### ISSUE TITLE
ios的$fetch没有根据content-type对数据进行处理。

### ISSUE THREAD

**Issue by zjzmyh** [bmfe/eros#10]
### 环境信息 
* 开发平台：mac
 * 开发工具及其版本 xcode 9

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> ios没有根据content-type对数据进行处理,一直是json格式，手动更改BMBaseRequest.m代码后，eros install就会被还原。还希望从根本解决一下
### 什么场景下会复现这个问题，复现率是多少。
> 百分百复现，调用即复现。

**Comment by xiaohuapunk** [comment]
下个版本去掉默认 json 格式大概下周发布更新

**Comment by PerseveranceZ** [comment]
@zjzmyh 这个问题在目前的最新的 sdk 中已经 fix ，可以重新 eros init 一个项目，花个十多分钟来进行迁移，迁移过程中又什么问题可以随时反馈。https://github.com/bmfe/eros-template/wiki/update-ios#110-20171229
