### ISSUE TITLE
this.$navigator.setRightItem 样式问题

### ISSUE THREAD

**Issue by ChenArno** [bmfe/eros#101]
### 简略的描述你的问题。
this.$navigator.setRightItem(
        { text: "保存", fontSize: '28',  textColor: "#df4f45" },()=>{})
设置text内容时，当显示内容过短时，靠做对齐，为了样式的显示，应当显示右对齐。
eros-cli  版本2.0.6-beta.4
"eros-widget": "^1.0.1-beta.8"
### 环境信息 
> 例子：
> * 开发平台：darwin\/windows/linux
> * node 版本：8.x.x
> * npm 版本：5.x.x
> * 调试类型：模拟器/真机
> * 调试系统版本: ios 8
> * 开发工具及其版本 xcode 9

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 例：bmImage module 中不支持传递参数的类型，导致的崩溃。
### 什么场景下会复现这个问题，复现率是多少。
> 例：百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：

**Comment by hanliuxin5** [comment]
我看了这个界面 Android 的布局，是右对齐的

**Comment by aa453509345** [comment]
we have fixed this bug  in version 2.1.3
