### ISSUE TITLE
所有的image loading菊花动效建议

### ISSUE THREAD

**Issue by shenmashi** [bmfe/eros#102]
image 默认的时候有出现loading 菊花动效，但是这样的话，如果图片较多较大，可能会出现满屏菊花动效，比较丑陋！

建议1. 在native.js 可以自行配置全局的image是否需要loading 菊花动效
       2.在image标签上允许设置是否需要loading 菊花动效，覆盖native的设置

**Comment by myliuyx** [comment]
补充了  placeholder 属性， 只有当此属性等于“default”的时候才会展示菊花加载效果，默认不展示
