### ISSUE TITLE
[Bug] bm_imagepicker not found

### ISSUE THREAD

**Issue by DONGChuan** [bmfe/eros#103]
The first time when I build the demo by android studio. I got `bm_imagepicker not found` error.  Solved by adding 

```
flatDir {
    dirs '../wxframework/libs'
}
```

in `build.gradle` of the project to indicate where `bm_imagepicker.arr` is.

And my environment:
buildToolsVersion 26.0.2
Gradle 4.1
GradleToolVersion 3.0.0

**Comment by myliuyx** [comment]
thank you！
We already have, in the app build. Gradle
