### ISSUE TITLE
请问eros可以使用natjs吗？

### ISSUE THREAD

**Issue by zassq** [bmfe/eros#104]
首先谢谢EROS这个这么好的库，让我们这些完全不懂移动端的小白也能尝试一把，比原生weex省心太多。

我现在的项目需要下载音乐文件，然后播放，我看到natjs有下载和简单音乐播放的功能，但是他们需要用weexpack创建的项目才能用，请问该如何手动导入他们的module进eros呢？

另外，需要集成google map的话，该如何入手？能请大神指个方向吗？

最后，如果提问错了地方，请海涵。谢谢。

**Comment by xiaohuapunk** [comment]
集成 natjs 需要原生开发来搞，如果不了解原生开发那会困难点

**Comment by PerseveranceZ** [comment]
@zassq nat的音频开发如果会原生的话可以自己接入 不会的话可以等我们开发完组件化之后 拓展此功能，而 google map 集成应该和我们 sdk 中的 amap 集成类似，你可以看下 sdk 中的源代码

**Comment by zassq** [comment]
@xiaohuapunk @PerseveranceZ 好的，谢谢。

**Comment by zassq** [comment]
@xiaohuapunk @PerseveranceZ 瞎折腾貌似被我弄成了！起码代码有效果。。。
我在github下了nat module的源码，然后添加了一个自己的library

照贴了nat的build.gradle进去
替换了几个依赖，特别是weex sdk，用了eros集成的sdk版本
```
// compile 'com.android.support:appcompat-v7:25.4.0'
// compile 'com.taobao.android:weex_sdk:0.18.0'
compile project(':sdk')
compile 'com.instapp.nat:transfer:2.0.0'
compile 'com.instapp.nat:media-audio:2.0.0'
```

然后在app.java里注册module
```
try {
     WXSDKEngine.registerModule("audio", Audio.class);
     WXSDKEngine.registerModule("transfer", Transfer.class);
} catch (WXException e) {
     e.printStackTrace();
}
```

然后再把node_module下的natjs的代码copy了出来，新建了个plugin的文件夹在js下面



之所以没有用natjs自己的包，是因为有个问题我一直不知道怎么弄，就是nat的module名称是这样的
```
audio = weex.requireModule('nat/media/audio');
```
我实在不知道怎么设置这个`nat/media/audio`的module名，我试过这样
```
WXSDKEngine.registerModule("nat/media/audio", Audio.class);
```
还有这样
```
WXSDKEngine.registerModule("NatMediaAudio", Audio.class);
```
但是都不work...


所以我只好按前面quote的那样，自己改成
```
WXSDKEngine.registerModule("audio", Audio.class);
```
然后在对应的js里
```
audio = weex.requireModule("audio");
```

vue文件里
```
Nat.audio.play("http://cdn.instapp.io/nat/samples/audio.mp3");
```
就能播放出音乐了，这样是不是算把nat的module集成进去了？
然后最重要就是想请教一下如何设置module名称的问题，谢谢

---
nat audio module [传送门](https://github.com/natjs/weex-nat-media-audio)

**Comment by myliuyx** [comment]
如果你已经可以播放音乐了肯定证明你已经成功集成了natjs 了。

设置你的module名称的问题  其实就是你的
 WXSDKEngine.registerModule("audio", Audio.class);
比如你可以 
WXSDKEngine.registerModule("NatMediaAudio", Audio.class);
那么你在js就可以
audio = weex.requireModule("NatMediaAudio");

**Comment by yp199618** [comment]
您好,请问这一句代码使用写在什么位置?
WXSDKEngine.registerModule("audio", Audio.class);
