### ISSUE TITLE
安卓版本切换横屏会闪退，eros的demo也有这个问题 #90

### ISSUE THREAD

**Issue by shaibaoj** [bmfe/eros#105]
安卓版本切换横屏会闪退，eros的demo也有这个问题 #90

这个问题上提提过，修改了 ，其实还是会闪退，没有测底修改

**Comment by PerseveranceZ** [comment]
@hanliuxin5 @myliuyx (#90)

**Comment by hanliuxin5** [comment]
我看了当前 https://github.com/bmfe/WeexErosFramework 的代码，是因为我只提到的是 feature 分支，好像并没有合并到发布分支里。。

不太清楚你们的发布流程，但是简单来说就是最新的代码里没有我的改动的代码

**Comment by PerseveranceZ** [comment]
@shaibaoj  今天的发布会修复此问题 到时候通知你哈

**Comment by PerseveranceZ** [comment]
@shaibaoj https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=_20180322 already fixed.
