### ISSUE TITLE
[Question] How to use stylus in eros?

### ISSUE THREAD

**Issue by DONGChuan** [bmfe/eros#106]
I just add `stylus` and `stylus-loader` in devDependencies and set `lang='stylus'` in <style>. But got cssSyntaxError. Do I need any more configurations to use stylus?

**Comment by PerseveranceZ** [comment]
@DONGChuan Hi

1. `eros-cli` already add stylus and stylus-loader
2.  Weex only support single class selector currently, and only support a subset of CSS Rules. [docs](http://weex.apache.org/cn/guide/use-vue.html#yang-shi)

Do you use nested writing?

**Comment by PerseveranceZ** [comment]
@DONGChuan 
eros-cli upgrade to 2.0.7-beta.6, support sass less stylus.

**Comment by DONGChuan** [comment]
Thank u!! 👍
