### ISSUE TITLE
WxcGridSelect 和recycle-list 在一个页面中使用页面会闪退

### ISSUE THREAD

**Issue by super-chen** [bmfe/eros#115]
### Your questions.
- WxcGridSelect 和recycle-list 在一个页面中使用页面会闪退
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin
- Node: 8.10.0
- Npm: 5.6.0

**Comment by PerseveranceZ** [comment]
@super-chen eros-cli 版本多少

**Comment by PerseveranceZ** [comment]
Make sure your eros-cli is newset and try it, if it is still not work, you can create new issue for `weex-ui` and `weex-loader`.

**Comment by PerseveranceZ** [comment]
https://github.com/alibaba/weex-ui/issues/219

目前 recycle-list 使用上面有很多限制 http://weex-project.io/cn/references/components/recycle-list.html#zhu-yi-shi-xiang
需要等到 recycle-list 支持

暂时不建议在recycle-list 里面使用weex-ui 组件 建议用list 就好
此处新recycle-list的定位是具有很强回收和复用的能力list 更多场景是 data -view 绑定好的特定场景
