### ISSUE TITLE
采用原生方式实现微信底部四个tab的导航

### ISSUE THREAD

**Issue by anicy** [bmfe/eros#116]
### Your questions.
-请问使用eros的androidframework的时候，想用原生做底部导航，类似微信下方导航，有现有module吗？ 
 若是没有，android客户端应该基于eros提供的framework怎么实现？

![image](https://user-images.githubusercontent.com/8448282/37896093-a002d4d0-3115-11e8-9a69-6908ee5a5faf.png)

-

### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
@anicy
weex-ui 中已经有类似的 tab 使用 https://github.com/alibaba/weex-ui/tree/master/example/tab-bar
也可以用 weex 自行封装 https://github.com/bmfe/eros-template/tree/master/src/js/components/tabs
