### ISSUE TITLE
关于原生module的扩展

### ISSUE THREAD

**Issue by anicy** [bmfe/eros#117]
- 背景
我想基于weexframework 进行自定义模块开发，而这个模块单独作为应该lib存在的，看官方demo中有amap的扩展是作为插件形式存在的，且在framework中有注册，

![Uploading Jietu20180326-165649.jpg…]()

开发者在进行自定义模块开发的时候是否也需要对weexframework进行配置？ 或者有其他的方式，谢谢

PluginComponentsAndModules  -- 》 

```
   private HashMap<String, String> getPluginAmapModules() {
        HashMap<String, String> amapMoudles = new HashMap<>();
        amapMoudles.put("amap", "com.plugamap.module.WXMapModule");
        return amapMoudles;
    }

```

**Comment by myliuyx** [comment]
正在做这一块的重构和优化， 开发者是可以 自已定义模块开发的。
现在的注册 Components 或者 Modules 你可以暂时的 注册在 wxframework/res/xml/app_config.xml 文件里。里面有一些我们拓展的  component 和 module 映射关系， 你可以根据这个 参考下 如何 自定义 component 和 module  的开发。

如果你自己拓展的lib 库相关的话 你可以多先借鉴下 我们的 amap。 
nexus 是一个base库， 很多公共的、抽象的、全局的。 基类都会放在这儿。

具体自己的lib库逻辑可以按照你自己的逻辑写不需要太多的考虑 weex 或者eros. 
仅在 最后你可能需要 有一个和 weex 对接的  component 和 module 时 参考下 现在已有的。

**Comment by anicy** [comment]
了解了，谢谢
