### ISSUE TITLE
ios端进行pack无法运行

### ISSUE THREAD

**Issue by anicy** [bmfe/eros#118]
### Your questions.
-
-ios10中使用eros pack ios 出现白屏
### Environment. 
- Mobile model: iphone6s
- Mobile system: iOS 10
- Dev platform: darwin\

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 采用eros init 默认下载的template中的bundle能正常看到demo的展示页面
- 若执行 eros pack ios ，然后build到真机中，出现如下错误

```

【error】本地资源不存在: /var/mobile/Containers/Data/Application/D9E348A2-4596-4D67-8D12-2870B97F3277/Library/Bundlejs/bundle(null)/pages/demo/index.js
2018-03-27 23:20:16.399977 WeexEros[15997:4138985] <Weex>[error]WXMonitor.m:250, Request to (null)/pages/demo/index.js?random=1736450987 occurs an error:未能完成操作。（“BMNetWorkIntercepet”错误 -400。）
```
请问是哪里缺少配置吗？ 并没有对代码进行修改过

ps： 使用同样的源代码，执行 eros pack android，在android端能正常使用。

**Comment by PerseveranceZ** [comment]
@anicy eros init 出来的项目 pack 应该没有问题吧，你可以尝试 init 出来的 platforms ，迁移到自己项目中。

**Comment by PerseveranceZ** [comment]
升级到脚手架最新即可 @anicy

**Comment by anicy** [comment]
DONE
THANKS

**Comment by pidogc** [comment]
@anicy 你好，我現在也出現了這個問題，但是腳手架已升級到最新，一樣無法解決，請問你當時是怎麼解決的，謝謝
