### ISSUE TITLE
iOS分享问题

### ISSUE THREAD

**Issue by AsaYao** [bmfe/eros#123]
1.iOS9+ 好像不会走
![image](https://user-images.githubusercontent.com/17565106/38084059-096763cc-337e-11e8-891f-0c6e814773e3.png)
 运用新的方法:
![image](https://user-images.githubusercontent.com/17565106/38084078-1ad63b42-337e-11e8-8728-0db82a784932.png)
2.方法里的判断有错误：
![image](https://user-images.githubusercontent.com/17565106/38084122-39a67ba4-337e-11e8-8a1b-68cdc1ce7b26.png)
支付和分享冲突，详情看方法体里面的内容。
参考思路：要么写在一个if里面判断完，要么分开写。
3.注意配置白名单，urlscheme等必要的条件。

**Comment by PerseveranceZ** [comment]
@AsaYao 非常感谢你的反馈，我们近期会修改，如果您有时间，也可以给我们 pr 。

**Comment by xiaohuapunk** [comment]
你本地的代码不是最新的，更新一下iOS依赖，然后在试试看，如果ok了请关闭issue，有的问题的话请回复一下谢谢~！

**Comment by PerseveranceZ** [comment]
最新代码中已经 fix.
