### ISSUE TITLE
ios端list组件的下拉刷新loading不居中

### ISSUE THREAD

**Issue by GeekBlue** [bmfe/eros#124]
### Your questions.
- list组件 :showRefresh="true" 开启eros的下拉刷新的loading，在安卓端表现正常，ios端出现loading位置不稳定现象，表现为有时居中，有时稍微偏左一点，有时直接挨着屏幕最左端，真机（iphone5、5s）（ios10.3.3、ios11.2.6）和模拟器（iPhone5、6、8、x）（ios11.2）都是这样
- 如果不使用eros的下拉刷新，自己添加`<refresh></refresh>`组件的话可以正常居中
### Environment. 
- Mobile model: iPhone5、6、8、x
- Mobile system: ios10.3.3、ios11.2.6
- Dev platform: win10运行Mac虚拟机
- Node: 8.1.0
- Npm: 5.6.0
脚手架版本2.0.7-beta.6

### Reappearance of the problem (It's best to have a screenshot).
![1](https://s1.ax1x.com/2018/03/31/9xeKfA.jpg)
![2](https://s1.ax1x.com/2018/03/31/9xellt.jpg)
![3](https://s1.ax1x.com/2018/03/31/9xe16P.jpg)

**Comment by xiaohuapunk** [comment]
需要远程看一下，或者来个demo

**Comment by xiaohuapunk** [comment]
多半是因为你的样式原因导致的，先关闭，如有问题请重新打开次isues
