### ISSUE TITLE
Android上面设置setNavigationInfo无任何效果

### ISSUE THREAD

**Issue by super-chen** [bmfe/eros#129]
### Your questions.
-1、Android上面设置setNavigationInfo无任何效果，IOS上面代码是正常运行的
-2、Android上面如果先设置setRightItem，在设置setNavigationInfo，顶部NavigationBar会莫名消失了

### Environment. 
- Mobile model: 三星 S7
- Mobile system: 7.1.0   /  API 25
- Dev platform: windows
- Node: 8.10.0
- Npm: 5.6.0

**Comment by hanliuxin5** [comment]
你贴下``js``代码呢

更建议你使用 https://alibaba.github.io/weex-ui/#/cn/packages/wxc-minibar/

**Comment by super-chen** [comment]
如下是设置navigator的代码，感谢查阅

created () {
            this.$navigator.setRightItem({
                textColor: '#000000',
                fontSize: '32',
                fontWeight: 'normal',
                image: 'bmlocal://assets/audit/icon_audit_record@2x.png'
            }, () => {
                this.$router.open({
                    name: 'audit.normalRecordList',
                    type: 'PUSH'
                });
            });
            this.$router.getParams().then(data => {
                this.$notice.loading.show('加载中');
                if (data.id) {
                    this.$navigator.setNavigationInfo({ title: '常规稽核 (2/3)' });
                    request.getNormalTree(data.id).then(data => {
                        this.moduleList = data;
                        this.$notice.loading.hide();
                    })
                } else {
                    this.$navigator.setNavigationInfo({ title: '常规稽核 (1/3)' });
                    request.getNormalModule().then(data => {
                        this.moduleList = data;
                        this.$notice.loading.hide();
                    })
                }
            })
        }

**Comment by hanliuxin5** [comment]
之前我没用过这个，我现在在我手机上试了试这个`this.$navigator`相关的功能，好像我也遇到了不少的问题。
暂时建议你先使用纯 css 来实现这个导航条的功能。

**Comment by poerlang** [comment]
试试这个，以前的版本，这招在我这边管用：安卓 **RouterModel** 这个类里面加入如下代码
 
public String statusBarStyle = "Default"; //如果没有默认值，会导致某些情况下 $navigator 设置无效

**Comment by PerseveranceZ** [comment]
@moketao 感谢反馈 我们会在近期添加进去

**Comment by myliuyx** [comment]
public String statusBarStyle = "Default"; //如果没有默认值，会导致某些情况下 $navigator 设置无效
已添加~
