### ISSUE TITLE
请问bmAxios中data支持参数序列化吗？

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#130]
### Your questions.
- eros_widget中$axios模块，data参数默认接受Object，那么我想像axios一样可以全局配置data为序列化

### Environment. 
- Mobile model: Xiaomi
- Mobile system: 5.1.1
- Dev platform: Android
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 因为后台请求的参数是form格式，而不是object。
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
你应该是要去配置`Content-Type`这个属性来到达目的，你说的`接受Object`这个东西，其实是指在使用上框架对齐做了一次封装，让你以‘Object’的方式来填写参数

**Comment by PerseveranceZ** [comment]
你可以在请求拦截器里面做这件事情。@hopkinson

**Comment by hopkinson** [comment]
```
requestHandler(request, next) {
            request.data = qs.stringify(request.data)
            request.header['Content-Type'] = 'application/x-www-form-urlencoded'
            next()
        },
```
我这样写了 但是没执行。@PerseveranceZ

**Comment by hopkinson** [comment]
let tmp = request.header || {}
request.header = Object.assign({
 'Content-type':123
}, tmp)

**Comment by hanliuxin5** [comment]
你写的是什么？没太懂
