### ISSUE TITLE
bmAxios data参数对象->key中包含下划线时，ios请求时会给该key加双引号，导致后台接受不到

### ISSUE THREAD

**Issue by cox-yj** [bmfe/eros#131]
### Your questions.
-bmAxios post请求， data中的key中包含下划线时，在请求时会给该key加双引号，导致后台接受不到
-代码中显示

<img width="353" alt="f8b1296d-f178-4cc5-83ce-5f73849f025e" src="https://user-images.githubusercontent.com/20311488/38468940-ab7953b0-3b7f-11e8-92d3-486e5c170b51.png">

-xcode中显示：

<img width="337" alt="ee787ec9-f674-44be-8280-4c91500f8396" src="https://user-images.githubusercontent.com/20311488/38468951-df84e156-3b7f-11e8-8f9b-2a1f31de2f32.png">

-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS All

**Comment by xiaohuapunk** [comment]
双引号是ide对有字符的字符串添加的，为了查看log方便，不会改变实际的key，使用抓包工具看一下请求参数吧，另让后端看一下完整的请求数据是什么

**Comment by PerseveranceZ** [comment]
@cox-yj 还存在此问题么
