### ISSUE TITLE
建议在 eros 的 image 控件中加入原生 weex 的保存图片功能

### ISSUE THREAD

**Issue by poerlang** [bmfe/eros#132]
http://weex.apache.org/cn/references/components/image.html
请参阅上面链接中的 save 函数。

**Comment by poerlang** [comment]
升级到最新版即可

**Comment by akFace** [comment]
@moketao 升级到最新版了，怎么使用？ 貌似还没有保存图片的功能

**Comment by scyllarusllc** [comment]
SDK 16+ 就有这个save功能了。
