### ISSUE TITLE
关于选择图片this.$image.pick的bug

### ISSUE THREAD

**Issue by YaoguaiDa** [bmfe/eros#133]
- 机型：魅蓝s6
-问题描述：选择相册中的图片时，点开大图，选中之后返回，缩略图上显示未选中实际已选择

![image](https://user-images.githubusercontent.com/19499202/38537805-3c06bda6-3c56-11e8-8a67-24ebfef0baf2.png)
![image](https://user-images.githubusercontent.com/19499202/38537809-46380a82-3c56-11e8-89d9-cc4986967416.png)

**Comment by hanliuxin5** [comment]
确实有这个bug，开始修复中...

**Comment by hanliuxin5** [comment]
修复版本已提交测试，静待佳音

**Comment by myliuyx** [comment]
已经合并PR
