### ISSUE TITLE
想问下合适的混合开发方式

### ISSUE THREAD

**Issue by BoomToy** [bmfe/eros#134]
### Your questions.
- 你好，想问下如果基于Eros做混合开发（就是可能会嵌套一个H5单页面应用在其中），我该以哪种方式实现比较好
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 11.3
- Dev platform: mac
- Node: 8.11.1
- Npm: 5.6.0

**Comment by hanliuxin5** [comment]
`就是可能会嵌套一个H5单页面应用在其中` 没太明白你的意思，可否详细描述一下场景？

**Comment by PerseveranceZ** [comment]
@Johnny-Liang 可能你需要拓展 eros 的 webview，然后按照原先的 H5混合开发 的流程，定义交互和事件相应。
