### ISSUE TITLE
安装cli找不到相关依赖

### ISSUE THREAD

**Issue by usercao** [bmfe/eros#135]
![image](https://user-images.githubusercontent.com/13760476/38594937-78a95bd0-3d7b-11e8-8880-236543f8a579.png)

**Comment by PerseveranceZ** [comment]
@usercao 使用 cnpm 安装的吗，你可以通过 eros -v 看下打印版本号有没有报错

**Comment by usercao** [comment]
我是挂代理安装的，不会出现安装失败的问题，版本是最新的beta8

**Comment by PerseveranceZ** [comment]
@usercao 这几个报错应该没有关系，因为项目中 webpack 和 babel 分离了，你直接下载依赖运行 eros dev 应该没问题吧？

**Comment by usercao** [comment]
开发全程都是没有问题的，只是看到这几个依赖没有比较难受，希望项目组能够更新

**Comment by PerseveranceZ** [comment]
babel是放到项目中的 webpack 集成在脚手架中，如果强行解决，两边都下，会造成2个的下载时间都边长，目前还无法做到抽离 webpack 出来，等后续改版优化会考虑这个问题。
