### ISSUE TITLE
怎么安装weex-market里的插件

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#136]
### Your questions.
- 我想安装Weex Market里的插件，是通过什么方式？比如，weex-action-sheet。是手动集成进去还是可以用weexpack?
- 
### Environment. 
- Mobile model: android
- Mobile system: xiaomi
- Dev platform:mac
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
官方没有维护那个，基本不用想了

**Comment by PerseveranceZ** [comment]
@hopkinson 如果你没有原生经验，可以参考下这个 [issue](https://github.com/bmfe/eros-template/issues/104) ,不过要是插件的维护情况而定，很可能用不了。

**Comment by CGerAJ** [comment]
上面的issue 失效了 能提供一些这方面的帮助吗？

**Comment by PerseveranceZ** [comment]
@CGerAJ https://github.com/bmfe/eros/issues/104
