### ISSUE TITLE
geolocation获取定位时，返回了{status:9}是什么意思

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#137]
### Your questions.
- this.$geo.get()我直接在开发时候使用，为什么会返回{status:9}，9是代表什么意思？
- 是要配置 什么吗？但是我已经给了定位权限。
### Environment. 
- Mobile model: 红米
- Mobile system: 5.1.1
- Dev platform: android
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
-  发现一个问题，我新建工程的时候按照默认配置就可以获取定位信息
![image](https://user-images.githubusercontent.com/13248613/38657698-3dd90300-3e54-11e8-9a2e-a6c1e539f6d1.png)
如果我自定义包名，工程名就不能获取定位信息。
![image](https://user-images.githubusercontent.com/13248613/38657717-567e4118-3e54-11e8-900b-5e8fb10cfb54.png)

- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hopkinson** [comment]
把gradle.property那个文件改为默认的com.benwu.wx就好了。我放弃修改在android工程里改目录结构了

**Comment by myliuyx** [comment]
是的 因为定位使用的是第三方的高德地图， 默认的可以定位是因为我们申请了 高德的key.
而每一个 高德的key 都有签名的 所以你修改了 包名 就无法定位了。

如果你想继续使用的话 可以自行去高德地图申请个key，然后在native.js里 配上
 'amap': {
        'enabled': 'true',
        'iOSAppKey': '',
        'androidAppKey': ''
    }
