### ISSUE TITLE
mediator里为什么订阅了事件在别的页面不生效？

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#138]
我打算在mediator.vue里请求字典接口，然后注册事件
```
export default {
    data() {
        return {
            data: {}
        }
    },
    created() {
        this.$fetch({
            method: 'POST',
            name: 'sys/dict/list'
        }).then(res => {
            let {
                data
            } = res
            this.$event.emit('dict', data)
        }, error => {
            // 错误回调
        })
    }
}
```

然后在别的页面设置其回调

 ```
 created() {
        this.$event.on('dict', data => {
            this.dict = data
        })
    },

```

### Your questions.
-  结果：别的页面没收到数据
-  没思路，不想把字典数据放在$storage做持久化存储,但是又不知道能不能在medicator里实现

### Environment. 
- Mobile model: xiaomi
- Mobile system: android 5.1.1
- Dev platform: mac
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
@hopkinson 首先你需要确定 你的 别的页面是否已经 open ，或者是在你的打开流程中，如果这个页面都不存在，你事件都没订阅
