### ISSUE TITLE
安卓环境打开，sdk，nexus的依赖没内容

### ISSUE THREAD

**Issue by puxiaoshuai** [bmfe/eros#139]
### Your questions.
-安卓环境打开，sdk，nexus的依赖没内容，
-
### Environment. 
- Mobile model: android
-
- Dev platform: /windows
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 资源没拉取下来
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
@puxiaoshuai `eros install` 失败，确保网络，确保 `git bash` 已经设置为你的 .sh 文件的默认执行程序，可通过右键默认程序来设置。

**Comment by puxiaoshuai** [comment]
确保 git bash 已经设置为你的 .sh 文件的默认执行程序，可通过右键默认程序来设置。这句不是太懂，怎么设置

**Comment by PerseveranceZ** [comment]
进入 scripts下面有.sh 文件 右键 选择默认程序为 git bash （注意 不是 git for windows），没有 git bash 就需要去安装 git

**Comment by ColinCLL** [comment]
我也遇到了类似的问题。环境是win10。eros install 没有把文件拉下来。

使用git bath 打开直接闪退。

另外，设置默认打开程序的话，里面没有git bash选项 ，只有git for windows.
