### ISSUE TITLE
添加定位后刷新没用

### ISSUE THREAD

**Issue by hejie20170930** [bmfe/eros#14]
### 简略的描述你的问题。
> 例：下拉刷新添加定位后失效
### 环境信息 
> 例子：
> * 开发平台：windows
> * node 版本：8.0.0
> * npm 版本：5.3.0
> * 调试类型：模拟器
> * 调试系统版本: 安卓4.4.3
> * 开发工具及其版本 vscode

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 例：下拉刷新添加定位后失效
### 什么场景下会复现这个问题，复现率是多少。
> 例：百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：
![image](https://user-images.githubusercontent.com/32407307/34473593-ce6a276c-efaf-11e7-884a-078e90df013e.png)

**Comment by PerseveranceZ** [comment]
业务使用问题 已经自行 fix
