### ISSUE TITLE
Android libAMapSDK_MAP_v6_1_0.so' has no sections

### ISSUE THREAD

**Issue by FredLiu111** [bmfe/eros#140]
### Your questions.
根据入门文档，搭建环境之后，Android Studio 引入Android项目后，报错两个，地图相关功能无法打开。日志如下：
问题一：
Error:error: the input file '/Users/xxxx/ErosWeex/erosweex/platforms/android/WeexFrameworkWrapper/app/build/intermediates/transforms/mergeJniLibs/samplechannel/debug/0/lib/x86/libAMapSDK_MAP_v6_1_0.so' has no sections

问题二：
Error:A problem was found with the configuration of task ':sdk:countDebugDexMethods'.
> Directory '/Users/liupeng/ErosWeex/erosweex/platforms/android/WeexFrameworkWrapper/sdk/build/outputs/aar/sdk-debug.aar' specified for property 'inputDirectory' is not a directory.

**Comment by aa453509345** [comment]
是直接Eros init出来的项目吗

**Comment by FredLiu111** [comment]
是直接Eros init出来的项目。之前从Eros 二维码扫码下载的Demo，也是地图功能打不开。小米6手机 ，Android 8.0系统。

**Comment by hanliuxin5** [comment]
demo app 地图功能打不开，指的是 `$router.toMap()` 吗

**Comment by FredLiu111** [comment]
是 $router.toMap(),点击没有响应

**Comment by myliuyx** [comment]
toMap 没实现。 是一个空方法

**Comment by PerseveranceZ** [comment]
@FredLiu111 我们马上会废弃这个方法，后续地图相关会有全新的文档，还请耐心等待。

**Comment by poerlang** [comment]
同样遇到这样的问题，编译时报两个错，但不影响导出 apk ，不知为何，等更新。

**Comment by PerseveranceZ** [comment]
@FredLiu111 @moketao 目前插件化已完成，可自行 init amap 使用，可 init 项目根据文档来使用[https://bmfe.github.io/eros-docs/#/zh-cn/plugin_amap](https://bmfe.github.io/eros-docs/#/zh-cn/plugin_amap)
