### ISSUE TITLE
最近几个版本， webSocket.onopen = function (e) {};  这样的写法会导致即便连接了 onopen 也无法被激活

### ISSUE THREAD

**Issue by poerlang** [bmfe/eros#141]
webSocket.onopen = function (e) {
      console.log('onopen', e);
};

发现改成如下格式能正常运行：
webSocket.onopen( function (e) {
      console.log('onopen', e);
});

也可能是我这边的个例，发出来确认一下。

**Comment by xiaohuapunk** [comment]
onopen是个方法，参数为Function 即 `onopen(callback)`，所以你上面的写法是有问题的

**Comment by PerseveranceZ** [comment]
@moketao 有可能是最近这个版本 weex 修改了 webSocket 的写法。

**Comment by poerlang** [comment]
是这几个版本 weex 官方文档的写法不对，还沿用旧的写法，而 eros 的websocket的文档，是指向weex官方错误的文档的。当然，weex官方肯定有责任修改。不过，我感觉 eros 的反应速度应该更快一些。

**Comment by poerlang** [comment]
另外，weex的 websocket 模块，和现在 eros 现在用的 bmWebSocket 模块，是两套代码，所以建议还是另外编辑一份文档比较好，不必指向weex官方文档。

**Comment by poerlang** [comment]
https://github.com/bmfe/eros-docs/pull/5

**Comment by poerlang** [comment]
提交了 pr
