### ISSUE TITLE
setNavigationInfo方法异常问题

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#142]
### Your questions.
-
-
### Environment. 
- Mobile model: M6
- Mobile system: Android 8
- Dev platform: windows
- Node: 8.11.1
- Npm: 5.6.0

### What do you think may be caused by the analysis of the problem.
- this.$navigator.setNavigationInfo({
    title: '',                              // 中间区域标题    
    navShow: true,                          // 是否显示导航栏
    statusBarStyle: 'Default'               // 状态栏文字颜色：Defautl 黑色， LightContent 白色
}
- 当前设置下statusBarStyle未能生效。

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
比较难以找到你这个机器进行测试,估计是手机型号导致的问题.
暂时用`weex-ui`来替代你的界面显示?

**Comment by myliuyx** [comment]
在 Android 版本4.4 以上的小米、魅族可以设置statusBarStyle 状态栏文字颜色，其他安卓手机必须在6.0以上才会生效！
