### ISSUE TITLE
请问如何全局引入通用scss文件？

### ISSUE THREAD

**Issue by lczhai** [bmfe/eros#143]
最近在尝试用咱们这个，昨天写了一个通用的scss文件，但不知道在哪里全局引入，难道非得挨个vue页面单独import嘛？

**Comment by PerseveranceZ** [comment]
还没在 eros 中尝试过在 js 中引入 scss，如果可以，放到 appboard 对应的路径就行。
如果不行，只能单独 import，毕竟 app 是个 多页面应用，和单页面有所区别。
