### ISSUE TITLE
在其它页面如何获取mediator实例中的data数据？

### ISSUE THREAD

**Issue by huanghaodong** [bmfe/eros#145]
我知道怎么修改mediator实例中的data，就是在mediator实例中用this.$event.on注册一个修改data事件，然后在其他页面的实例中触发这个事件。
      但是，我想在其它页面获取mediator实例中的data怎么弄？业务场景就是，我登陆后，在login页面触发mediator中绑定的指定事件来将登陆后服务器返回的用户信息（如，昵称）存入data，那么怎么在个人中心页面获取到这个昵称？若mediator中昵称改变后，如何让个人中心页面中的昵称自动改变？
      这个时候想起了用vuex进行状态的管理,这在单页面中没有问题(状态可以共享),但是多页面每个页面都是一个新的实例,这样就没有办法使用vuex共享状态了。怎么办...

eros文档上有段话：”mediator/index.js 会在 app 启动的时候，作为第一个 js bundle 被执行，并且常驻内存，可以在bus上绑定事件，保存数据和状态，可以做类似 sessionStore 或者 Vuex的功能”，可是这vuex功能具体怎么实现呢

**Comment by hanliuxin5** [comment]
vuex 那样的功能可能目前不太可行吧.

**Comment by PerseveranceZ** [comment]
@huanghaodong 可以实现 不过目前可能要自行封装下 2边都通过发布订阅来交互 你在业务中去mediator的数据前也要 emit 一下 然后紧接着通过 on 来接 ，其实可以把mediator 改成 js 入口形式文件 通过 new Vue 来控制 data 类似 vuex 的封装应该可以，可以先自己实现，或者通过storage 来做

**Comment by zhouxianjun** [comment]
> @huanghaodong 可以实现 不过目前可能要自行封装下 2边都通过发布订阅来交互 你在业务中去mediator的数据前也要 emit 一下 然后紧接着通过 on 来接 ，其实可以把mediator 改成 js 入口形式文件 通过 new Vue 来控制 data 类似 vuex 的封装应该可以，可以先自己实现，或者通过storage 来做

额。。。大佬，有例子吗？
