### ISSUE TITLE
Android里怎么把导航条里的图片内容给清除？

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#146]
### Your questions.
-  请问设置了内容为image的导航条，怎么在页面退出时清除？
-  试过了以下的方法但是不行
![image](https://user-images.githubusercontent.com/13248613/39230979-231817a8-489b-11e8-8b6b-e70e6362cfc3.png)

### Environment. 
- Mobile model: xiaomi
- Mobile system: Android 5.1.1
- Dev platform: mac
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
个人建议使用weexui的导航条控件。
或者你设置一个颜色为导航条颜色的图片？
