### ISSUE TITLE
$router.toMap在安卓机无效

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#148]
### Your questions.
```
this.$router.toMap({
                type: 'NAVIGATION', //type类型：NAVIGATION(表现方式为：地图上添加起点终点标示大头针，终点标示上面有个导航的按钮)
                title: '页面标题', //页面标题
                navigationInfo: {
                  title: '故宫博物院',
                  address: '北京市东城区景山前街4号',
                  longitude: '116.397026',
                  latitude: '39.918058'
                }
            })
```
在安卓没办法跳转。

### Environment. 
- Mobile model: xiaomi
- Mobile system: android 5
- Dev platform: mac
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
参考 https://github.com/bmfe/eros/issues/140

**Comment by myliuyx** [comment]
toMap 已经废弃， 如果需要使用地图的话可以参考 amap 文档使用对应的标签
