### ISSUE TITLE
路由信息与statusbar设置优先级问题

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#149]
### Your questions.
-在route.js中设置了非空title后，通过router.open方法和setNavigationInfo动态设置的状态栏信息不会生效。
-
### Environment. 
- Mobile model: android
- Mobile system: 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 希望api方法的优先级能够大于route.js设置
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
已修复，近期上线
