### ISSUE TITLE
安卓as启动eros项目报错

### ISSUE THREAD

**Issue by xiaofeng283** [bmfe/eros#150]
### Your questions.
- 安卓端as编辑器启动报错
![image](https://user-images.githubusercontent.com/20809418/39551192-9021891e-4e96-11e8-823b-3abde5f36d32.png)
查看日志：
![image](https://user-images.githubusercontent.com/20809418/39551209-a3202d18-4e96-11e8-8f1d-f97a115985a2.png)

### Environment. 
- Mobile model: android
- Mobile system: 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 是不是gradle插件引起的？我用的是gradle-4.4-all.zip，但是换到gradle-4.1后显示：
Minimum supported Gradle version is 4.4. Current version is 4.1.
这是根据提示和日志等信息综合猜测的，卡在这里好久了，希望能解决下

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
你可以选择一个你本地支持的gradle版本，比如你选择4.1的话，相应的插件可以配置为3.0.1
```
 classpath 'com.android.tools.build:gradle:3.0.1'

distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

```

**Comment by xiaofeng283** [comment]
上面的问题解决了，但是出现了这个错误，
![image](https://user-images.githubusercontent.com/20809418/39579795-2f913a16-4f1a-11e8-92df-3867daf4e7af.png)，需要怎么调整呢？

**Comment by xiaofeng283** [comment]
as版本是3.1.2的

**Comment by xiaofeng283** [comment]
重新导入项目后问题已解决，感谢@hanliuxin5
