### ISSUE TITLE
Android setNavigationInfo里的title属性无效，使用setCenterItem的text属性正常。

### ISSUE THREAD

**Issue by zhangning12328** [bmfe/eros#151]
### Your questions.
-Android setNavigationInfo里的title属性无效
-使用setCenterItem的text属性正常

### Environment. 
- Mobile model: nubia NX511J
- Mobile system: Android5.0.2
- Dev platform: macOS 10.13.4
- Node: 8.9.4
- Npm: 5.6.0

### What do you think may be caused by the analysis of the problem.
```
- this.$navigator.setNavigationInfo({   //使用些方法，Android上标题内容为空，iOS正常
                    title: "标题",       
                    navShow: true,
                    statusBarStyle: 'LightContent'
                }, () => {});      
- this.$navigator.setCenterItem({    //使用些方法，Android上标题内容可以正常显示
                    text: "标题",
                    textColor: '',
                    fontSize: '32',
                    fontWeight: '900',
                    image: ''
                }, () => {})
```

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by akFace** [comment]
同遇到一样的问题

**Comment by akFace** [comment]
navShow: false 隐藏也不起作用

**Comment by myliuyx** [comment]
已经修复 下个版本修复~

**Comment by myliuyx** [comment]
已修复，使用新的库版本：

     //eros base
    implementation 'com.github.bmfe.eros-nexus:nexus:1.0.1'
    implementation 'com.github.bmfe:WeexErosFramework:1.0.1'

    //eros plugin
    implementation 'com.github.bmfe:eros-plugin-android-amap:1.0.1'
    implementation 'com.github.bmfe:eros-plugin-android-getui:1.0.1'
    implementation 'com.github.bmfe:eros-plugin-android-wxshare:1.0.1'
    implementation 'com.github.bmfe:eros-plugin-android-wxpay:1.0.1'

**Comment by akFace** [comment]
@myliuyx  有bug，换成1.0.1库版本。页面切换（路由跳转）会导致APP闪退。

**Comment by myliuyx** [comment]
@kang558  重新init 一个 或者 你diff 下 WeexFrameworkWrapper build.gradle  和 app 目录下的  build.gradle  2个文件。
