### ISSUE TITLE
eros install 做了什么，我可否是直接运行install.android.sh文件代替这个install 操作

### ISSUE THREAD

**Issue by ColinCLL** [bmfe/eros#153]
### Your questions.
- eros install 后无任何反应，打算在git bash运行。scripts/install.android.sh，代替eros install是否可行，会不会留下什么隐患
-
### Environment. 
- Dev platform: win7/10
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
![image](https://user-images.githubusercontent.com/19434659/39672289-2919c99a-515a-11e8-872a-fe7a16f1b3c3.png)

![image](https://user-images.githubusercontent.com/19434659/39672307-6483774c-515a-11e8-93e0-3b0359552885.png)

- 使用网易严选的demo 也是无效。

### Reappearance of the problem (It's best to have a screenshot).
- 能够在成功使用eros install  或者 找到方法代替 eros intall 最终能够在android studio编译成功。

**Comment by hanliuxin5** [comment]
你把你当前的项目目录贴出来看一看呢

**Comment by ColinCLL** [comment]
我看源码发现原因了，是eros-cli那边，install模块的核心代码被注释了。麻烦改一下，跑一遍看看还有合适呢吗没通。传上npm,谢谢。

**Comment by PerseveranceZ** [comment]
@ColinCLL 新版本中已经不需要 eros install 了，文档我们已经更新了 [https://bmfe.github.io/eros-docs/#/zh-cn/base_init](https://bmfe.github.io/eros-docs/#/zh-cn/base_init)，安卓直接导入项目同步即可。

**Comment by ColinCLL** [comment]
好的明白，谢谢
