### ISSUE TITLE
bmGeolocation应该怎么配置并使用？

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#154]
### Your questions.
- 我想调用 `this.$geo.get()`获取当前位置。之前旧版是要配置高德地图的key之后就可以了。但是新版我不知道在哪里配置高德地图的key。
- Jony说是**要init**，去看文档。但是我没有在文档里找到相关的资料。不知道在哪里init。
- 所以能提供详细的指引吗？
### Environment. 
- Mobile model: xiaomi
- Mobile system:android
- Dev platform: mac
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
请在详细描述一下你遇到的问题，比如哪个方法等等

**Comment by PerseveranceZ** [comment]
@hopkinson 看了下文档确实遗漏了初始化方法的介绍，今天我们稍后补下 init 高德地图的文档。

**Comment by xiaohuapunk** [comment]
@hopkinson 文档已补充 [文档](https://bmfe.github.io/eros-docs/#/zh-cn/eros_widget?id=geo%EF%BC%88%E5%BD%93%E5%89%8D%E4%BD%8D%E7%BD%AE%E4%BF%A1%E6%81%AF%EF%BC%89)
