### ISSUE TITLE
首页设置导航条不生效

### ISSUE THREAD

**Issue by myfanhua** [bmfe/eros#155]
### Your questions.
-首页设置导航条不生效
-
### Environment. 
- Mobile model: Nexus 5X
- Mobile system: android 8.0
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
-  
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
![qq 20180507141254](https://user-images.githubusercontent.com/22782462/39687388-d21c35ea-5200-11e8-82bb-278b7b7cf5c4.png)
![qq 20180507141310](https://user-images.githubusercontent.com/22782462/39687389-d2762f0a-5200-11e8-9542-7226564e07f5.png)

**Comment by PerseveranceZ** [comment]
@myfanhua 如果我没看错，你写的是`cros`

**Comment by myfanhua** [comment]
@PerseveranceZ   已纠正 但还是不行  运行环境是 andriod studio的安卓模拟器 ， 然后发现 运行官方的demo 也是无法设置导航栏的

**Comment by PerseveranceZ** [comment]
@myfanhua 感谢反馈，无效应该是针对于首页，我们会于近期修复一下，首页的你可以暂时先通过 weex 自行实现或者引入 weex-ui

**Comment by myfanhua** [comment]
@PerseveranceZ   可是我用eros init 创建的模板 在 andriod studio 模拟器中(安卓8.0)  demo里设置导航栏 的隐藏显示也是无效的

**Comment by myliuyx** [comment]
近期修复。代码已经提交。

**Comment by myliuyx** [comment]
已修复，使用新的 插件版本即可。
    //eros base
    implementation 'com.github.bmfe.eros-nexus:nexus:1.0.1'
    implementation 'com.github.bmfe:WeexErosFramework:1.0.1'

    //eros plugin
    implementation 'com.github.bmfe:eros-plugin-android-amap:1.0.1'
    implementation 'com.github.bmfe:eros-plugin-android-getui:1.0.1'
    implementation 'com.github.bmfe:eros-plugin-android-wxshare:1.0.1'
    implementation 'com.github.bmfe:eros-plugin-android-wxpay:1.0.1'
