### ISSUE TITLE
直接跟着教程流程走，不能生成项目

### ISSUE THREAD

**Issue by ColinCLL** [bmfe/eros#156]
### Your questions.
-Cause: duplicate entry: android/support/v4/view/BetterViewPager.class
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 点那个小锤子make project后报错。

![image](https://user-images.githubusercontent.com/19434659/39691908-b4192ee8-5211-11e8-8e5b-9814839e6d34.png)

- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
重复依赖问题 正在解决。

**Comment by PerseveranceZ** [comment]
@ColinCLL 目前 android 项目存在重复引用问题和编译版本问题，已经修复，预计明天发布，到时候可以重新 init 导入项目，请稍做等待

**Comment by myliuyx** [comment]
@ColinCLL 已修复。
手脚架 2.0.8-beta.1  直接 重新init 新的就可以~

**Comment by ColinCLL** [comment]
谢谢
