### ISSUE TITLE
2018.05.02版本更新后，无法打开weex开发者选项窗口

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#157]
### Your questions.
-2018.05.02版本更新后，无法打开weex开发者选项窗口；
-在此之前的版本可以打开。
![image](https://user-images.githubusercontent.com/23135400/39735733-7d094a5c-52af-11e8-9465-ed681921ff27.png)

### Environment. 
- Mobile model: android
- Mobile system: 6
- Dev platform:windows/genymotion模拟器
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 希望大佬们恢复一下。
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
如果你用真机的话，试试摇一摇手机能不能把这个菜单弄出来呢

**Comment by myliuyx** [comment]
库依赖的时候，摇一摇的功能被屏蔽了， 如果你需要使用 这个的话可以用 源码依赖的分支就有了。
https://github.com/bmfe/eros-template/blob/source/README.md

**Comment by myliuyx** [comment]
已经修复~
