### ISSUE TITLE
Android Studio run 失败！！！

### ISSUE THREAD

**Issue by akFace** [bmfe/eros#158]
### Your questions.
-
Error running app: This version of Android Studio is incompatible with the Gradle Plugin used. Try disabling Instant Run (or updating either the IDE or the Gradle plugin to the latest version)
-
### Environment. 
- Mobile model: mi note3
- Mobile system: miui9 安卓7.1.1
- Dev platform: windows
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 官方weex-toolkit在命令行中weex run android成功。但是在这个eros失败
- 当前版本的android studio 与 gradle不兼容。在log中 提示我升级ide和gradle为最新版，尝试 禁用Instant Run，但仍然不能解决问题。

按照该方法不行。 [https://blog.csdn.net/qq_15807167/article/details/51984920](url)

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by akFace** [comment]
能否加个命令行build或者run

**Comment by PerseveranceZ** [comment]
@kang558 目前 android 项目存在重复引用问题和编译版本问题，已经修复，预计明天发布，到时候可以重新 init 导入项目，请稍做等待

**Comment by akFace** [comment]
@PerseveranceZ  嗯嗯，谢谢！明天再试试

**Comment by PerseveranceZ** [comment]
@kang558 

已修复 脚手架更新最新 init 即可，如果成功，辛苦关闭下 issue

**Comment by akFace** [comment]
@PerseveranceZ  成功了
