### ISSUE TITLE
安卓环境下，input使用v-model清除不了

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#159]
### Your questions.
- 我是使用了新的脚手架。在Android环境下，input使用v-model清除不了？
- 之前老的脚手架（2.7.0@beta版）可以在`sdk\src\main\java\com\taobao\weex\dom\WXDomObject:831~847` 注释就正常了 ，但是现在我找不到weex源码。请问这个问题应该怎么解决？
![image](https://user-images.githubusercontent.com/13248613/39847717-93bae134-5435-11e8-91f1-c2d3f5c55a38.png)

### Environment. 
- Mobile model: android
- Mobile system:5.1.1
- Dev platform: mac
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hopkinson** [comment]
用源码依赖解决了

**Comment by LonelyCodelang** [comment]
@hopkinson 请问是如何解决？要改android原生代码吗？

**Comment by wowtrxqn** [comment]
@hopkinson 请问是如何解决
