### ISSUE TITLE
用as打开新建项目后报错Error:Cause: org/apache/commons/lang/StringUtils

### ISSUE THREAD

**Issue by janxy** [bmfe/eros#16]
### 简略的描述你的问题。
Error:Cause: org/apache/commons/lang/StringUtils
Gradle 'WeexFrameworkWrapper' project refresh failed
### 环境信息 
> 例子：
> * 开发平台：windows7
> * node 版本：6.11.4
> * npm 版本：5.6.0
> * 调试类型：模拟器/真机
> * 调试系统版本: 
> * 开发工具及其版本 as 2.3.3

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
按照步骤新建项目后然后eros install完成
重as打开后发现该问题。

**Comment by aa453509345** [comment]
@janxy  能否给一张wxframework文件夹结构的截图 请确保所有依赖库都已经下载完成

**Comment by karynsong** [comment]
已解决

**Comment by janxy** [comment]
什么问题的，已经修复了？

**Comment by PerseveranceZ** [comment]
@janxy 不好意思关闭错误了 请确认你的环境是都有 `git bash`, 执行`.sh`文件的默认选项是不是也是`git bash`，然后在`init` 一个新项目执行 `eros install` 试一下，导入项目，如果还是不行 ，https://github.com/bmfe/eros-template/wiki 加一下这里的二维码我们有个**开发者组**，里面会帮你看下问题

**Comment by janxy** [comment]
你好，不好意思这么晚才回复，，还是AS导入项目报错，已经加入开发者微信群。目前还没有人帮我解决，，特想看看eros的demo
