### ISSUE TITLE
Eros原生日期选择组件显示问题

### ISSUE THREAD

**Issue by howie95** [bmfe/eros#160]
### Your questions.
- 当组件的selectType参数设置为single的时候，第一次点选日期会呈现正常的有底色+日期字体变为白色，但是当再次点击同一天的时候，文字又变回了未选中的颜色，即使设置了日期组件的样式也是一样
  
- 希望能有一个样式来控制选中状态的日期文字颜色，并且希望single模式下，默认给今日一个选中的状态。
  
### Environment. 
- Mobile system: iOS
- Dev platform: macOS
- eros-cli: 2.0.8-beta.1
  
### Reappearance of the problem (It's best to have a screenshot).
- 第一次选中时
![18d358f6-7b56-496c-9f56-b525f5498ce7](https://user-images.githubusercontent.com/12136338/39901689-aaef7c08-54fc-11e8-9bce-05ab9992ab3d.png)
- 再次点击
![d0be4cf0-d589-4392-ba9b-fb311e825147](https://user-images.githubusercontent.com/12136338/39901699-b25713d4-54fc-11e8-8f6f-2f981a373598.png)

**Comment by xiaohuapunk** [comment]
@howie95 单选模式重复点击一天显示的问题已修复，请跟新iOS 依赖，另外 如果想默认选择今天可以将 startData 设置为当天，可以参考一下 eros demo
