### ISSUE TITLE
5月13日新init的项目，字体图标在iOS端显示正常，在Android端不能显示

### ISSUE THREAD

**Issue by zhangning12328** [bmfe/eros#161]
### Your questions.
- 5月13日新init的项目，字体图标在iOS端显示正常，在Android端不能显示
-
### Environment. 
-Mobile model: nubia NX511J
-Mobile system: Android5.0.2
-Dev platform: macOS 10.13.4
-Node: 8.9.4
-Npm: 5.6.0

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by carrypann** [comment]
遇到了同样的问题，最近init的新版本项目出现的问题

**Comment by myliuyx** [comment]
已经修复了  更新下 库的 版本就可以。或者直接init一个新的。
