### ISSUE TITLE
scrollend ios端会一直执行

### ISSUE THREAD

**Issue by lookjoe** [bmfe/eros#162]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
@lookjoe 最好贴一下使用代码 和 最终效果

**Comment by lookjoe** [comment]
@PerseveranceZ Issues: 使用scrollend，实现选择器，android端正常读取e.contentOffset.y，ios端如下
```
<scroller show-scrollbar="false" class="price_picker" @scrollend="scrollHandler">
  <text :ref="'price' + index" class="font_text" v-for="(item, index) in priceList" :key="index">{{item && '¥ '}}{{ item }}</text>
</scroller>
```
```
scrollHandler(e) {
  let offsetY = e.contentOffset.y
  let y = Math.abs(offsetY)
  let index = Math.round(y / 60)
  this.priceIndex = index + 2
  modal.toast({
    message: e.contentOffset.y,
    duration: 0.3
  })
}
```
### android端，安卓真机，playground sdk 0.18
![f7a9cfdce2d0681be8f55ae636596041](https://user-images.githubusercontent.com/35515858/40035610-1c81a824-5835-11e8-803a-b80e06168a1b.png)

![35047ed2a2b437f8c5032428ed4d0475](https://user-images.githubusercontent.com/35515858/40035365-f85901aa-5833-11e8-9771-138b199c0c4a.png)
### ios端，iPhone8真机，playground sdk 0.18
![be80e2c1fcb8f8e12d09bdb3e8bdeeab](https://user-images.githubusercontent.com/35515858/40035721-b0b8c180-5835-11e8-9423-53944d0c775e.png)
![e192cfd9c34fdd8b0c566c18ab7b1ec0](https://user-images.githubusercontent.com/35515858/40035789-117479ec-5836-11e8-8cd3-7dac0a83c395.png)

**Comment by xiaohuapunk** [comment]
@lookjoe 有问题再提，先关闭了
