### ISSUE TITLE
建议增加获取键盘高度

### ISSUE THREAD

**Issue by sheatming** [bmfe/eros#163]
真心建议添加这个东西。

**Comment by hanliuxin5** [comment]
是出于什么样的原因，需要增加这样一个功能呢？能简述一下吗

**Comment by sheatming** [comment]
做即时通讯的页面时，如果input在最底部的时候，获取焦点的时候会将整个页面上移。
上移后list中的顶部内容会被提上去，如果只有一条消息的话就看不见了。获取键盘高度 然后减掉list的高度。可以解决这个问题。

如果你们有什么好方法可以解决这个问题，也希望告知。

android中可以设置页面为adjustresize 但设置后会吧输入框挡住，而不是将view的高度压缩。
ios中还没搞清楚怎么搞。

**Comment by hanliuxin5** [comment]
对的，`android` 中可以通过设置 `adjustresize`，ios 的话就不太清楚了。 @PerseveranceZ

**Comment by sheatming** [comment]
![qq 20180521111929](https://user-images.githubusercontent.com/17745365/40289064-d9e16578-5ce8-11e8-9f44-3d48e2685735.png)
其实应该是第三种效果。现在是第二种。

**Comment by sheatming** [comment]
应该是让整个view的高度减小，而不是直接顶上去

**Comment by xiaohuapunk** [comment]
我们做过这个需求，现有weex实现聊天页面不太行，iOS端如果想让页面不随键盘自动偏移需要修改源码，这是一个问题，再有输入框没办法做到随内容增加自动适应高度，就算扩展了键盘高度，用weex的方法控制 页面偏移也是有问题的，偏移量不准确，后期如果想扩展其他功能比如发送图片，语音等等，都是问题，所以建议直接集成第三方提供的im sdk，比如融云，当然还是需要原生开发来搞；

**Comment by sheatming** [comment]
那我在想想吧。键盘高度不好弄的话不行就放弃这块的功能了

**Comment by sheatming** [comment]
周五那天在群里也讨论过，android 通过修改属性后，计算出高度。这个逻辑倒是可行的。
![qq 20180521113755](https://user-images.githubusercontent.com/17745365/40289514-691c4c60-5ceb-11e8-8cb1-1d6b9abd3569.png)

**Comment by sheatming** [comment]
就是吧list的高度和input的容器 统一缩小和抬高。

**Comment by akFace** [comment]
@sheatming  正有此需求，能否贴完整的源码过来啊 ，还有 this.keyborderHeight 怎么得来 ？

**Comment by pidogc** [comment]
@sheatming 我也是有這需求，可否再詳細講一下，未寫過android和ios的，所以有些需要涉及到這方面的實在不知道怎麼寫
