### ISSUE TITLE
使用图片上传插件，服务端接收问题

### ISSUE THREAD

**Issue by bigfongcom** [bmfe/eros#164]
### Your questions.

-  使用 this.$image.pickAndUpload 这个方法上传图片
-  服务端(php),使用$_FILES接收到的内容是一个空数组

### Environment. 
- Mobile model: android
- Mobile system: mi 6 (android 8.0.0)
- Dev platform: windows
- Node: v8.11.1
- Npm: 5.6.0

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
可以基本确定是你们后端解析问题，因为很多人都在用并没问题，还是让你们后端好好看看吧。另外你可以使用抓包工具查看一下实际请求信息，App是否携带了 图片资源

**Comment by bigfongcom** [comment]
解决了，谢谢
