### ISSUE TITLE
echart在android中有点问题

### ISSUE THREAD

**Issue by sheatming** [bmfe/eros#165]
### Your questions.
三星里只要完全可见就不显示 稍微被遮挡一点边就隐藏了
### Environment. 
- Mobile model:老爷机 三星5500
- Mobile system: android 5.1.1
- Dev platform: windows
- Node: 8.x.x
- Npm: 5.x.x

**Comment by PerseveranceZ** [comment]
删减之后，应该是自身样式影响，关闭了。
