### ISSUE TITLE
使用eros请求数据报this.$fetch is not a function

### ISSUE THREAD

**Issue by wowtrxqn** [bmfe/eros#166]
### Your questions.
请求数据出错

### Environment. 
- Mobile model: PDA
- Mobile system: Android 7
- Dev platform: windows10
- Node: 8.9
- Npm: 6.0

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
![code](https://user-images.githubusercontent.com/24369118/40298778-cb949a52-5d16-11e8-9ed1-ffa5128a9ca6.png)
![debug](https://user-images.githubusercontent.com/24369118/40298821-ee0de6b0-5d16-11e8-8801-6f886dab43b1.png)

**Comment by PerseveranceZ** [comment]
@wowtrxqn 你这个是 eros 项目吗？用的 weex debug?

**Comment by wowtrxqn** [comment]
@PerseveranceZ   是的，用的eros，weex debug的时候发现了这个问题

**Comment by PerseveranceZ** [comment]
真机 模拟器使用没问题吧？`eros -v`贴下版本号

**Comment by wowtrxqn** [comment]
我一直用的真机调试，模拟器最开始用的，没有问题 @PerseveranceZ 
![version](https://user-images.githubusercontent.com/24369118/40300266-5cb0db14-5d1b-11e8-8a27-90638df8d298.png)

**Comment by PerseveranceZ** [comment]
你试下在顶部 import 'Config' 会不会好使 ，你这个是调试的内置包吗

**Comment by wowtrxqn** [comment]
@PerseveranceZ 我没有Config啊，我调式的是我写的页面，进页面获取后台接口数据，然后在页面渲染出来，而且我看eros官方的demo里面有个文件用到了this.$fetch，也是直接用的



![qq 20180521222541](https://user-images.githubusercontent.com/24369118/40312761-6339a490-5d46-11e8-900e-e66d0a25626d.png)

**Comment by PerseveranceZ** [comment]
`weex debug` 开启的时候无法访问我们 appboard 中拼接的公共 bundle，widget，而我们在编译阶段会自动帮你拼接，前提是页面中以 `export default {` 来写的，所以改成这个就没问题了。

**Comment by wowtrxqn** [comment]
@PerseveranceZ 我第一张截图里面就是这么写的，export default {}

**Comment by PerseveranceZ** [comment]
请求里 name 是别名 url是绝对路径
