### ISSUE TITLE
热更新后APP崩溃

### ISSUE THREAD

**Issue by wrnm** [bmfe/eros#168]
在执行增量更新后，重启APP的时候APP崩溃了日志如下：
java.lang.NullPointerException: Attempt to get length of null array
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:63)
	at com.benmu.framework.update.VersionChecker.checkZipValidate(VersionChecker.java:210)
	at com.benmu.framework.update.VersionChecker.access$400(VersionChecker.java:35)
	at com.benmu.framework.update.VersionChecker$4.onSuccess(VersionChecker.java:256)
	at me.ele.patch.BsPatch$2$1.run(BsPatch.java:134)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

配置eros.dev.js如下：
// appBoard，mediator 不建议进行修改 如果修改了 也请对应修改
module.exports = {
    'eslint': false,
    'webpackWarnings': false,
    'exports': [
        // appBoard
        'js/config/index.js',
        // mediator
        'js/mediator/index.vue',
        // home
        'js/pages/demo/index.vue',
        'js/pages/demo/index/index.vue',
        'js/pages/demo/fang/shw.vue',
        'js/pages/demo/fang/renmai.vue',
        'js/pages/demo/fang/wo.vue',
        'js/pages/demo/fenlei/index.vue',
        'js/pages/demo/faxian/index.vue',
        'js/pages/demo/wode/index.vue',
        'js/pages/demo/fang/zhuce.vue',
        'js/pages/demo/faxian/oldfaxian.vue',
        'js/pages/demo/faxian/hangyezx.vue',
        'js/pages/demo/faxian/shishidt.vue',
        'js/pages/demo/faxian/gongsidt.vue',
        'js/pages/demo/faxian/cunchu.vue',

        // 'js/pages/demo/lifecycle/index.vue',
        // 'js/pages/demo/assets/index.vue',
        // 'js/pages/demo/globalAttr/index.vue',
        // 'js/pages/demo/inputExtend/index.vue',
        // 'js/pages/demo/refresh/index.vue',
        // 'js/pages/demo/storage/index.vue',
        // 'js/pages/demo/router/index.vue',
        'js/pages/demo/router/home.vue',
        // 'js/pages/demo/event/a.vue',
        // 'js/pages/demo/event/b.vue',
        // 'js/pages/demo/notice/index.vue',
        // 'js/pages/demo/font/index.vue',
        // 'js/pages/demo/image/index.vue',
        // 'js/pages/demo/bmchart/index.vue',
        // 'js/pages/demo/bmrichtext/index.vue',
        // 'js/pages/demo/bmcalendar/index.vue',
        // 'js/pages/demo/other/bindingx.vue',
        // 'js/pages/demo/other/weexui.vue',
        // 'js/pages/demo/other/bui.vue'
    ],
    'alias': {
        'Components': 'js/components',
        'Common': 'js/common',
        'Config': 'js/config',
        'Widget': 'js/widget',
        'Pages': 'js/pages',
        'Utils': 'js/utils',
        'Fang':'js/fang',
        'Fenlei':'js/fenlei',
        'Faxian':'js/faxian',
        'Wode' : 'js/wode',
        'Index':'js/index',
    },
    'diff': {
        'pwd': 'd:/Users/yangmingzhe/Work/opensource/eros-diff-folder',
        'proxy': 'http://192.168.1.110:3001/static/eros-fnwsjb/dist/js/'
    },
    'server': {
        'path': './',
        'port': 8889

        
    },
    'mockServer': {
        'port': 52077,
        'mockDir': './dist/mock'
    },
    'socketServer': {
        'port': 8890,
        'switch': true
    }
}

配置文件eros.navtive.js
module.exports = {
    'appName': 'eros-fnwsjb',
    'appBoard': '/config/index.js',
    // android 监听全局事件homeBack 如果为true 安卓端需要自行调用router.finish方法来关闭应用
    'androidIsListenHomeBack': 'true',
    'version': {
        'android': '1.0.0',
        'iOS': '1.0.0'
    },
    'page': {
        'homePage': '/pages/demo/index.js',
        'mediatorPage': '/mediator/index.js',
        'navBarColor': '#1DA1F2',
        'navItemColor': '#ffffff'
    },
    'url': {
        // https://lev-inf.benmu-health.com/test/xxx
        'image': 'http://weex.fangniuwa.co/index.php/home/index/sjimage',
        'bundleUpdate': 'http://192.168.1.110:3001/app/check'
    },
    'zipFolder': {
        'iOS': '/ios/WeexEros/WeexEros',
        'android': '/android/WeexFrameworkWrapper/app/src/main/assets'
    },
    'getui': {
        'enabled': 'false',
        'appId': '',
        'appKey': '',
        'appSecret': ''
    },
    'umeng': {
        'enabled': 'false',
        'iOSAppKey': '',
        'androidAppKey': ''
    },
    'wechat': {
        'enabled': 'false',
        'appId': '',
        'appSecret': ''
    },
    'amap': {
        'enabled': 'true',
        'iOSAppKey': '623c0396a9b879461c971a14baa678fb',
        'androidAppKey': ''
    }
}

**Comment by PerseveranceZ** [comment]
本地数据库中是否有此差分包信息

**Comment by myliuyx** [comment]
1、打完拆分包以后对比对应的jsVersion。
2、抓包查看下请求的jsVersion。
3、可以去数据库查询下 是否有对应jsVersion 的记录
