### ISSUE TITLE
页面跳转事件有重复执行

### ISSUE THREAD

**Issue by bigfongcom** [bmfe/eros#169]
### Your questions.
 beforeBackAppear (params, options) {
     console.log('beforeBackAppear');
 },
appeared (params, options) {
       console.log('appeared');
}

使用this,$router.open(）打开新页面，上面函数分别输出两次，说明执行两次；
如果是涮新页面，则正常各自执行一次

-
### Environment. 
- Mobile model: android
- Mobile system: mi 6 (android 8.0.0)
- Dev platform: windows
- Node: v8.11.1
- Npm: 5.6.0
- eros-cli: 2.0.8-beta.1

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
是插件化版本吗 widget 版本是多少

**Comment by bigfongcom** [comment]
"eros-widget": "^1.0.2-beta.1",

**Comment by PerseveranceZ** [comment]
如果在模拟器执行两次应该是正常的，因为 weex debugger 并不能识别我们的 widget，我们又做了一次 widget 拼接，你可以看下 weex debugger 中如果是一次就正常了
