### ISSUE TITLE
关于页面回退问题

### ISSUE THREAD

**Issue by bigfongcom** [bmfe/eros#170]
### Your questions.

按教程$router.open（），设置canBack:false,跳转到新页面后，手机软键回退失效，确实是灵的（效果有效），
1.但使用$router.back（）依然能回退到上一页；
2.使用wxc-minibar组件，点击其默认回退按钮还是能回退到上一页;
-
### Environment. 
- Mobile model: android
- Mobile system: mi 6 (android 8.0.0)
- Dev platform: windows
- Node: v8.11.1
- Npm: 5.6.0
- eros-cli: 2.0.8-beta.1

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
@bigfongcom 暂时还没遇到死活不让用户返回的场景，这个仅仅只是禁止了用户手势返回和按钮而已
