### ISSUE TITLE
希望bmAxios插件暴露出response Header 供responseHandler调用

### ISSUE THREAD

**Issue by momo360** [bmfe/eros#171]
### Your questions.
-当前只能在responseHandler中取到request header。

因为我们系统登录鉴权需要使用到response header的accesstoken，所以希望eros能暴露出来response header。当前只能在responseHandler中取到request header。
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- eros未暴露该接口
- 

### Reappearance of the problem (It's best to have a screenshot).
- 图片

**Comment by PerseveranceZ** [comment]
已经可以获取，具体请看下面链接，变化对应库版本

[https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=%E8%8E%B7%E5%8F%96-responseheaders](https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=%E8%8E%B7%E5%8F%96-responseheaders)
