### ISSUE TITLE
在项目中如何去判断是否有网络/网络状态

### ISSUE THREAD

**Issue by zhengxiaodong502** [bmfe/eros#172]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
新版本已经添加 请参考文档 toolModule 使用方法
