### ISSUE TITLE
期待拓展统计插件

### ISSUE THREAD

**Issue by Sunrise1970** [bmfe/eros#173]
插件化版本之后，底层抽离了友盟统计模块，但之前上线的版本是用到友盟统计的，希望能拓展一个友盟统计或其他统计插件

**Comment by akFace** [comment]
我也很期待，正在用到。自己搞，遇到坑可多了

**Comment by shawn-tangsc** [comment]
我也在弄，包括自定义统计，巨烦

**Comment by akFace** [comment]
已经更新版本了。新版本带有友盟统计插件了，但是没有自定义事件 @shawn-tangsc
