### ISSUE TITLE
导航栏右侧不能用图标字体吗

### ISSUE THREAD

**Issue by yzzjg** [bmfe/eros#175]
### Your questions.
-this.$navigator.setRightItem({
            text: '&#xe600;',
            textColor: '#fff',
            fontSize: '32',
            fontWeight: 'normal'
        }
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
不能，只支持 图片 或 文字

**Comment by CWTgithub** [comment]
导航栏左侧返回按钮的打开方向能定义吗？
