### ISSUE TITLE
期待添加自定义键盘

### ISSUE THREAD

**Issue by hidata2013** [bmfe/eros#177]
希望可以提供一套接口或者键盘控件，供前端实现自定义键盘。

**Comment by PerseveranceZ** [comment]
@hidata2013 自定义键盘这个，大概是在什么场景使用，自定义些啥呢。。。

**Comment by hidata2013** [comment]
@PerseveranceZ 比如需要科学计算，输入金额大写时需要的中文键盘等，或者一些表情键盘。给前端一个组件，js填充布局实现。

**Comment by PerseveranceZ** [comment]
@hidata2013 这样直接用 Weex 实现就行 类似 modal
