### ISSUE TITLE
POST请求参数不识别问题

### ISSUE THREAD

**Issue by MRhexiaolin** [bmfe/eros#178]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- POST请求时，data中的参数未能识别

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
@MRhexiaolin 有抓包看请求时候 data 是否携带了么，最好给下抓包的截图

**Comment by MRhexiaolin** [comment]
POST参数是json格式，服务器想接收的是参数列表。

**Comment by xiaohuapunk** [comment]
@MRhexiaolin 跟你们服务器确认一下他们接收的request header 中 content-type 是什么类型，默认是 application/json，你可以修改次参数
