### ISSUE TITLE
安卓端加载图片失败显示的place_holder.png占位问题

### ISSUE THREAD

**Issue by ChenArno** [bmfe/eros#180]
### Your questions.
-安卓端，图片加载失败后会显示一张心形的图片。
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 希望能自由更换该图片，跟ios端一样，而不是在源码中替换
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
你说的 更自由是什么方式呢。。

**Comment by ChenArno** [comment]
跟图标一样，可以自由替换，可以将其放置在res/drawable-xhdpi下

**Comment by PerseveranceZ** [comment]
文档里面不也是自由替换吗? [https://bmfe.github.io/eros-docs/#/zh-cn/ios_image](https://bmfe.github.io/eros-docs/#/zh-cn/ios_image)

**Comment by myliuyx** [comment]
安卓这边暂时还不好做直接替换的，除非是源码依赖可以直接替换，库依赖的话暂时还不行， 不过 image 标签有 placeholder 属性可以解决这个问题！

**Comment by ChenArno** [comment]
好的，感谢，希望以后会有更好的解决方案
