### ISSUE TITLE
 安卓手机加载页面失败

### ISSUE THREAD

**Issue by zhongdom** [bmfe/eros#181]
###  安卓手机无法加载页面
- errorCode：-1001
- errMsg：degradeToH5|createInstacndefail|wx_create_instance_erros isJSFrameworkInit==false reInitCount==1
### Environment. 
- Mobile model: 魅蓝note 2
- Mobile system: Android 5.1
- Dev platform: darwin
- Node: 8.9.1
- Npm: 4.6.1

### What do you think may be caused by the analysis of the problem.
- 谷歌了一下，weex sdk的某个版本存在在android 5.0版本会出现此情况，iOS和安卓的其他版本未复现

**Comment by PerseveranceZ** [comment]
可以把遇到问题的相关机型，统一汇总给 weex 官方 issue，待官方解决后我们会同步 sdk。

**Comment by 970024540** [comment]
安卓版本太高，新建模拟器，选择安卓版本9.0，重新运行即可
