### ISSUE TITLE
this.$image.pickAndUpload 上传 gif 动画的时候，可否跳过不裁剪直接上传？

### ISSUE THREAD

**Issue by poerlang** [bmfe/eros#182]
我目前遇到的情况是，用户上传的 gif 动画，之前是动的，上传后变成了静止的
可否在 this.$image.pickAndUpload 里加个选项， 如果用户选择的是 gif 动画就跳过裁剪直接上传？

**Comment by xiaohuapunk** [comment]
上传 gif 目前还不支持，之后空了会考虑加入这功能
