### ISSUE TITLE
bui-weex控件无法使用

### ISSUE THREAD

**Issue by phoenixsky** [bmfe/eros#183]
- bui-weex组件无法使用
- 组件中嵌套子组件后,由于没有正确的引入,会在eros中找不到.比如<bui-image-slider> 引用到了<bui-image>组件 log中会报错 找不到<bui-image> 但是单独使用<bui-image>是可以的.
- 可能是因为`bui` 0.2.2之后修改了引入方式的原因

**Comment by PerseveranceZ** [comment]
@phoenixsky 你需要去给 bui 提此 issue，让他们规范支持引入，或者拷贝下来自行维护，引入方式是 webpack 所决定的，我们和 weex 都使用着类似的配置文件。

**Comment by phoenixsky** [comment]
@PerseveranceZ OK
