### ISSUE TITLE
eros  weex debug 无法开启调试

### ISSUE THREAD

**Issue by JK3412** [bmfe/eros#184]
### Your questions.
根据eros文档 所述 ，使用 命令 weex debug 抛出 bash: weex: command not found
无法打开浏览器 用真机扫描 二维码调试，
还有 这么查看 js 里面console.log() 打印出来的东西
因为无法用浏览器打开项目，所以 不知道 这么查看 console.log() 里面的东西

小白求解，，是我操作错误 还是 什么的？
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
weex debugger 安装了吗。。。

**Comment by JK3412** [comment]
你好，安装好了。有二维码，debug 能够开启， 但是不能 使用 console 啊 。。。我以前都是做的vue 能用
浏览器调试，  这个不能用浏览器打开，只能用 真机或者模拟器打开，，有点搞不来了。。
问问 ，能不能 用浏览器 打开调试， 像做vue weex 那样，可以使用命令 npm run dev 或 weex start 这样子打开.. 求指导

**Comment by JK3412** [comment]
你好。感谢你的帮助。 已经解决了 。可以 在debug 上面调试 dom 和 console 了。。。
现在终于可以开始 vue-native 开发了 。。霍霍，

**Comment by theladderofsuccess** [comment]
你好，我想请问一下你是如何解决在debug上调试dom和consle这个问题的，方便回答一下吗？

**Comment by z1900** [comment]
> 你好。感谢你的帮助。 已经解决了 。可以 在debug 上面调试 dom 和 console 了。。。
> 现在终于可以开始 vue-native 开发了 。。霍霍，
我也遇到了这个问题，请问你是怎样解决的

**Comment by z1900** [comment]
你好 我也遇到了这个问题 请问是怎么解决的 @JK3412
