### ISSUE TITLE
安卓安装成功启动后报错：文件不存在

### ISSUE THREAD

**Issue by baermowei** [bmfe/eros#185]
这是怎么回事？
路径不对吗？

![文件不存在](http://img.hb.aicdn.com/4adbd24e7f81e56f0cb41a685e10cc7a652a01d94feb7-s08wmO_fw658)

**Comment by PerseveranceZ** [comment]
eros pack android 一下

**Comment by myliuyx** [comment]
如果你直接有做过setHomePage 操作 而页面也不存在的话也可能出现这种问题， 这时候你可以卸载APP重新运行！
