### ISSUE TITLE
请问，在文档中没有找到调用手机设备控件的api

### ISSUE THREAD

**Issue by JK3412** [bmfe/eros#186]
### Your questions.
-你好，我在文档中，没有找到调用手机设备，比如摄像头，麦克风，等的api ..只有在demo中有演示，
请问在哪里可以查看到详细的 api 呢。。。望指导...........

 还有就是 问问 有没有直接的入口可以插入 第三方的 sdk呢，因为我对安卓和ios 的项目配置不是很懂。
如果有个直接入口，比如调用方法的话，那就太完美了。。
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
仔细看文档 `拓展` 模块 和 `eros-plugin`
