### ISSUE TITLE
安卓插件WeexErosFramework:1.0.4  tabBar报错

### ISSUE THREAD

**Issue by torns** [bmfe/eros#187]
### Your questions.
-
-
### Environment. 
- Mobile model: android
- Mobile system: android 5
[](url)
![wechatimg5](https://user-images.githubusercontent.com/23144884/41015618-ad1b6baa-697d-11e8-80f4-8b2b729049a6.jpeg)
安卓最新版本首页使用了tabBar原生组件报错

**Comment by myliuyx** [comment]
把 /WeexFrameworkWrapper/app/src/main/res/layout/  目录下 activity_main.xml 文件删除了。
