### ISSUE TITLE
关于原生 tabbar的建议

### ISSUE THREAD

**Issue by zqqq** [bmfe/eros#189]
2个建议
1. 支持角标，用于个人中心时，可以提示消息数量，或者购物车时，提示数量。
2. 增加一个逻辑选项，允许控制是否跳转页面。比如在购物车时，我不想在这个页面了，要允许跳转到另一个页面。

**Comment by xiaohuapunk** [comment]
@zqqq 第二个跳转需求，不太明白，你意思是提供一个方法，可以直接跳转到 任意一个 item 上是吗？

**Comment by zqqq** [comment]
不是，现在的item是使用fragment实现切换的吧，跳出的意思就是不使用fragment了，不在当前activity 相当于,$router.open重新打开一个页面，这样新的界面就不在再tabbar了，目的就是想打开新的页面，不再有tabbar，比如购物车，点击了，之后跳转到购物车时，下面的结算按钮，会和tabbar重叠。如果不是在新页面打开，就在tabbar上面了

**Comment by myliuyx** [comment]
还不是很明白，如果你想跳出直接open 到其他页面不行么？

**Comment by zqqq** [comment]
原生tabbar,有导出点击事件吗。我看demo只是通过配置文件，配置的item,当然，通过item的js文件，再次调用open，是可以打开新页面。但是那样是不是跳转了2次。。还是我理解有问题。。。我再看看文档。。

**Comment by xiaohuapunk** [comment]
tabbar 是原生的组件，加载的是你配置的js页面，你所有的逻辑要在你的js页面上完成，包括打开新的页面，跟tabbar没关系，比如 从tabbar上的第一个页面 item1 上open一个新的页面，新的页面不会有tabbar那部分视图的，不知道这么说你理解没有，你自己有没有在demo中体验一下

**Comment by zqqq** [comment]
好的，明白了。这样确实是可以的。
