### ISSUE TITLE
原生导航栏高度处理错误

### ISSUE THREAD

**Issue by zqqq** [bmfe/eros#190]
### Your questions.
-沉浸式导航时，状态栏没有计算高度，导致导航栏被状态栏挡住
![screenshot_2018-06-07-16-14-37](https://user-images.githubusercontent.com/10234272/41086993-25aed76e-6a6e-11e8-9077-9d8c519024c7.jpeg)

### Environment. 
- Mobile model: 华为
- Mobile system: android 4.4.4
- Dev platform: darwin\/windows/linux
- Node: 8.9.3
- Npm: 5.5.1

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by zqqq** [comment]
使用tabbar 当第一个item的属性为 'navShow': 'false' 时，即第一个 首页的tabpage不显示导航，后面的两个 显示导航，此时，来回切换就会出这个现象
如果三个tabitem 都显示导航，又是正常的。

**Comment by myliuyx** [comment]
你试试 demo   路由功能-> 设置APP启动首页   
就是第一个 false 后面 显示的！

**Comment by zqqq** [comment]
我这个是个tabbar，如果是直接页面是正常的。

**Comment by zqqq** [comment]
而且，在app，第一次打开，tabbar未切换过的情况下，第一次切换，也是正常的，一旦切换到，每一个item，即 'navShow': 'false' 这个item之后，再切换回第二个带nav的item时，就不正常了。

**Comment by zqqq** [comment]
操作流程是这样，打开app, tabbar 默认显示的是 第一个item属性  'navShow': 'false' ，不带nav的页面。然后切换到第地第二个item ，nav是正常的，切换到第三个，nav也是正常的，反过了，再切换到第一个item，再次切换到第二个或第三个，此时 nav 就不正常了。

**Comment by myliuyx** [comment]
你试试 demo 路由功能-> 设置APP启动首页
然后重启app 也会出现这样的情况吗？

**Comment by zqqq** [comment]
还是这样，

**Comment by PerseveranceZ** [comment]
@zqqq 我们最近修复下 先用在 tabbar 中使用自定义导航 或者在非 tabbar 中使用原生导航吧

**Comment by myliuyx** [comment]
还是这样是什么意思啊？
你试试 demo 路由功能-> 设置APP启动首页  
也会这样吗？ 
我就想让你试试我们demo 里面的有有没这样的问题。
确认下 然后我好定位是哪儿的问题？
毕竟直接给一个这样的错误 我很难定位到具体是哪里的问题啊 兄弟？

还有能提供下 具体的手机型号么？ 您是否也可以换个手机试试 是否有同样的问题呢？

**Comment by zqqq** [comment]
好的，

**Comment by myliuyx** [comment]
Android 机型适配相关， 目前仅发现4.4 手机可能会出现这种情况。
对Android 4.4 机型增加判断出来。
