### ISSUE TITLE
ios xcode 导入项目 问题 

### ISSUE THREAD

**Issue by JK3412** [bmfe/eros#191]
### Your questions.
-用xcode 导入项目， frameworks文件夹里面的 libPods-WeexEros.a  文件是红色，
Pods里面的 frameworks/IOS/ *.framework 也是红色的 -- 运行就报错，-- 求 指导。。。。

xcode 9.4
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
xcode 不用导入项目，严格 按文档来

**Comment by JK3412** [comment]
你好，感谢你的指导， 现在 demo 能在xcode 上运行了。。  今天中午在 pod  update 的时候 突然拉取了一个 build 文件，然后 导入 就把错误排除了。。 但是运行的时候 还是有很多 黄色的感叹号警告。。不知道是不是正常的？

**Comment by PerseveranceZ** [comment]
没关系 是正常的 @bbac3412
