### ISSUE TITLE
导入模板项目报错，点击小锤子后依旧报错：Unable to find a matching configuration of project :wxframework: None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by LXR314** [bmfe/eros#192]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
同 #193
