### ISSUE TITLE
下载Eros demo，安卓导入后报错，点击小锤子后，依旧报错。：Unable to find a matching configuration of project :wxframework: None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by LXR314** [bmfe/eros#193]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by hanliuxin5** [comment]
下载eros demo？
你试试直接打开 eros 初始化出来的项目呢。

**Comment by myliuyx** [comment]
提供下 脚手架版本 环境版本吧。
就一句这样的错误 目前只能知道一个  库找不到，并不能提供什么有用的帮助！

**Comment by tangshihao1994** [comment]
![image](https://user-images.githubusercontent.com/42458153/47488711-7fb3d580-d877-11e8-86e3-d8ca804e865b.png)
我也是这个问题，ios没问题，as就跑这个错
