### ISSUE TITLE
新模板ios运行报错

### ISSUE THREAD

**Issue by hukaibaihu** [bmfe/eros#194]
更新了最新的template之后，运行install.ios.sh，打开xcode运行报错：
![image](https://user-images.githubusercontent.com/9410341/41161678-45c788fe-6b66-11e8-9167-f9ae96a273fb.png)

**Comment by shawn-tangsc** [comment]
你的pod版本是多少？可以试试看1.3.1的版本

**Comment by hukaibaihu** [comment]
1.3.1编译成功，之前是1.5.3。
Thank you！
