### ISSUE TITLE
Android JSpath路径携带参数出错

### ISSUE THREAD

**Issue by zhangjanp** [bmfe/eros#197]
### Your questions.
- 
### Environment. 
- Mobile model: Android
- Mobile system: 
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

[https://jsplayground.taobao.org/bundle/88cb789b-5983-4c35-8c11-39e16bd89fa0/vuebundle.js?param=test](https://jsplayground.taobao.org/bundle/88cb789b-5983-4c35-8c11-39e16bd89fa0/vuebundle.js?param=test)

**Comment by PerseveranceZ** [comment]
@Z-Janp 详细描述下 是 url 上面加参数出什么错

**Comment by zhangjanp** [comment]
@PerseveranceZ 携带什么参数都会报错。
例如 [https://jsplayground.taobao.org/bundle/88cb789b-5983-4c35-8c11-39e16bd89fa0/vuebundle.js?param=test](https://jsplayground.taobao.org/bundle/88cb789b-5983-4c35-8c11-39e16bd89fa0/vuebundle.js?param=test)
