### ISSUE TITLE
关于原生TabBar的建议

### ISSUE THREAD

**Issue by zhangjanp** [bmfe/eros#198]
### Your questions.
- 希望可以提供打开指定item的接口

#### 场景
- 从第二个item页的某个元素触发跳转到第一个item页

**Comment by zqqq** [comment]
嗯，确实需要这个，
还有支持  角标

**Comment by xiaohuapunk** [comment]
建议已列入开发计划，预计下个版本会上，感谢反馈

**Comment by xiaohuapunk** [comment]
新版本以支持 使用方法请看 https://bmfe.github.io/eros-docs/#/zh-cn/eros_sdk_module?id=bmtabbar
