### ISSUE TITLE
引入SDK时初始化操作应该在哪里做

### ISSUE THREAD

**Issue by zhongdom** [bmfe/eros#199]
在引入支付宝和微信等SDK时，需要用各种key进行初始化操作。iOS的话一般时放在`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` 中。所以在封装插件时这些操作应该在原生做还是应该暴露给js端做？如果暴露给js端做，在什么时候进行调用？放在`appboard`可不可行？

**Comment by myliuyx** [comment]
https://bmfe.github.io/eros-docs/#/zh-cn/plugin_wx_pay  这里有关于微信支付相关的文档。
支付宝支付 暂时还未完成，有其他小伙伴正在开发中！

**Comment by PerseveranceZ** [comment]
@zhongdom 不要放入 appboard 那样会在没打开一个页面执行一次，可以放在中介者，或者首页

**Comment by xiaohuapunk** [comment]
插件化后初始化的方法都放到了 Module 中，详情请阅读文档 https://bmfe.github.io/eros-docs/#/zh-cn/plugin_wx_pay ，实现方式可以参考源码实现
