### ISSUE TITLE
订阅事件中 iOS 路由无法跳转

### ISSUE THREAD

**Issue by akFace** [bmfe/eros#201]
### Your questions.
-订阅事件中 iOS 路由无法跳转，安卓可以。
-估计是ios bug
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 11
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 暂无

### Reappearance of the problem (It's best to have a screenshot).
- 
![881523f85930bdfd7b0f7615516c0d02](https://user-images.githubusercontent.com/22288837/41397672-8df2b966-6fe7-11e8-9c6d-571c86646a7b.jpg)

**Comment by xiaohuapunk** [comment]
问题已定位到： mediator页面中调用 router 会有问题，下个版本会修复。感谢反馈

**Comment by xiaohuapunk** [comment]
已优化 升级iOS基础库版本为 1.2.6 以上
