### ISSUE TITLE
Android 中的 onActivityResult 没被触发

### ISSUE THREAD

**Issue by lyloou** [bmfe/eros#202]
### Your questions.
- Android 中的 onActivityResult 没被触发

### Environment. 
- Mobile model: android
- Mobile system: 5.1
- Dev platform: darwin\/windows/linux

### 场景
在调用 `mTencent.shareToQQ(context, params, iUiListener);` 时，
无法在 `onActivityResult`中拿到回调。

### What do you think may be caused by the analysis of the problem.
cordova中有`cordova.setActivityResultCallback(this);`来辅助触发onActivityResult回调。
```
cordova.setActivityResultCallback(this);
mTencent.shareToQzone(mContext, params, iUiListener);
```
设置上面的方式后，可以触发onActivityResult：
```
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        if (resultCode == Constants.ACTIVITY_OK) {
            if (requestCode == Constants.REQUEST_QQ_SHARE) {
                Tencent.onActivityResultData(requestCode, resultCode, intent, iUiListener);
            }
            if (requestCode == Constants.REQUEST_QZONE_SHARE) {
                Tencent.onActivityResultData(requestCode, resultCode, intent, iUiListener);
            }
        }

        super.onActivityResult(requestCode, resultCode, intent);
    }
```

另一个问题：WXModule中可以提供`onNewIntent`吗

谢谢！

**Comment by myliuyx** [comment]
一般没有触发  onActivityResult ，只能是 没有调用 startActivityForResult 或者是 填写的 requestCode 不一样导致的。

**Comment by lyloou** [comment]
@myliuyx 
在继承`WXModule`的类中，针对类似QQ分享，微博分享这些需要回调的情况是没法接管了呢（不能在这里调用`startActivityForResult`）。

不会是 resultCode 的问题，下面代码第一行也没调用：
```
@Override
public void onActivityResult(int requestCode, int resultCode, Intent intent) {
    System.out.println("----------++++++++++++++----------");
    Tencent.onActivityResultData(requestCode, resultCode, intent, iUiListener);

    super.onActivityResult(requestCode, resultCode, intent);
}
```

**Comment by lyloou** [comment]
最后我通过在继承WXModule的类的方法中，启动一个自定义的透明背景的Activity解决了，在自定义的activity中就可以随便重写方法了。
```
    @JSMethod(uiThread = false)
    public void shareToQQ(String data, final JSCallback callback) {
        ShareQQActivity.newInstance(mWXSDKInstance.getContext(), data, callback);
    }
```
