### ISSUE TITLE
运行eros-demo项目Android端，出现gradle 3.0.0和android-maven-gradle-plugin:1.5无法成功下载的问题。

### ISSUE THREAD

**Issue by dstweihao** [bmfe/eros#205]
- 运行eros-demo项目Android端，出现gradle 3.0.0和android-maven-gradle-plugin:1.5无法成功下载的问题。
- 明明在eros-demo项目中的build.gradle文件中两个repositories{}中已经有google()了，不知道为什么还会报错。
![](https://user-images.githubusercontent.com/22561017/41636293-23a4a1d0-7480-11e8-8484-fd387753761d.png)

![](https://user-images.githubusercontent.com/22561017/41636275-0c33b6ee-7480-11e8-90a5-57c8ee67c26f.png)

**Comment by dstweihao** [comment]
现在发现是Android Studio 升级到3.1.3的原因。

**Comment by myliuyx** [comment]
翻墙下试试!
你也可以 下载 3.0.1 版本的Android Studio！

**Comment by dstweihao** [comment]
已解决，公司沙盒系统限制的原因。
