### ISSUE TITLE
errcode->-1001msg

### ISSUE THREAD

**Issue by gqdtl** [bmfe/eros#206]
### Your questions.
-errCode->-1001msg
-
### Environment. 
- Mobile model: 模拟器
- Mobile system:android 8
- Dev platform: darwin\/windows/linux
- Node: 9.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by gqdtl** [comment]
![byjbu25m76ue7855 g2 fm](https://user-images.githubusercontent.com/14305510/41709811-bb65b152-7576-11e8-841f-7a8e21379d1b.png)

**Comment by myliuyx** [comment]
使用真机测试下看看~

**Comment by gqdtl** [comment]
真机可以
