### ISSUE TITLE
热刷新显示未连接

### ISSUE THREAD

**Issue by gqdtl** [bmfe/eros#208]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by gqdtl** [comment]
![screenshot_20180622-151342](https://user-images.githubusercontent.com/14305510/41762962-21711f50-762f-11e8-9259-43a5f39311db.jpg)

同一个局域网

**Comment by PerseveranceZ** [comment]
模拟器还算是真机，还有issue 提的时候记得改下机型，不看截图还以为是 ios 问题。

手机浏览器看能不能上网，能不能访问你的 ip 加 端口
