### ISSUE TITLE
希望原生tabbar增加相应的api

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#209]
### Your questions.
-目前的原生tabbar没有办法控制和监听
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 希望能够监听tabbar切换，能够通过js切换tabbar
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
bmTabbar module 了解一下

发自我的 iPhone

**Comment by morelearn1990** [comment]
文档上只有红点显示与否的控制和打开某个页面的 api ，如何监听 tabbar 上某个页面显示的呢？当这个页面显示的时候，可能要去刷一波数据什么的。

**Comment by sgssxf** [comment]
同样希望js控制tabbar，因为不同用户登录进去tabbar项目内容不一定相同，设置在eros.native.js里面没办法更改啊

**Comment by xiaohuapunk** [comment]
在切换tabbar的时候会触发生命周期，安卓问题已修复，详情请看 https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=_20180704
