### ISSUE TITLE
原生Tabbar切换没有走生命周期

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#210]
### Your questions.
-安卓原生tabbar内的页面，在切换时没有走生命周期。
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 目前在创建时会走vue的created周期，以及从非tabbar页面返回时，会走eros的beforeBackAppear和backAppeared周期。其余情况都没有走生命周期。
- 希望切换时能够走生命周期，或者提供监听tabbar切换的api，以便对相应页面做更新。

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
近期会加上tab 切换的时候 走 viewWillAppear 生命周期
