### ISSUE TITLE
现有的vue项目，通过eros来转成app，需要那些步骤？

### ISSUE THREAD

**Issue by zhongku** [bmfe/eros#212]
现有的vue项目，通过eros来转成app，需要那些步骤？有指导教程吗？非常感谢

**Comment by morelearn1990** [comment]
首先是标签上要兼容,weex上的标签是自定义组件,标签数量\类型\属性和html上传统标签不一样的.其次是CSS属性,weex上CSS属性只支持很少的一部分,这部分需要做很大的兼容处理才行.再有weex上和浏览器的环境不一样,比如api请求是eros封装的,和浏览器可能有点不一样,需要采坑等.

其实最好的办法是重新写吧,这样还轻松一点.

以上是我当前实践得到的结论,可能有误的地方,仅作参看

**Comment by zhongku** [comment]
非常感谢，如此耐心的回答。weex上CSS属性只支持很少的一部分?标准的应该支持吧？

**Comment by PerseveranceZ** [comment]
@morelearn1990 已经回答的很详细了
建议你先熟悉 weex 文档，尤其是 web 端 app 端差异性 还有 vue 差异性的部分，在这过程中思考迁移成本
@zhongku

**Comment by zhongku** [comment]
非常感谢，其实我们现在是从头开始写的。

**Comment by xiaohuapunk** [comment]
有问题可以在群里和其他开发者讨论，isuess 先关闭了
