### ISSUE TITLE
不支持显示bash64位的图片吗？

### ISSUE THREAD

**Issue by akFace** [bmfe/eros#213]
### Your questions.
-我从官方示例复制代码到APP上。显示不出来
-weex 官方代码 [链接](http://dotwe.org/vue/8cc89b9bd036d06ebf2d5f452b3bcc51)

http://dotwe.org/vue/8cc89b9bd036d06ebf2d5f452b3bcc51

### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 未知

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
下个版本修复

**Comment by xiaohuapunk** [comment]
以支持，详情请看 https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=_20180704

**Comment by akFace** [comment]
@xiaohuapunk  牛皮啊，支持大佬
