### ISSUE TITLE
打包后生成apk包，拦截器打开下找不到xxx.js

### ISSUE THREAD

**Issue by wowtrxqn** [bmfe/eros#214]
### Your questions. 打包后生成apk包，找不到xxx.js
-
-
### Environment. 
- Mobile model: Android
- Mobile system: 5.1
- Dev platform: win 10
- Node: 8.9.1
- Npm: 6.0.0

### What do you think may be caused by the analysis of the problem.
-  1. 文件不存在/storage.emulated/0/......./bundle/pages/Main.js
-  2. 既然bundle里都有了这些文件，为什报这个错，名称，大小写都检查过，各种重装app，build / pack

-  3. 用hotRefresh模式一切正常，然后切换Interceptor模式就1的错误

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
更改或者新增页面 需要 eros pack 。
