### ISSUE TITLE
tabBar Android 双击debug按钮刷新闪退以及borderColor作用整个tabbar的背景色

### ISSUE THREAD

**Issue by phoenixsky** [bmfe/eros#216]
### Your questions.
- tabBar Android 双击debug按钮刷新闪退
- borderColor作用整个tabbar的背景色
### Environment. 
- Mobile model: Android
- Mobile system: All
- Dev platform: darwin
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
使用最新版本的eros 问题已经修复了。

**Comment by phoenixsky** [comment]
之前测试版本问题为1.0.4. 未修复
1.0.5 gradle还获取不到
 jitpack里1.0.5版本编译失败
@myliuyx
