### ISSUE TITLE
Android无法下载 classpath 'com.android.tools.build:gradle:3.0.0'

### ISSUE THREAD

**Issue by jypblue** [bmfe/eros#218]
### Your questions.
- Android导入demo项目也是不行，3.0.0那个包下不下来每种官方脚手架项目运行都这样
### Environment. 
- Mobile model: iphone8
- Mobile system: iOS 11.4
- Dev platform: mac
- Node: 9.11.1
- Npm: 5.6.0

**Comment by PerseveranceZ** [comment]
贴一下报错呗 @jypblue

**Comment by myliuyx** [comment]
Android Studio   需要一个gradle:3.0.0 插件，一般第一次打开项目会自动的去下载 这个插件，有时候可能会很慢或者需要翻墙。

**Comment by jypblue** [comment]
我后面弄好了，但是感觉环境真心要严格如文档那样，node必须9.xx以及android studio 3.0.x版本才能正常运行，其它版本就完全不行。
