### ISSUE TITLE
希望增加H5回调weex方法

### ISSUE THREAD

**Issue by sevenceo** [bmfe/eros#219]
### Your questions.
用$router.toWebView打开H5,然后H5回调传参，参考bmnative的closePage，写了个fireEvent，发现fireGlobalEventCallback这个执行后，监听不到。最后遍历所有WXSDKInstance，然后触发事件的才有效果。
我觉得这个H5回传数据给weex页面，还是比较常用的，有些weex实现不了的功能，可以用h5解决，希望weex可以集成这个功能。
   @JavascriptInterface
        public void fireEvent(String eventId, String string) {
            Map<String, Object> params = new HashMap<>();
            params.put(eventId, string);
            //GlobalEvent是实例级的，不是应用级的。
            // 只有mWXSDKInstance这个实例能收到。但是可以遍历所有实例，都发送event
            List<WXSDKInstance> instances = WXSDKManager.getInstance().getWXRenderManager().getAllInstances();
            for (WXSDKInstance instance : instances) {
                instance.fireGlobalEventCallback("webEvent", params);
            }
            //mWXSDKInstance.fireGlobalEventCallback("webEvent", params);
            RouterTracker.popActivity();
        }

-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
已列入新需求

**Comment by xiaohuapunk** [comment]
以支持，详情请看 https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=_20180704
