### ISSUE TITLE
希望$router.toWebView支持本地路径

### ISSUE THREAD

**Issue by sevenceo** [bmfe/eros#221]
### Your questions.
类似如下：
  this.$router.toWebView({
                    url:'/assets/sign.html', 
                    title:'签字',
                    navShow:false
  });
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
下个版本会支持

**Comment by xiaohuapunk** [comment]
最新版本已支持，详情请看 https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=_20180704
