### ISSUE TITLE
源码分支新init项目在oppo  R15上一运行就crash

### ISSUE THREAD

**Issue by momo360** [bmfe/eros#222]
### Your questions.
-源码分支新init项目，尚未修改任何代码，在oppo  R15上一运行就crash
-
### Environment. 
- Mobile model: oppo  R15
- Mobile system:Android  8.1.0
- Dev platform: darwin\/windows/linux
- Node: 8.9.3
- Npm: 5.6.0

### What do you think may be caused by the analysis of the problem.
- 兼容性
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
![222](https://user-images.githubusercontent.com/8174765/42151104-6fbd0a84-7e0e-11e8-8132-7d27f595d1be.png)

**Comment by xiaohuapunk** [comment]
现在直接 eros init 即可，不需要clone 源码了，如果直接 eros init 的有问题请回复一下

**Comment by momo360** [comment]
不用直接init的 没有源码啊  我想要看到源码的 
是你们源码分支不用了吗？


发自我的 iPhone

**Comment by shawn-tangsc** [comment]
直接clone，源码依赖也一样的吧

**Comment by aa453509345** [comment]
init最新的eros项目 查看下还是否有这个问题
