### ISSUE TITLE
IOS个推问题

### ISSUE THREAD

**Issue by allen516** [bmfe/eros#224]
IOS 个推，这种写法好像不支持  
  var bmPush = weex.requireModule('bmPush');
    bmPush.initPush({
        appId: '',                
        appKey: '',
        appSecret: ''
    })
提示 initPush 未定义。我需要获取ios的clid，请问如何解决？

ios 9版本

**Comment by xiaohuapunk** [comment]
把 初始化方法放到 vue 生命周期中

**Comment by allen516** [comment]
放在created  里面也报错，

提示initPush    undefined ,怎么处理？

**Comment by xiaohuapunk** [comment]
看看是否用的 最新版本 个推插件，如果有问题就在群里问问，还是你使用的问题，别人使用都没问题
