### ISSUE TITLE
Android 原生tabbar页面,在created通过$navigator.setRightItem(),左侧也会有影响

### ISSUE THREAD

**Issue by phoenixsky** [bmfe/eros#225]
### Your questions.
- Android 原生tabbar页面,在created通过$navigator.setRightItem( '用了一个image' ),如果不设置leftItem(),多次切换tab后,左侧出现同右侧一样的图标

**Comment by xiaohuapunk** [comment]
这个100%必现吗？机型 系统版本提供一下
