### ISSUE TITLE
IOS里pod update 支付宝插件出现错误

### ISSUE THREAD

**Issue by hopkinson** [bmfe/eros#226]
### Your questions.
-  
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 11
- Dev platform: mac
- Node: v8.9.2
- Npm: 4.6.1
- Ruby: 2.5
- eros verison : 2.0.8 beta 3

![image](https://user-images.githubusercontent.com/13248613/42427348-b457650c-8360-11e8-8eb9-c835712837f9.png)

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
去支付宝插件提isuess，不是我们维护的

**Comment by hopkinson** [comment]
打扰了
