### ISSUE TITLE
动态修改image 的宽或者高图片会变形

### ISSUE THREAD

**Issue by hminghe** [bmfe/eros#227]
### Your questions.
当动态修改 image 的宽或者高图片会变形。
-
### Environment. 
- Mobile model: android
- Mobile system: android5/6 (只测试了这两个版本的系统)
- Dev platform: windows
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
![image](https://user-images.githubusercontent.com/1744129/42433059-39e28c00-8380-11e8-8b9f-2559a59fdc3a.png)

**Comment by PerseveranceZ** [comment]
跟 eros 没关系，好好看 weex 文档
https://weex.apache.org/cn/references/components/image.html

**Comment by xiaohuapunk** [comment]
下个版本会修复
