### ISSUE TITLE
希望能够增加获取当前原生tabbar页面的api

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#228]
### Your questions.
-在app从后台切换回前台以及从普通页面跳转到tabbar页面时，如果当前页面是tabbar内的页面，会触发所有已经访问过的tabbar页面的beforeBackAppear周期，希望能够提供api获取当前是什么页面。
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 感觉是访问过的tabbar页面都会存储在一个页面栈里，当tabbar显示和隐藏切换后，这个页面栈里的页面都会被重新激活。
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
这个是个bug，应该只触发当前页面，weex有方法获取当前页面，这个应该可以吧，还有tabbar每次切换的时候都会触发页面的生命周期，你可以标记当前你在哪个页面这样也ok吧

**Comment by Tilang** [comment]
@xiaohuapunk  weex好像没有办法获取到tabbar里的当前页面。标记这个办法不得行，因为app切换前后台的时候，tabbar内的页面不会走appActive和appDeactive周期，只能通过disappeared周期监听离开页面，就没办法分辨出是前后台切换还是正常的切换tabbar页面了。

**Comment by xiaohuapunk** [comment]
恩，攒一波tabbar的需求，之后一起上
