### ISSUE TITLE
mediator里面不能监听globalevent

### ISSUE THREAD

**Issue by theblueski** [bmfe/eros#229]
### Your questions.
-app需要做来电监听，所以希望在mediator里面监听事件，然后跳到接听电话页面，但是在mediator中设置globalevent监听后，没有触发任何操作
-
### Environment. 
- Mobile model: 小米手机
- Mobile system: miui9.6
- Dev platform: darwin
- Node: 8.11.3
- Npm: 5.6.0

### What do you think may be caused by the analysis of the problem.
- 可能在初始化mediator的时候globalevent没有初始化好？
- 

### Reappearance of the problem (It's best to have a screenshot).
- 

![20180711160909](https://user-images.githubusercontent.com/22572433/42558846-07e95304-8525-11e8-992a-efdb0a5e1643.png)

**Comment by xiaohuapunk** [comment]
那你实现了对于的原生代码吗？

**Comment by PerseveranceZ** [comment]
时间过长，先关闭，有问题再提出。
