### ISSUE TITLE
希望优化一下列表组件的内存回收

### ISSUE THREAD

**Issue by locationisme** [bmfe/eros#231]
### Your questions.
-在做图文展示列表的时候，下拉列表加载到几百条数据的时候就会内存溢出
-
### Environment. 
- Mobile model: Android
- Mobile system: Android 5.1
- Mobile RAM: 2048MB
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by aa453509345** [comment]
图片资源都成功加载了吗  能否提供下测试代码

**Comment by locationisme** [comment]
index.vue :
> <template>
    <div>
        <waterfall column-count="2" column-gap="6" @loadmore="onloading" loadmoreoffset="10">
            <cell v-for="(value,index) in goodsList" :key="index">
                <block-3 :goods="value"></block-3>
            </cell>
        </waterfall>
    </div>
</template>

> <script>
import block3 from './block3';

export default {
    components: {
        'block-3': block3,
    },
    data () {
        return {
            goodsList: [],
            page: 1
        };
    },
    created () {
        this.getGoods();
    },
    methods: {
        onloading() {
            this.$notice.loading.show();
            this.showLoading = 'show';
            setTimeout(() => {
                this.$notice.loading.hide();
                this.getGoods(this.page);
                this.showLoading = 'hide'
            }, 600)
        },
        getGoods(p) {
            const self = this;
            if(p){
                this.$fetch({
                    method: 'POST',
                    url: 'http://a.ruoshi168.cn/app/index.php?i=2&c=entry&op=list&do=index_ajax&m=bsht_tbk',
                    data: {
                        'shopid': 0,
                        'limit': p,
                        'diyminifee': 999999,
                    },
                    header: {
                        'Content-Type': 'application/x-www-form-urlencoded'
                    }
                }).then(resData => {
                    self.page += 1;
                    self.goodsList.push(...resData.content);
                }, error => {})
            }else{
                this.$fetch({
                    method: 'POST',
                    url: 'http://a.ruoshi168.cn/app/index.php?i=2&c=entry&op=list&do=index_ajax&m=bsht_tbk',
                    data: {
                        'shopid': 0,
                        'limit': 1,
                        'diyminifee': 999999,
                    },
                    header: {
                        'Content-Type': 'application/x-www-form-urlencoded'
                    }
                }).then(resData => {
                    self.page = 2;
                    self.goodsList = resData.content
                }, error => {})
            }
        },
    }
}
</script>

block3.vue 
> <template>
    <div class="wrapper">
        <div class="i-gd" >
            <div class="gd-bg">
                <image class="gd-img" resize="cover" :src="goods.pic+'_300x300.jpg'"></image>
            </div>
            <text class="gd-tlt">{{goods.title}}</text>
        </div>
    </div>
</template>

> <script>
export default {
    props: ["goods"],
}
</script>

<style scoped>
.wrapper {
    background-color: #fff;
    padding-bottom: 10px;
    padding-top: 26px;
    width: 750px;
}
.i-gd {
    width: 350px;
    height: 510px;
    margin-bottom: 20px;
}
.gd-bg {
    background-color: #f4f4f4;
}
.gd-img {
    width: 350px;
    height: 350px;
}
.gd-tlt {
    font-size: 28px;
    color: #333;
    width: 350px;
    margin-top: 15px;
    overflow: hidden;
    lines: 1;
    white-space: nowrap;
    text-overflow: ellipsis;
}
</style>

**Comment by hetian9288** [comment]
使用waterfall 内存问题很明显

**Comment by aa453509345** [comment]
7月26日的版本针对这一问题做了一些优化
