### ISSUE TITLE
mediator.js中使用router跳转页面在iOS上无效

### ISSUE THREAD

**Issue by uncleLian** [bmfe/eros#232]
### Environment. 
- Mobile model: IPhone8s 模拟器
- Dev platform: macOS 10.13.5 
- Node: 8.4.0
- Npm: 5.6.0

![image](https://user-images.githubusercontent.com/25951301/42669795-f29240a4-8689-11e8-825e-4f37fa47a349.png)
![image](https://user-images.githubusercontent.com/25951301/42669822-1c09812c-868a-11e8-994c-6204b81fb1bf.png)

**Comment by xiaohuapunk** [comment]
debug了一下确实有点问题，下个版本修复

**Comment by xiaohuapunk** [comment]
已修复，请更新基础库到最新版本
