### ISSUE TITLE
本地存储storage异步获取时如果值不存在无返回

### ISSUE THREAD

**Issue by sgssxf** [bmfe/eros#233]
### Your questions.
执行以下代码
```
this.$storage.get('noSet').then(Response=> {
    if (Response) {
        console.log('true')
    } else {
       console.log('false')
    }
    console.log(Response)
})
```
时在jsLog中只有以下输出
“jsLog: Unhandled promise rejection false”
无法判断该值是否已经
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
希望在异步获取本地存储时如果值不存在返回一个null或者false能做判断，比如要判断一个值如果不存在就存储进去，存在则执行其它任务……

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
返回的有。
errorMsg
status  0：成功  9： 失败
data   数据

**Comment by pidogc** [comment]
這個沒有東西返回啊！這樣子在app初始化時怎麼判斷storage裡面有沒有該屬性呢
![image](https://user-images.githubusercontent.com/42857270/58857388-fc066680-8659-11e9-9de1-54b25cf18334.png)

**Comment by pidogc** [comment]
使用async await 無法得到errMessage
