### ISSUE TITLE
iOS 12 ,Xcode10 beta3 编译提示 ld: library not found for -lstdc++.6.0.9

### ISSUE THREAD

**Issue by lilien1010** [bmfe/eros#235]
根据我找到的资料 说是 iOS12 不支持  libstdc++的库了，

xcode 在模拟器编译就提示下面的问题
```
ld: library not found for -lstdc++.6.0.9
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

如果是真机环境就不会

https://twitter.com/jeremyhu/status/1003882060556062720

**Comment by xiaohuapunk** [comment]
之后升级适配的时候会关注这个问题

**Comment by xiaohuapunk** [comment]
使用xcode10开发，请参考这篇文章操作就可以了 https://www.jianshu.com/p/6d94278d62b3
