### ISSUE TITLE
如何禁止tabbar滑动切换页面

### ISSUE THREAD

**Issue by Vongolatt** [bmfe/eros#236]
如题

**Comment by sgssxf** [comment]
@Vongolatt 我用的原生的tabBar，默认好像就不可以滑动切换页面啊

**Comment by shekang** [comment]
https://bmfe.github.io/eros-docs/#/zh-cn/eros_widget?id=router%ef%bc%88%e8%b7%af%e7%94%b1%ef%bc%89

`gesBack:目标页面是否开启手势返回。默认开启仅支持iOS；`

**Comment by Ethan-zjc** [comment]
问的应该是android，在android上默认原生tabBar可以左右滑动切换，ios不可以，同求怎么禁用android上左右滑动切换tabBar

**Comment by Vongolatt** [comment]
@zjc150  对, 就是主页面底部tabbar滑动切换效果.在eros.native.js中配置的tabbar官方文档没有禁用滑动的字段

**Comment by PerseveranceZ** [comment]
这个需要我们优化下

**Comment by Vongolatt** [comment]
@PerseveranceZ 好的, 谢谢

**Comment by missy0u** [comment]
找到wxframework\eros-framework\src\main\java\com\benmu\framework\view\TableView.java文件

103行下面添加 

`viewpager.setNoScroll(true);`

![image](https://user-images.githubusercontent.com/3926664/44896613-5d945000-ad2b-11e8-9d17-a55543a4dad3.png)

**Comment by Vongolatt** [comment]
@missy0u 谢谢
