### ISSUE TITLE
关于bmchart的一个问题

### ISSUE THREAD

**Issue by wtowto7207** [bmfe/eros#238]
### Question title
- 修改bm-chart.html并添加对应百度地图jssdk及bmap.js后，安卓端可正常展示热力图而ios端无效并报错的问题

### Environment. 
- Mobile model: iphone6p
- Mobile system: iOS 11.4
- Dev platform: darwin
- Node: 8.10.0
- Npm: 4.6.1

### What do you think may be caused by the analysis of the problem.
- 个人认为是BMChartComponent.m中wkwebview未能正确调用jssdk及bmap.js导致，但由于个人知识所限，不知该如何修改。
- 

### Reappearance of the problem (It's best to have a screenshot).
- xcode的报错信息
![image](https://user-images.githubusercontent.com/5389459/42803728-6e7f64a6-89d9-11e8-89ef-3d4dda2cf63b.png)
- bm-chart.html修改后代码
![image](https://user-images.githubusercontent.com/5389459/42803953-1b9a402a-89da-11e8-86bb-42bf73e57420.png)

**Comment by xiaohuapunk** [comment]
请提供完整的测试demo，可以在群里联系我

**Comment by wtowto7207** [comment]
好的
