### ISSUE TITLE
希望热更新时能自定义更新弹出框内容

### ISSUE THREAD

**Issue by shekang** [bmfe/eros#240]
### Your questions.
- 目前android端热更新时是没有任何弹出框提示的直接就强制更新了
- 而IOS端是有弹出框的提示,默认也是强制更新

### Reappearance of the problem (It's best to have a screenshot).
![qq 20180718111352](https://user-images.githubusercontent.com/13003498/42857273-c07ac65e-8a7b-11e8-8d72-3a7ed5944ba8.png)

希望能够完善两端的更新提示 比如说: 可以前端自定义更新提示 描述更新了哪些内容等。。

**Comment by PerseveranceZ** [comment]
@shekang 查看更新 可以自定义
