### ISSUE TITLE
提一个文档上的建议

### ISSUE THREAD

**Issue by HZZformGD** [bmfe/eros#242]
darwin 开发 iOS:的时候 
安装 CocoaPods：$ sudo gem install cocoapods -v 1.4.0
这一部 我建议 去掉 -v 1.4.0（前提是 ruby版本 比较新）
我发现。在ruby 比较新的情况下， 装1.4.0  导致pod update 出错 但是我去掉 -v 1.4.0 后装了就成功了，
所以我在想 是不是这个原因导致的， 不过我也没仔细考究过， 希望团队大大们 可以去试试

**Comment by xiaohuapunk** [comment]
pod 1.4.0 版本比较稳定，直接安装最新版本一些三方库如果没及时失败会出问题，这跟 ruby 版本应该没关系，因为没人反馈过这个问题

**Comment by HZZformGD** [comment]
@xiaohuapunk   好的。   可能昨晚碰巧被我解决了。    那关闭了这个issue 吧 多谢啦
