### ISSUE TITLE
2018.07.18版本更新后在Android下bmStorage读取的字符串会多个引号

### ISSUE THREAD

**Issue by Zmor** [bmfe/eros#243]
### Your questions.

2018.07.18版本更新后在Android下bmStorage读取的字符串会多个""，而之前的版本没有，
（IOS还没测试）
代码实例如下：

`
// 2018.07.18 之前版本
const storage = weex.requireModule('bmStorage');
const lang = storage.getDataSync('lang');
const lang_index_data = lang.data ? lang.data : 0;
const lang_index = lang_index_data;

// 2018.07.18 版本需要去除双引号
const storage = weex.requireModule('bmStorage');
const lang = storage.getDataSync('lang');
const lang_index_data = lang.data ? lang.data : 0;
const reg = new RegExp('"',"g");  
const lang_index = lang_index_data.replace(reg, "");  

`

**Comment by myliuyx** [comment]
一直就是以 字符串传递的~

**Comment by Zmor** [comment]
const storage = weex.requireModule('bmStorage');
const locale = storage.getDataSync('key');

实测在安卓下返回的是一串json，ios是字符串
比如：locale = 'en'
安卓返回 [ "en" ]
IOS返回 "en"

**Comment by xiaohuapunk** [comment]
我们确认一下

**Comment by aa453509345** [comment]
我们测试了一下，安卓端总体会返回对象的data字段对应是正是你存入的类型 
如下存入：`storage.setDataSync("key", "test");`
`var data = storage.getDataSync('key');`   
data.data对应类型为String
