### ISSUE TITLE
2018.7.18更新后，tabbar切换无法正常触发beforeBackAppear周期

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#245]
### Your questions.
-tabbar内的页面要在离开一次tabbar后（app前后台切换，或者路由到非tabbar页面再回来），切换tabbar时才会触发生命周期，不然只会触发disappeared周期。
-
### Environment. 
- Mobile model: 小米6
- Mobile system: android8
- Dev platform: windows
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 怀疑是初始化的时候没入页面栈
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by Tilang** [comment]
@myliuyx @PerseveranceZ 刚刚发现这个问题同样存在于ios系统下

**Comment by myliuyx** [comment]
2018年07月26日 新版本修复此问题
