### ISSUE TITLE
scroller使用showRefresh属性，下拉刷新会闪退

### ISSUE THREAD

**Issue by ChenArno** [bmfe/eros#247]
### Your questions.
-scroller使用showRefresh属性，下拉刷新会闪退，而使用list则不会这个情况
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x
平台是安卓模拟器，使用的eros版本是2018.07.18

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
Android 的 scroller 不支持扩展的下拉刷新，你换成 list 组件吧

**Comment by ChenArno** [comment]
最初版本是可以的，不知道什么原因改成不支持了，也只能先list了。
