### ISSUE TITLE
提交google play收到SSL Error Handler错误

### ISSUE THREAD

**Issue by zassq** [bmfe/eros#248]
提交google play后被reject了，收到邮件说SSL Error Handler错误，请问应该如何修复这个问题？
这个是google给的文章：
[https://support.google.com/faqs/answer/7071387](https://support.google.com/faqs/answer/7071387)

**Comment by aa453509345** [comment]
webview直接处理了SSL错误，应改为提示用户是否处理

**Comment by myliuyx** [comment]
因为 SSL 的验证 google 查的严一些，但是国内一般都不会做这个检测。
https://www.cnblogs.com/shoneworn/p/8182615.html
你可以参考这个 对 com.benmu.framework.activity.GlobalWebViewActivity 类 做一些修改吧。

**Comment by aa453509345** [comment]
下版本会处理
