### ISSUE TITLE
Could not resolve project :nexus.

### ISSUE THREAD

**Issue by likeDate** [bmfe/eros#249]
Unable to resolve dependency for ':app@yingyongbaoDebug/compileClasspath': Could not resolve project :wxframework.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoDebugAndroidTest/compileClasspath': Could not resolve project :nexus.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoDebugAndroidTest/compileClasspath': Could not resolve project :wxframework.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoDebugUnitTest/compileClasspath': Could not resolve project :nexus.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoDebugUnitTest/compileClasspath': Could not resolve project :wxframework.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoRelease/compileClasspath': Could not resolve project :nexus.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoRelease/compileClasspath': Could not resolve project :wxframework.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoReleaseUnitTest/compileClasspath': Could not resolve project :nexus.
Open File
Show Details

Unable to resolve dependency for ':app@yingyongbaoReleaseUnitTest/compileClasspath': Could not resolve project :wxframework.
Open File
Show Details

**Comment by PerseveranceZ** [comment]
好好看文档 执行 install.sh 脚本

**Comment by liudakehpu** [comment]
执行install.sh之后依然有报错，一堆人报这个问题，非得慌着关这些issue干嘛，问题根本就没解决

**Comment by heynchy** [comment]
我也曾遇到过这个问题，我的处理方式是：
可以试试把wxframework包和nexus包手动删除后，然后重新执行install.sh；主要是检测一下wxframework和nexus 两个依赖包有没有下载下来，一般来说如果wxframework或者nexus 没有加载下来，就会报这个错误。

**Comment by githubmzgg** [comment]
按照这个方法解决了问题，搜了好久才搜到这个原因。
