### ISSUE TITLE
嵌套list高度问题

### ISSUE THREAD

**Issue by Ethan-zjc** [bmfe/eros#250]
slider多页面，每个页面分为上中下三个部分（包含tabbar）， top固定高度，中间为可滚动list，通过下面 .test 控制中间内容的高度，ios可以控制距离底部的距离，bottom设置多少android底部都会被遮挡一部分

 ` <template>
    <div class="wrapper">
        <div class="class-list"></div>

        <slider class="slider" auto-play="false" infinite="false" scrollable="true" :index="curIndex" @change="conChange">
            <div class="frame" :style="{height: pageH + 'px'}" v-for="(item,index) in classes">
                <div class="test">
                    <class-list :tagId="curIndex"></class-list>
                </div>
            </div>
        </slider>
        
        <div class="bot"></div>

    </div>
</template>
<script>
import util from '../../utils/util';

import list from './list';

import { CLASSES, SUBCLASSES } from '../../class/config'

export default {
    components: {
        'class-list': list
    },
    created() {
        this.init()
    },
    data() {
        return {
            curIndex: 0,
            classes: [],
            isShow : false,
            pageH: weex.config.eros.deviceHeight,
        }
    },
    methods: {
        init() {
            this.classes = CLASSES
        },
    }
}
</script>
`
`<style scoped>
    .class-list {
        width: 750px;
        height: 144px;
        position: fixed;
        top: 0px;
        background-color: aqua;
    }
    .frame {
        position: relative;
    }
    .test {
       position: absolute;
       width: 750px;
       top: 144px;
       bottom: 100px;
    }
    .bot {
        position: fixed;
        height: 100px;
        width: 750px;
        bottom: 0px;
        background-color: aqua;
    }
</style>`

**Comment by xiaohuapunk** [comment]
你可以试试其他方法，看看能否实现你想要的效果，这种设置样式显示不同的问题基本都是 Weex 自身存在的问题，你需要给weex 官方提bug https://weex.incubator.apache.org/cn/bug-report-guidelines.html

**Comment by Tilang** [comment]
滚动容器会占满页面剩下的高度，你可以利用这个特性来实现你要的效果。

**Comment by Ethan-zjc** [comment]
@xiaohuapunk 好的，我去官网提一个，谢谢，通过判断设备，然后区分高度计算可以，但是感觉减去的值很莫名其妙

**Comment by Ethan-zjc** [comment]
@Tilang 嵌套的list的父元素必须设置高度，不然ios的list不会显示，在android到是有你说的这个特性，但是底部的高度识别不了，会被遮挡一部分
