### ISSUE TITLE
新版本app前后台切换事件不触发

### ISSUE THREAD

**Issue by locationisme** [bmfe/eros#251]
### Your questions.
-新版本app前后台切换事件不触发
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
提供下版本等信息?安卓 还是 ios ?

**Comment by xiaohuapunk** [comment]
需要在当前显示的vue页面做监听

**Comment by locationisme** [comment]
@myliuyx @xiaohuapunk 安卓新init的项目使用了提供的原生tabbar，在主页通过全局事件来监听，此时的前后台切换事件不触发

**Comment by myliuyx** [comment]
已修复2018年07月26日 更新。
