### ISSUE TITLE
[新功能]希望添加设置隐藏状态栏功能

### ISSUE THREAD

**Issue by akFace** [bmfe/eros#252]
希望添加设置隐藏状态栏功能或者横屏功能。目前横屏可以直接使用css旋转页面来做，但是状态栏没法隐藏

**Comment by Tilang** [comment]
https://bmfe.github.io/eros-docs/#/zh-cn/eros_widget?id=setnavigationinfo
这个可以设置要不要状态栏啊

**Comment by akFace** [comment]
this.$navigator.setNavigationInfo({
    title: '',                              // 中间区域标题    
    navShow: true,                          // 是否显示导航栏
    statusBarStyle: 'Default'               // 状态栏文字颜色：Defautl 黑色， LightContent 白色
}, () => {
     // 点击回调
    console.log("您点击了导航条中间区域。")
})
 
@Tilang  这个？ 这只有设置导航条不显示和状态栏颜色的 ，没有设置状态栏不显示的 。

**Comment by Tilang** [comment]
navShow: false, // 是否显示导航栏    这样就行了，那个是一体的。自己定义一个顶部导航栏或者用weexui的

**Comment by akFace** [comment]
@Tilang 老哥， 我说的是状态栏啊，不是导航栏啊

**Comment by xiaohuapunk** [comment]
下个版本支持一下

**Comment by xiaohuapunk** [comment]
最新版本已经支持 详情看一下更新日志
