### ISSUE TITLE
Android waterfall组件里的position: sticky无效

### ISSUE THREAD

**Issue by locationisme** [bmfe/eros#254]
### Your questions.
-给 waterfall 组件里的header加上position: sticky样式无效
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
weex 的问题请直接给weex 官方提bug
