### ISSUE TITLE
隔了几天 在xcode 模拟器上 报错

### ISSUE THREAD

**Issue by HZZformGD** [bmfe/eros#255]
### Your questions.
-
报错了 
从com.taobao.weex.bridge爆出来的。 求帮忙
模拟器上进入eros demo 页面 但是  就卡着 没了
libc++abi.dylib: terminating with uncaught exception of type NSException
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 11
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by varSmallRookie** [comment]
咋没人解释一下

**Comment by varSmallRookie** [comment]
问题解决了，node版本至少大于9

**Comment by HZZformGD** [comment]
@varSmallRookie   升级node 版本就好？

**Comment by varSmallRookie** [comment]
更新node版本，然后重新安装脚手架进行打包就好了

**Comment by HZZformGD** [comment]
@varSmallRookie  多谢今晚回去尝试一波

**Comment by HZZformGD** [comment]
@varSmallRookie  好像不行我升级到 node 10 版本了 卸载了eros-cli 重新安装 然后 把 node_modules 删除了 再安装还是一样的错误

**Comment by varSmallRookie** [comment]
我是将整个项目给删了，然后重新init了一个新项目，并且重新eros dev后一切正常了

**Comment by xiaohuapunk** [comment]
从报错看像是语法导致的 js 报错，仔细排查一下

**Comment by HZZformGD** [comment]
@varSmallRookie  但是   没改过东西呀 重新下载的模板 弄了好久一样出错。 今晚再回去看看只能

**Comment by xiaohuapunk** [comment]
这种使用问题你多在群里与其他人交流交流，问问别人是什么原因 isuess 先关了
