### ISSUE TITLE
原生tabbar，几个页面同步加载问题，及tabbar.watchIndex问题

### ISSUE THREAD

**Issue by mrlionline** [bmfe/eros#256]
### 用原生tabbar，A,B,C,D四个页面同步加载，打开主页时其它页面请求同时发生了

       用tabbar.watchIndex监听tabbar切换，但在A,B,C,D四个页面的created里都监听，只有一个生效

       这样便没有了意义，我不能在一个页面的监听事件里控制当index为其它页面时其它页面里的事件
-
-
### Environment. 
- Mobile model: 努比亚Z11
- Mobile system: Android 6.0.1
- Dev platform:windows
- Node: 8.9.3
- Npm: 5.5.1

-

**Comment by PerseveranceZ** [comment]
用 beforeAppear 之类的我们拓展的生命周期试试

**Comment by mrlionline** [comment]
@PerseveranceZ 不行，在A页面的beforeAppear写一个alert，打开app会alert两次，在B,C,D其中一个的beforeAppear里写个alert，打开app时会alert三次

**Comment by myliuyx** [comment]
wathIndex 问题已经修复 
参考： https://bmfe.github.io/eros-docs/#/zh-cn/update_log_all?id=_20180726
