### ISSUE TITLE
关于scroller 下拉涮新调用refreshEnd出现闪退问题

### ISSUE THREAD

**Issue by bigfongcom** [bmfe/eros#259]
### Your questions.
-
-
### Environment. 
- Mobile model: mi6
- Mobile system: miui
- Dev platform: android8.0.0
- Node: 8.x.x
- Npm: 5.x.x

该组件scroller 设置为ref="list" :showRefresh="true" @refresh="onrefresh"
下拉涮新获取数据后调用this.$refs["list"].refreshEnd()出现闪退出当前页面

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
Android scroller 不支持我们扩展的下拉刷新，你换用list 或者使用weex的下拉刷新组件吧

**Comment by bigfongcom** [comment]
说明：在原有`<scroller>、<list>`组件基础上添加`showRefresh`属性来控制是否需要显示下拉刷新组件；

showRefresh {bool}：当值为`true`时 native 端自动为`<scroller>`或`<list>`添加下拉刷新组件（缺省此属性或者值为`false`时不会显示下拉刷新组件）；

你们教程说明里提示是支持的啊，现在去掉了？

**Comment by xiaohuapunk** [comment]
iOS 两个组件都支持，Android 只有 list 支持，文档我加个备注，你先替换成list 实现吧

**Comment by bigfongcom** [comment]
好的
