### ISSUE TITLE
eros下拉刷新增强，在调用refreshEnd方法时，程序崩溃

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#260]
### Your questions.
-下拉刷新增强效果能够实现，但是在调用refreshEnd方法结束动画时，程序会崩溃。
-只测了android，ios不知道情况
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by uncleLian** [comment]
- scroller的下拉增强在结束时，安卓出现闪退然后重启应用的情况，还会导致iconfont图标全部为X，ios正常

**Comment by xiaohuapunk** [comment]
scroller 只有iOS 支持扩展的下拉刷新，Android 不支持，换成 list 组件吧

**Comment by xiaohuapunk** [comment]
@Tilang @uncleLian list组件有问题吗？

**Comment by xiaohuapunk** [comment]
先关闭了，有问题在反馈吧
