### ISSUE TITLE
新版本内存泄漏

### ISSUE THREAD

**Issue by akFace** [bmfe/eros#261]
### Your questions.
-
-
### Environment. 
- Mobile model: 小米note3
- Mobile system: 安卓7.1.1
- Dev platform: windows
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 数据加载量多，tab快速切换的情况下。【大量数据场景】加载echarts图表数据量大

### Reappearance of the problem (It's best to have a screenshot).
- 
![screenshot_2018-08-03-17-14-35-325_vip bizhihui a](https://user-images.githubusercontent.com/22288837/43635510-deb20f9c-9741-11e8-952a-aacf1416b452.png)
![image](https://user-images.githubusercontent.com/22288837/43635553-02d45dda-9742-11e8-8749-0ab865fce6b3.png)
每一个tab对应不同的组件

![screenshot_2018-08-03-17-06-54-705_com miui home](https://user-images.githubusercontent.com/22288837/43635497-d497ef2c-9741-11e8-8e5d-79d50959118d.png)

images.githubusercontent.com/22288837/43634922-1f6d1254-9740-11e8-8b8c-bfaceee0a3c5.png)
![screenshot_2018-08-03-17-08-09-582_vip bizhihui a](https://user-images.githubusercontent.com/22288837/43634938-250fa456-9740-11e8-82e6-a575bd23cec7.png)
![screenshot_2018-08-03-17-07-22-891_vip bizhihui a](https://user-images.githubusercontent.com/22288837/43634943-288aaa18-9740-11e8-97e5-88576cacdac9.png)

**Comment by akFace** [comment]
补充友盟统计错误日志：

![image](https://user-images.githubusercontent.com/22288837/44026284-19537358-9f25-11e8-86c5-cc8a8e293933.png)

![image](https://user-images.githubusercontent.com/22288837/44026290-2135cc42-9f25-11e8-8941-cc42666fbb79.png)
![image](https://user-images.githubusercontent.com/22288837/44026387-772d01b0-9f25-11e8-93eb-8d749cbbe70a.png)

**Comment by xiaohuapunk** [comment]
如果很好复现就在群里 @一下，远程调试一下 @kang558

**Comment by akFace** [comment]
不太好复现。还需要什么错误信息。我贴过来吧  @xiaohuapunk

**Comment by akFace** [comment]
F:\truxing\ganlan_bc_app\platforms\android\WeexFrameworkWrapper\wxframework\eros-framework\src\main\java\com\benmu\framework\extend\hook\ui\components\HookWXText.java
这里面的broadcastreceiver注册后一直没注销，估计是这个导致内存泄漏的

**Comment by akFace** [comment]
加载很长很长的列表，内存占用暴增
