### ISSUE TITLE
希望能够扩展android端检测并更新apk的方法

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#262]
### Your questions.
-框架底层升级了不好更新。。。
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by akFace** [comment]
是的，安卓必备的啊。下载功能即[文件传输](http://natjs.com/#/zh-cn/reference/network/transfer)和安装apk的插件

**Comment by PerseveranceZ** [comment]
底层变动更新版本号即可
