### ISSUE TITLE
Adnroid自定义更新jsbundle失败。

### ISSUE THREAD

**Issue by zhangjanp** [bmfe/eros#263]
### Your questions.
- 高配Android可能会出现更新失败，原因是设置新版jsVersion为异步。
-
### Environment. 
- Mobile model: OPPO R15
- Mobile system: Android 8

### What do you think may be caused by the analysis of the problem.
更新版jsbundle后，会重新设置新版jsVersion，但这个操作为异步操作。导致重启app前未完成这一步操作，致使app读取的还是旧版jsbundle。

```
// eros-nexus/src/main/java/com/benmu/framework/utils/SharePreferenceUtil.java
// setDownLoadVersion
// #39 
sharedPreferences.edit().putString(Constant.SP.SP_DOWNLOAD_VERSION, version).apply();
```

~~apply()~~ Changed to  **commit()**

**Comment by myliuyx** [comment]
thank you ， Has been modified
