### ISSUE TITLE
希望支持设置状态栏背景色

### ISSUE THREAD

**Issue by bigfongcom** [bmfe/eros#266]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

现在框架状态栏背景色与顶部导航栏颜色一同设置的，希望分开独立设置

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
你可以自定义页面来实现，不要用原生的导航栏

**Comment by dstweihao** [comment]
我也有这样的需求，比如写一个vue页面，想要单独修改这个页面标题栏背景颜色，Android端做沉浸式处理，一直没找到好的解决方案。
