### ISSUE TITLE
使用原生Tabbar跳转到子页后，子页里无法跳转到指定Tabbar页

### ISSUE THREAD

**Issue by bigfongcom** [bmfe/eros#267]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

子页里使用
 tabbar.openPage({
          index:1
})
此方法无法跳转

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
这个方法需要在tabbar页面调用，其他页面返回操作还是要调 router.back 方法
