### ISSUE TITLE
$navigator使用异常

### ISSUE THREAD

**Issue by bigfongcom** [bmfe/eros#268]
### Your questions.
-
-
### Environment. 
- Mobile model: mi6
- Mobile system: android
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

android:给$navigator,设置左或右图标，经常是图标不不显示，有时显示是一个黑色块，并给左边设置图片情况下，点击后回调事件没有触发，即左边的点击事件用不了，如果换为文字，点击的回调事件是有效的

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
贴一下代码吧
