### ISSUE TITLE
地图引入为空对象

### ISSUE THREAD

**Issue by mawei1191546352** [bmfe/eros#269]
### Your questions.
- 
-var amap = weex.requireModule('amap') 引入的对象是空的
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- iOS、Android的集成按照官网 集成，之后引入var amap = weex.requireModule('amap') 发现是{};
`<weex-amap class="map" id="map2018" compass="true" scale="true" geolocation="true" :zoom="15" :center="pos">
<weex-amap-marker :position="pos" :title="point.title" ></weex-amap-marker>
</weex-amap>`

地图是能显示的，但仅此而已

![image](https://user-images.githubusercontent.com/24433377/44324255-acb6c700-a487-11e8-8347-9b114d46677c.png)

- 就是拿到amap对象 为{}，无法进行其他操作

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
在 vue 的生命周期里面操作 `amap`
