### ISSUE TITLE
【新功能】iOS友盟统计添加自定义事件 

### ISSUE THREAD

**Issue by akFace** [bmfe/eros#270]
### Your questions.
-希望iOS友盟统计添加自定义事件 ，安卓的已经有了，文档还没写上而已。
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by xiaohuapunk** [comment]
good idea

**Comment by xiaohuapunk** [comment]
统计插件已更新欢迎使用 https://bmfe.github.io/eros-docs/#/zh-cn/plugin_umAnalytics
