### ISSUE TITLE
library not found for -lAFNetworking

### ISSUE THREAD

**Issue by zjcboy** [bmfe/eros#272]
### Your questions.
使用eros-cli新建的空白项目 在执行xcode调试时报错
library not found for -lAFNetworking

![image](https://user-images.githubusercontent.com/8294751/44345889-20c48f80-a4c7-11e8-8677-88c00948c5ef.png)

### Environment. 
xcode 9.4.1

**Comment by xiaohuapunk** [comment]
请按照文档加载iOS所需依赖，最后注意 打开的文件的后缀是` .xcworkspace`
