### ISSUE TITLE
 Could not find license-gradle-plugin.jar

### ISSUE THREAD

**Issue by hiXing** [bmfe/eros#273]
### Your questions.
-
eros init 获取一个纯净模板之后，执行  install.sh 更新依赖，
导入到AS之后报错

-
### Environment. 
- Dev platform: /windows
- Node: v9.11.2
- Npm: 6.0.1

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
![image](https://user-images.githubusercontent.com/9985104/44441012-2de39a80-a5fd-11e8-929e-cbcaa4b51442.png)

**Comment by myliuyx** [comment]
android studio 提示的什么 修改 最好不要随便确定。
一般android studio新版都会更新 android stduio 的一些插件版本 如果你确定了 可能就需要对应的做一些适配，如果没有安卓基础 可能会很头疼。
Eros 现在使用的 android studio 版本是 3.0.1版本。
'com.android.tools.build:gradle:3.0.0
gradle_version  gradle-4.1

**Comment by hiXing** [comment]
谢谢了，找到原因了，
![image](https://user-images.githubusercontent.com/9985104/44635452-0fecb000-a9d8-11e8-9489-01fe396f4279.png)

这两个模板生成的Android项目下的**Project**的**build.gradle**不一样，
纯净模板比默认模板多了一个一段配置

![这是纯净版的](https://user-images.githubusercontent.com/9985104/44635418-d7e56d00-a9d7-11e8-9c55-f4efcfd8e1e5.png)

![这是默认的](https://user-images.githubusercontent.com/9985104/44635496-783b9180-a9d8-11e8-8c50-4530c50b5697.png)

我把纯净模板的 **_subprojects_** 注释掉，就不报这个错误了，
或者不注释，修改**纯净模板**的 sdk 的build.gralle 

![image](https://user-images.githubusercontent.com/9985104/44635385-8ccb5a00-a9d7-11e8-84b2-e2485de369ce.png)

把 `version "0.14.0"` 改为 ` version "0.11.0"` 也能解决这个问题。
