### ISSUE TITLE
原生title支持右上角按钮吗

### ISSUE THREAD

**Issue by 527430408** [bmfe/eros#274]
### Your questions.
- 原生title支持右上角按钮吗
- 在文档里没看到有说明
- 如果没有 希望可以出一个,可以在routers.js里配置 或者 在created里调用方法配置

**Comment by PerseveranceZ** [comment]
@527430408 https://bmfe.github.io/eros-docs/#/zh-cn/eros_widget?id=setrightitem beforeAppear 调用

**Comment by 527430408** [comment]
不好意思 没看到 谢谢！
