### ISSUE TITLE
eros 浏览器启动 后出现 Upgrade Required , mac 系统

### ISSUE THREAD

**Issue by JK3412** [bmfe/eros#275]
### Your questions.
mac 系统eros dev 后 浏览器启动后 显示Upgrade Required, 文档提示 node > 9 , 但是当我把node 升级到9后就启动不了, 
提示:
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 9.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

node-sass 也升级到4.9.3 , 也无效， 把node 降回8， 可以启动 但是 显示Upgrade Required
端口 8890，52077 ， 可以正常访问 文件地址, 
npm rebuild node-sass --force 也没用, 
node-sass ， 删除了 在安装也没用 也是 4.9.3
求大神指点

-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
@bbac3412 你用 n 或者 nvm 多切几个版本试试 这中间有几个小版本会出现这样的问题，并用淘宝源下载会比较好
