### ISSUE TITLE
关于全局websocket

### ISSUE THREAD

**Issue by 527430408** [bmfe/eros#276]
### Your questions.
websocket相关代码应该写在哪里
eros appActive 中需要重连websocket 应该写全局的
mediator 里写eros不行吗 试过之后没有相关代码执行

**Comment by PerseveranceZ** [comment]
代码没执行吗？文档里面说了 mediator 写入之后需要重新 eros dev ，重启 app 。

**Comment by 527430408** [comment]
![9fe5ed95-8304-474e-92ed-dd17d24e6987](https://user-images.githubusercontent.com/19465367/44566886-8dc77600-a7a2-11e8-8b0a-14e7ac32a3a5.png)
test 可以打印出来
test1 test2 都不能打印出来

用console.log xcode 也没有输出

**Comment by xiaohuapunk** [comment]
@527430408 appActive、appDeactive 的事件只有当前栈顶的的weex页面才会响应

**Comment by 527430408** [comment]
@xiaohuapunk 已经写出来了 谢谢
