### ISSUE TITLE
关于websocket服务器断开

### ISSUE THREAD

**Issue by 527430408** [bmfe/eros#277]
### Your questions.
websocket 由服务器断开后 重连是有bug吗?
onopen不会被触发
![915a1f56-645a-4a5e-a662-fe42a263bf0b](https://user-images.githubusercontent.com/19465367/44616620-ab214080-a885-11e8-99be-f9a987178edd.png)
这是在一直重连 但是找不到服务器，然后开启服务器后就不会报404了。应该就是重连上了，但是不会触发onopen的监听

代码在这里
![b30c20be-b118-41a7-9a22-4d774b841f4e](https://user-images.githubusercontent.com/19465367/44616769-8aa6b580-a888-11e8-8496-a5fe88fa5614.png)

**Comment by 527430408** [comment]
onclose里的close()只是测试一下

**Comment by xiaohuapunk** [comment]
服务器终止连接会回到 onclose，重连的话需要在重新调用连接方法

**Comment by 527430408** [comment]
我已经写了没三秒重新连接 但是服务器断开 没有调用到onclose

**Comment by xiaohuapunk** [comment]
@527430408 我们的热刷新用的也是同一个实现，重连机制是没问题的，你可以测试一下，先eros dev开启服务，打开app会提示连接成功，然后终止服务，再次eros dev开启服务，会重新连接，可以从服务端分析分析问题
