### ISSUE TITLE
android文本框退格问题

### ISSUE THREAD

**Issue by LonelyCodelang** [bmfe/eros#278]

**Comment by xiaohuapunk** [comment]
提供一下 测试 代码

**Comment by LonelyCodelang** [comment]
[demo.txt](https://github.com/bmfe/eros/files/2322256/demo.txt)


在值删完后，this.mobile_no 一直会有一个字符串

**Comment by LonelyCodelang** [comment]
`                    <input type="text" placeholder="请输入手机号码" v-model.trim="mobile_no" slot="value" class="input" :autofocus=false value="" />`
用的v-model做的双向绑定，在提交获取mobile_no时先输入内容，再把清空内容，获取到一直还会剩最后一个字符串，清空不了

**Comment by myliuyx** [comment]
weex 安卓的 v-model 暂时还有些问题 .
