### ISSUE TITLE
全面屏手机屏幕高度获取有误

### ISSUE THREAD

**Issue by Tilang** [bmfe/eros#279]
### Your questions.
-红米note5 设置=》全面屏=》全面屏手势（隐藏虚拟键）下，获取到的屏幕高度仍然是设置为经典导航键（显示虚拟键）时的屏幕高度。造成适配问题。
### Environment. @
- Mobile model: 红米note5
- Mobile system: android 8.1.0
- Dev platform: android
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- weex的屏幕高度获取方法没有考虑虚拟功能键占有屏幕高度的问题。
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
新增了一个 虚拟键盘的全局属性  virtualButtonsHeight  你可以借助一下~
