### ISSUE TITLE
bmBundleUpdate.download在android下不起作用

### ISSUE THREAD

**Issue by sheatming** [bmfe/eros#281]
### Your questions.
- ios中正常，android在未更新前可以正常使用（有leakCanary的版本），更新后bmBundleUpdate可以正常使用(getJsVersion可以使用), 走到download时 就GG了 无报错 无效果。在callback中console.log或是执行动作没有触发。

### Environment. 
- Mobile model: 模拟器/真机
- Mobile system: android 5.x
- Dev platform: darwin/windows
- Node: 9.11.2(windows)
- Npm: 5.6.0(windows)

### What do you think may be caused by the analysis of the problem.
- 不熟悉android的代码，在相应位置插入Log.i是可以打印出传进去的参数

### Reappearance of the problem (It's best to have a screenshot).
- 配置正确，在未更新前可以正常使用

**Comment by xiaohuapunk** [comment]
查一下App的版本号是否设置正确，可以抓包看一下请求参数？这个App版本号需要在AndroidStudio中设置的

**Comment by sheatming** [comment]
@xiaohuapunk 
版本号对应检查过没问题，抓包也能抓过来diff的地址，吧地址放到download中的path执行，然后就没然后了.

**Comment by sheatming** [comment]
download的callback里的任何东西不执行，打印resData也不执行

**Comment by xiaohuapunk** [comment]
群里有人也用了，没有说有问题，你如果确认是eros的问题，把环境准备好，可以在群里直接@安卓同学
