### ISSUE TITLE
关于android微信支付

### ISSUE THREAD

**Issue by 527430408** [bmfe/eros#282]
### Your questions.
ios微信支付能正常build.
android按照文档每一步都做了,报了两个错.是关于umeng的.
WXEntryActivity.java 文件报错
![8fb54410-acf1-4804-ad08-f2be92f8d9cf](https://user-images.githubusercontent.com/19465367/44698620-4cd9a500-aab3-11e8-89fd-77938baf6692.png)

**Comment by PerseveranceZ** [comment]
截图下报错

**Comment by myliuyx** [comment]
diff 下 github 上对应的文件做下修改吧， 最近更新了 umeng库。
```
https://github.com/bmfe/eros-template/blob/source/platforms/android/WeexFrameworkWrapper/app/src/main/java/com/benmu/wx/wxapi/WXEntryActivity.java
```
