### ISSUE TITLE
关于状态栏投递的问题

### ISSUE THREAD

**Issue by LingCn** [bmfe/eros#284]
![wechatimg170](https://user-images.githubusercontent.com/22288787/44770456-b54f8180-ab9a-11e8-83dc-153b5d4abcb0.jpeg)

页面状态栏配置代码
'page': {
        'homePage': 'tabBar',
        'mediatorPage': '/mediator/index.js',
        'navBarColor': '#3aa4d0',
        'navItemColor': '#ffffff'
    },

出现原因dom使用了box-shadow: 0 0 10px rgba(0,0,0,0.18);

**Comment by myliuyx** [comment]
最好不要使用 shadow。

**Comment by LingCn** [comment]
目前已经暂时取消使用这个属性，但是之前的并没有这个问题哦

**Comment by xiaohuapunk** [comment]
shadow 是 weex sdk本身的问题，后续weexsdk更新我们会及时跟进，应该会解决这个问题，先关闭了

**Comment by LingCn** [comment]
好的，谢谢
