### ISSUE TITLE
热更新 BSDIFF 数据失败 记录

### ISSUE THREAD

**Issue by 527430408** [bmfe/eros#285]
### Your questions.
- 按照eros默认热更新做的 已经做好服务器版本控制 根据xcode来看 js文件都已经下载好了
![aab49ae1ca81c9bb3f49de7d5d44bca0](https://user-images.githubusercontent.com/19465367/44837562-873a7200-ac6c-11e8-9b88-3895cd7dfa4d.png)
这个问题还需要什么配置之类的吗

**Comment by xiaohuapunk** [comment]
多半是因为patch包和当前本地的zip包不匹配导致的
