### ISSUE TITLE
点击安卓虚拟按钮返回问题

### ISSUE THREAD

**Issue by LingCn** [bmfe/eros#289]
### Your questions.
问题描述：内置包的情况下，使用原生tabBar的时候，点返回有时候tabbar页面也在路由的length里面，即点击虚拟按键的返回会把按我点击的tabbar页面都切换

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by myliuyx** [comment]
你可以参考下 demo 里 路由功能  设置APP首页  可以到 tabbar 。
好像并没有出现您这种情况， 能否描述的更详细些~

**Comment by LingCn** [comment]
路由是正常的，这个问题不是每次都出现，暂时也没办法描述清楚，我再看看
