### ISSUE TITLE
关于点击home回到桌面不正常退出

### ISSUE THREAD

**Issue by LingCn** [bmfe/eros#290]
### Your questions.
在Android上点击home回到桌面，app不正常退出，当通过返回按钮监听homeBack退出成功之后，bug恢复正常

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by wszwj** [comment]
当通过返回按钮监听homeBack退出成功之后???

**Comment by LingCn** [comment]
androidFinishApp () {
            const globalEvent = weex.requireModule('globalEvent')
            globalEvent.addEventListener('homeBack', options => {
                (this.curHomeBackTriggerTimes === this.maxHomeBackTriggerTimes) && this.$router.finish()
                this.curHomeBackTriggerTimes++
            })
        },

当这个函数调用能够退出app的时候，描述的bug回复正常，否则点击home键app都会被退出

**Comment by myliuyx** [comment]
其他手机也会 按home 键退出吗？
不管是 weex 还是 eros 都并没有对 home 键做任何处理的， 可能是您手机什么设置导致的？

**Comment by LingCn** [comment]
其它手机也会哦，不过没试过demo会不会，我测试一下
