### ISSUE TITLE
android 原生tab 生命周期怎么监测 eros{}(页面全局事件)无效

### ISSUE THREAD

**Issue by phoenixsky** [bmfe/eros#291]
### Your questions.
- android 原生tab 生命周期怎么监测 eros{}(页面全局事件)无效

### What do you think may be caused by the analysis of the problem.
- 非tab页面 `beforeAppear`等方法 都正常回调
- tab页面,没有调用

**Comment by myliuyx** [comment]
你用的是什么版本
[tabbarItem1.txt](https://github.com/bmfe/eros/files/2359771/tabbarItem1.txt)
这个都可以正常走生命周期

**Comment by PerseveranceZ** [comment]
@phoenixsky 有问题提供下测试代码，没有的问题的话就close吧

**Comment by phoenixsky** [comment]
额 好像是我理解错了. 以为切换到每个tab页的时候,才会调用'appeared' ,原来所有的tab页的'appeared'是一起调用的.  这样的话,首次打开app需要加载的页面过多,有没有类似懒加载的生命周期. 利用tabChange?

**Comment by xiaohuapunk** [comment]
ok，多在群里交流交流 先关闭了
