### ISSUE TITLE
eros dev报错

### ISSUE THREAD

**Issue by zhijijason** [bmfe/eros#292]
今天我eros init，再运行cnpm install，然后再运行eros dev报错：
ERROR in /usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/script-loader.js!/usr/local/lib/node_modules/eros-cli/node_modules/.7.1.5@babel-loader/lib!/usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/selector.js?type=script&index=0!./src/js/pages/demo/index.vue
Module not found: Error: Can't resolve 'bui-weex/src/components/bui-button' in '/Users/jason/Desktop/weex/gd/src/js/pages/demo'
 @ /usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/script-loader.js!/usr/local/lib/node_modules/eros-cli/node_modules/.7.1.5@babel-loader/lib!/usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/selector.js?type=script&index=0!./src/js/pages/demo/index.vue 7:18-63
 @ ./src/js/pages/demo/index.vue?entry=true

ERROR in /usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/script-loader.js!/usr/local/lib/node_modules/eros-cli/node_modules/.7.1.5@babel-loader/lib!/usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/selector.js?type=script&index=0!./src/js/pages/demo/other/bui.vue
Module not found: Error: Can't resolve 'bui-weex/src/components/bui-swipe-cell' in '/Users/jason/Desktop/weex/gd/src/js/pages/demo/other'
 @ /usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/script-loader.js!/usr/local/lib/node_modules/eros-cli/node_modules/.7.1.5@babel-loader/lib!/usr/local/lib/node_modules/eros-cli/node_modules/.0.6.12@weex-vue-loader/lib/selector.js?type=script&index=0!./src/js/pages/demo/other/bui.vue 11:21-70
 @ ./src/js/pages/demo/other/bui.vue?entry=true

**Comment by PerseveranceZ** [comment]
`Module not found: Error: Can't resolve 'bui-weex/src/components/bui-button' in '/Users/jason/Desktop/weex/gd/src/js/pages/demo'`
你引入了 bui-weex 这个库现在有些脱离标准 可能需要自行引入
