### ISSUE TITLE
有没有对应支持、可用的富文本编辑器？

### ISSUE THREAD

**Issue by hzm07** [bmfe/eros#297]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
没有，可以通过 webview 和 app 交互引入一个比较好的库
