### ISSUE TITLE
Android Eros plugin互调用问题

### ISSUE THREAD

**Issue by janxy** [bmfe/eros#298]
var helloplugin = weex.requireModule('helloplugin')
helloplugin.hello()
这样调用plugin里面的hello没有问题，，相反在插件里面如何通知前端呢？

**Comment by xiaohuapunk** [comment]
native 主动触发 js 方法 1.可以通过 globalEvent ；2.可以调用module的方法传入callback，native端调用callback；具体请看weex官方文档，或者参考已有插件的实现
