### ISSUE TITLE
安卓中activity与week WeexModule 通信

### ISSUE THREAD

**Issue by mingxinyiriyi** [bmfe/eros#299]
### Your questions.
-
-
### Environment. 
- Mobile model: MI5
- Mobile system:Android
- Dev platform: windows/
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
自定义NFC插件，继承 WeexModule的java类中，调用了原生的native activity并且执行。得到数据如何返回给继承 WeexModule的java类，给前端调用数据。
![1](https://user-images.githubusercontent.com/15307525/45526736-fa1a2000-b80a-11e8-96cf-b5e78f99438f.png)
![2](https://user-images.githubusercontent.com/15307525/45526739-fd151080-b80a-11e8-8d63-aefdd49c67b7.png)

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by phoenixsky** [comment]
> 将jsCallback定义为成员变量,在newIntent的回调中,调用

```
/**
 * Created by Rocky on 2017/12/18.
 */

public class NFCModule extends WXModule {

	public static final int REQUEST_CODE = 1001;


	JSCallback jsCallback;

	@JSMethod
	public void read(JSCallback jsCallback) {
		this.jsCallback = jsCallback;
		if (!hasNFC()) {
			jsCallback.invoke(ModuleUtil.error("该设备不支持NFC"));
			return;
		}
		if (!enableNFC()) {
			jsCallback.invoke(ModuleUtil.error("请在设置中开启NFC"));
			return;
		}

		Intent intent = new Intent(mWXSDKInstance.getContext(), NFCReadTextActivity.class);
		((Activity) mWXSDKInstance.getContext()).startActivityForResult(intent, REQUEST_CODE);

	}

	@Override
	public void onActivityResult(int requestCode, int resultCode, Intent data) {
		super.onActivityResult(requestCode, resultCode, data);
		if (resultCode == Activity.RESULT_OK) {
			if (requestCode == REQUEST_CODE) {
				jsCallback.invoke(ModuleUtil.result(data.getStringExtra(NFCReadTextActivity.EXTRA_CODE)));
			}
		}
	}


	public boolean hasNFC() {
		PackageManager packageManager = mWXSDKInstance.getContext().getPackageManager();
		return packageManager.hasSystemFeature(PackageManager.FEATURE_NFC);
	}

	public boolean enableNFC() {
		NfcManager manager = (NfcManager) mWXSDKInstance.getContext().getSystemService(Context.NFC_SERVICE);
		NfcAdapter adapter = manager.getDefaultAdapter();
		if (adapter != null && adapter.isEnabled()) {
			return true;
		} else {
			return false;
		}
	}
}

```

**Comment by mingxinyiriyi** [comment]
onNewIntent(Intent intent) 是ReadTextActivity 安卓原生的activity中的方法。没有返回到onActivityResult，并且报错。其实也没有MainActivity这个类。

 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=Intent { act=android.nfc.action.NDEF_DISCOVERED typ=text/plain flg=0x10000000 cmp=com.benmu.wx/com.benmu.pluginsimple.ReadTextActivity (has extras) }} to activity {com.benmu.wx/com.benmu.framework.activity.MainActivity}: java.lang.NullPointerException: file
![3](https://user-images.githubusercontent.com/15307525/45541487-e1792c80-b841-11e8-9b88-c8eeb9e2bbb2.png)
![4](https://user-images.githubusercontent.com/15307525/45541489-e2aa5980-b841-11e8-9cb5-9b62281773b6.png)
![5](https://user-images.githubusercontent.com/15307525/45541491-e50cb380-b841-11e8-8a71-d7e6e32804a1.png)
![6](https://user-images.githubusercontent.com/15307525/45541501-e6d67700-b841-11e8-9b98-243642cd315c.png)

**Comment by phoenixsky** [comment]
晕,只是让你参考一下,把callback改成 类的成员变量的写法  .我只是把我之前封装的代码 让你看一下.怎么`把得到数据返回`.
