### ISSUE TITLE
eros使用情况总结

### ISSUE THREAD

**Issue by hejie20170930** [bmfe/eros#3]
### eros 使用中常见错误。
> 1.Windows下安装环境报错，有时候需要eros团队配合才能搭建好环境
> 2.UI组件，少部分人没接触bui-weex以及weex-ui导致eros团队封装进去的组件看不懂，建议使用的人可以自己封装组件以及一起丰富组件库的内
> 3.前端代码以及安卓底层的代码中注解较少，不便于理解框架内部机制
> 4.APP更新机制需要改进
> 5.打包过后的apk文件比较大，可以出一个文档来告知如何缩小安装包的大小...
> 6.调试文件中的刷新按钮能不能独立出来，减少调试时间，便于更快速的开发
> 7.文档说明不够详细，有许多小知识点文档中没有介绍，需麻烦eros团队里面的人才能做到。
> 8.封装进来的bui-weex,weex-ui以及weex-amap等最好给个地址便于新手查询
> 9.有空可以拓展一下获得手机信息等参数，如电池量，IMEI码等，参照nat.js
> 10.可以考虑集成一波sqllite
### eros 使用须知
> 1.使用前需了解VUE，ES6以及WEEX的开发机制，经常看到有人问vue语法问题以及官方文档里面的内容，加大了工作量
> 2.了解WEEX封装好的demo以及可以使用的组件，eros是基于weex的二次封装，所以最好对WEEX有了一定的熟悉程度之后再来用框架做APP。

**Comment by hejie20170930** [comment]
忘记加上了，方便的话集成一波支付宝支付

**Comment by PerseveranceZ** [comment]
1.Windows下安装环境报错，有时候需要本木团队配合才能搭建好环境（fix）
2.UI组件，少部分人没接触bui-weex以及weex-ui导致本木封装进去的组件看不懂，建议使用的人可以自己封装组件以及一起丰富组件库的内（weex-ui,bui 已经可以正常使用）
3.前端代码以及安卓底层的代码中注解较少，不便于理解框架内部机制（慢慢完善）
4.APP更新机制需要改进（慢慢拓展，目前没有问题）
5.打包过后的apk文件比较大，可以出一个文档来告知如何缩小安装包的大小...（可配置依赖在开发计划中）
6.调试文件中的刷新按钮能不能独立出来，减少调试时间，便于更快速的开发（已实现双击刷新，报错日志弹出）
7.文档说明不够详细，有许多小知识点文档中没有介绍，需麻烦本木团队里面的人才能做到。（待完善）
8.封装进来的bui-weex,weex-ui以及weex-amap等最好给个地址便于新手查询（内置的已干掉）
9.有空可以拓展一下获得手机信息等参数，如电池量，IMEI码等，参照nat.js（开发中）
10.可以考虑集成一波sqllite（待商榷）
11.支付宝（后续接入）
