### ISSUE TITLE
tabBar现在是3个tab, 后来新增了一个tab，通过全量更新，更新后没有生效，还是原来的3个tab

### ISSUE THREAD

**Issue by wehnhew** [bmfe/eros#303]
### Your questions.
-tabBar现在是3个tab, 后来新增了一个tab，通过全量更新，更新后没有生效，还是原来的3个tab
-
### Environment. 
- Mobile model: Android
- Mobile system: 7.0
- Dev platform: windows
- Node: 10.4.1
- Npm: 6.1.0

**Comment by xiaohuapunk** [comment]
eros.native.js 配置文件是内置到原生工程中的，目前这个配置文件不支持热更新，因为app每次启动的时候都需要先读取这个文件来初始化weex相关环境，你的需求是需要动态设置tabBar的配置，你看一下bmTabbarModule 相关方法，应该可以满足你的需求
