### ISSUE TITLE
eros中使用原生tabBar后，ui组件里的遮罩挡不住tabBar菜单

### ISSUE THREAD

**Issue by wowtrxqn** [bmfe/eros#304]
### Your questions.
- eros中使用原生tabBar后，在tabBar页面里的ui组件中遮罩挡不住tabBar菜单
-
### Environment. 
- Mobile model: android
- Mobile system: 5.1
- Dev platform: darwin\/windows/linux
- Node: 10.0.8
- Npm: 6.0.0

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
![bug](https://user-images.githubusercontent.com/24369118/45857144-0281d600-bd8a-11e8-922f-8e2011475078.jpg)

**Comment by xiaohuapunk** [comment]
tabBar是最顶级页面，页面中的ui是不能覆盖tabbar上面的，alert 可以使用 widget 中的 notice

**Comment by wowtrxqn** [comment]
> tabBar是最顶级页面，页面中的ui是不能覆盖tabbar上面的，alert 可以使用 widget 中的 notice

好的，谢谢
