### ISSUE TITLE
IOS 项目中pod swift 库问题

### ISSUE THREAD

**Issue by IOSzhangwei** [bmfe/eros#306]
### Your questions.
-
在IOS  Podfile中导入pod 'Charts' 。添加use_frameworks!。
执行pod install。
报错：[!] The 'Pods-WeexEros' target has transitive dependencies that include static binaries: (/Users/zhangWei/Desktop/gold_weex_carteam/platforms/ios/WeexEros/Pods/WeexPluginLoader/WeexPluginLoader.framework)

报错原因是 weexSDK，有一个静态库，，但是我单独导入weexSDK是没有任何问题的，，但是我导入pod 'BMBaseLibrary' 出现了这个问题，你们的库中有依赖weexSDK，在pod install 中导致了这个问题，请问有解决方案吗？

**Comment by xiaohuapunk** [comment]
eros 依赖的库有包含 静态库的，所以会报错，你可以排查一下

**Comment by bengban** [comment]
WeexPluginLoader.framework 包含静态库，而cocoapods1.4.0还不支持混编。
我这边尝试下来最快的解决方案是：
1.  使用cocoapods处理OC第三方库引用。 在Podfile去掉use_framework!, 这样eros相关的引用能加入到项目中；
2. 使用carthage处理swift第三方库。然后编译好的framework放到项目中就好了。
