### ISSUE TITLE
在IOS12下，eros.native.js中的navBarColor对navigator的背景颜色没有效果，都是白色，不管把navBarColor改成什么都一样

### ISSUE THREAD

**Issue by zhijijason** [bmfe/eros#307]
### Your questions.
-
-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by clotee** [comment]
同问，谢谢！
![image](https://user-images.githubusercontent.com/11476395/45870817-70e08b80-bdbe-11e8-8afa-1b182cdf5b82.png)

**Comment by PerseveranceZ** [comment]
首先确认下改动完了之后重新启动 eros dev 并重新 build 的 app 后是否还会出问题，如果还是有问题，近期我们会做 ios 12 的兼容。

**Comment by zhijijason** [comment]
> 首先确认下改动完了之后重新启动 eros dev 并重新 build 的 app 后是否还会出问题，如果还是有问题，近期我们会做 ios 12 的兼容。

是的，eros.native.js中的navBarColor改动后，我重新eros pack后再运行在IOS12下的，IOS12下导航条的背景颜色navBarColor不管怎么改都是白色的，在IOS11下是没问题的

**Comment by clotee** [comment]
> 首先确认下改动完了之后重新启动 eros dev 并重新 build 的 app 后是否还会出问题，如果还是有问题，近期我们会做 ios 12 的兼容。

是的 各种反复操作，依然存在。

**Comment by xiaohuapunk** [comment]
问题已解决请把iOS基础库升级到1.3.1 https://bmfe.github.io/eros-docs/#/zh-cn/app_base_library?id=change-log

**Comment by zhijijason** [comment]
> 问题已解决请把iOS基础库升级到1.3.1 https://bmfe.github.io/eros-docs/#/zh-cn/app_base_library?id=change-log

哦，好的，谢了

**Comment by zhijijason** [comment]
> https://bmfe.github.io/eros-docs/#/zh-cn/app_base_library?id=change-log

请问一下，我pod repo update后，然后再pod install，那个BMBaseLibrary库的版本还是1.3.0，是不是还没更新到中央仓库呢？pod 已经改成1.3.1了，写法如下：pod 'BMBaseLibrary', :git => 'https://github.com/bmfe/Benmu-iOS-Library.git', :tag => '1.3.1'

**Comment by xiaohuapunk** [comment]
@zhijijason `Benmu-iOS-Library` 仓库名字以修改为`eros-plugin-ios-baseLibrary`，引入方式文档已修改，请使用`pod 'ErosPluginBaseLibrary', :git => 'https://github.com/bmfe/eros-plugin-ios-baseLibrary.git', :tag => '1.3.1'`，来引用

**Comment by zhijijason** [comment]
> @zhijijason `Benmu-iOS-Library` 仓库名字以修改为`eros-plugin-ios-baseLibrary`，引入方式文档已修改，请使用`pod 'ErosPluginBaseLibrary', :git => 'https://github.com/bmfe/eros-plugin-ios-baseLibrary.git', :tag => '1.3.1'`，来引用

哦，知道了，谢谢
