### ISSUE TITLE
请求头默认格式为什么会是： "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by clotee** [bmfe/eros#312]
### Your questions.
不做任何配置修改的情况下，请求头看到是： "application/x-www-form-urlencoded"，文档默认是：application/json

### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.10.0
- Npm: 6.2.0
@xiaohuapunk xiao
2018-09-27 14:56:03.482587+0800 *******[5318:1790925] <Weex>[error]BMBaseRequest.m:51, BMCommonRequest Request_URL>>>>>>>>>>>>>>>>:<NSMutableURLRequest: 0x1c0013220> { URL: https://************/login, Method POST, Headers {
    "Accept-Language" =     (
        "zh-Hans-CN;q=1"
    );
    "Content-Type" =     (
        "application/x-www-form-urlencoded"
    );
    "User-Agent" =     (
        "CityClubStaff/1.0.0 (iPhone; iOS 11.1.1; Scale/3.00)"
    );
} }

'BMBaseLibrary', :git => 'https://github.com/bmfe/Benmu-iOS-Library.git', :tag => '1.3.1'的情况下出现的问题。
其次返回错误结果为什么，每次data是空对象，后台是又返回值得
[info]BMAxiosNetworkModule.m:42, request data: {
data = {
};
errorMsg = "Bad Request(Code:400)";
status = 400;
}

**Comment by clotee** [comment]
'BMBaseLibrary', :git => 'https://github.com/bmfe/Benmu-iOS-Library.git', :tag => '1.3.1'的情况下出现的问题。
其次返回错误结果为什么，每次data是空对象，后台是又返回值得
<Weex>[info]BMAxiosNetworkModule.m:42, request data: {
    data =     {
    };
    errorMsg = "Bad Request(Code:400)";
    status = 400;
}

**Comment by xiaohuapunk** [comment]
刚刚看了一下，请求头的地方判断有点问题。我优化一下

**Comment by xiaohuapunk** [comment]
1.已优化，先执行 `pod cache clean ErosPluginBaseLibrary`清除一下本地缓存，然后在执行 `pod update` 拉取最新代码即可；
2.400的问题是访问出错，你自己排查一下吧；

**Comment by clotee** [comment]
第二点我这边是发现，当请求状态码为400的时候，请求返回结果的data值被置空了，但接口是调试工具是可以接收到结果的。

**Comment by xiaohuapunk** [comment]
检查字段，请求格式，既然报了 400 说明请求已经通了，自己排查一下应该是你们业务问题

**Comment by clotee** [comment]
好的，谢谢🙏
