### ISSUE TITLE
android build failed

### ISSUE THREAD

**Issue by CGerAJ** [bmfe/eros#313]
### Your questions.
- android build failed! i set gradle version for 4.1,  what can i do?
-
### Environment. 
- Dev platform: darwin
- Node:v9.2.0
- Npm:6.4.1

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
<img width="1620" alt="android build failed" src="https://user-images.githubusercontent.com/20548301/46190317-ba345c00-c325-11e8-8cb5-a707bbcd2296.png">

error msg

```
Unable to find a matching configuration of project :nexus: None of the consumable configurations have attributes.
```
:app:preSamplechannelReleaseBuild

**Comment by myliuyx** [comment]
Carefully read the document！
```
https://bmfe.github.io/eros-docs/#/zh-cn/base_init
```
Should be the init the wrong step

**Comment by CGerAJ** [comment]
tks! i do it～solved my problem.

**Comment by CGerAJ** [comment]
need run install.sh script
