### ISSUE TITLE
android checkbox 、button等控件为啥不能正常显示

### ISSUE THREAD

**Issue by zhongyao-x** [bmfe/eros#315]
### Your questions.
- android checkbox、button 不能正常显示 
### Environment. 
- Mobile model: Nexus 5
- Mobile system: android 8.0
- Dev platform: darwin\/windows/linux
- Node: 8.11.1
- Npm: 6.4.1

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
[截图1](https://img1.wxzxzj.com/vuedbd7837b2dca2e51bf1710706be84e84e.jpeg)
[截图2](https://img1.wxzxzj.com/vuedc9987d25c3c043d38b442618fe1eb906.jpeg)

**Comment by zhongyao-x** [comment]
<style name="AppTheme" **parent="Theme.AppCompat.Light.DarkActionBar"**>
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>

不知道什么原因初始化android项目时没有加 Theme.AppCompat.Light.DarkActionBar 加上就好了
Theme.AppCompat.Light.DarkActionBar

**Comment by PerseveranceZ** [comment]
@xuzhongyao 非常感谢 可能我们安卓兄弟太懒了。。。
