### ISSUE TITLE
微信登录分享和支付无法授权成功～闪一下就没了～

### ISSUE THREAD

**Issue by CGerAJ** [bmfe/eros#318]
### Your questions.
- 
-
### Environment. 
- Mobile model: 华为荣耀10
- Mobile system:安卓 8
- Dev platform: darwin
- Node: v9.2.0
- Npm: 6.4.1

### What do you think may be caused by the analysis of the problem.
- 微信开放平台生成的签名和包名一致 在app内点击授权 报错信息
https://developer.umeng.com/docs/66632/detail/66787
-  复查 签名和包名一致
- 删除微信缓存重试 卸载微信 也不行

求思路

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by fukai7722** [comment]
遇到同样的问题了
