### ISSUE TITLE
伪类:active状态反了

### ISSUE THREAD

**Issue by wmlgl** [bmfe/eros#324]
### Your questions.
- 对text标签使用伪类:active添加阴影后， 按下的状态没阴影，释放后反而有阴影了， 行为和focus一样
-
### Environment. 
- Mobile model: Android
- Mobile system: MIUI 10
- Dev platform: windows
- Node: 7.9.0
- Npm: 4.2.0

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
这应该是 weex sdk 的问题，可以反馈到 weex 那边。
