### ISSUE TITLE
ios中 点击带链接带cell 出现页面崩溃

### ISSUE THREAD

**Issue by 52imnet** [bmfe/eros#326]
### Your questions.
-
-
### Environment. 
- Mobile model: iphone6s
- Mobile system: iOS 10.2
- Dev platform: darwin
- Node: 10.12.0
- Npm: 6.4.1

### What do you think may be caused by the analysis of the problem.
- 问题描述，页面能正常渲染，点击带有link参数的cell 会出现页面崩溃

```
<template>
    <div :style="contentStyle">
            <list ref="list" :show-scrollbar="false" :showRefresh="true" @refresh="onrefresh">
                <cell v-for="(card, index) in cards" :key="index" :index="index">
                    <wxc-cell :title="card.name" :has-arrow="false" @wxcCellClicked="wxcCellClicked" :has-top-border="true" :desc="card.desc" :link="card.link">
                        <image class="image" :src="card.img" slot="value"></image>
                    </wxc-cell>
                </cell>
            </list>
        </div>
</template>
```
- 是否是因为weexsdk版本过低？

![image](https://user-images.githubusercontent.com/39212514/47279176-dfa14680-d601-11e8-9a38-a30b615e6044.png)

### Reappearance of the problem (It's best to have a screenshot).
- 
![image](https://user-images.githubusercontent.com/39212514/47280372-b7691600-d608-11e8-856e-7ee98ae2d385.png)

**Comment by PerseveranceZ** [comment]
Unexpected token '<'
这是 js 语法报错
