### ISSUE TITLE
使用fetch请求,url写全地址，params不解析。

### ISSUE THREAD

**Issue by simple-YoungBadBoy** [bmfe/eros#334]
代码截图
![image](https://user-images.githubusercontent.com/20324269/48040146-ad234c00-e1b2-11e8-9676-cca0a63d3bb6.png)
![image](https://user-images.githubusercontent.com/20324269/48040170-c0361c00-e1b2-11e8-867e-0ce51cb0cc69.png)
charles抓取到的地址 deviceId和msgId并没有变成params的值，而是直接被url解析了。
使用name给变量名是可以的，但是这个地址端口不同，需要单独这样写。
麻烦看下是什么问题 谢谢

**Comment by myliuyx** [comment]
暂时还不支持您这种写法~

**Comment by simple-YoungBadBoy** [comment]
已解决。
有2种解决方法：
1. 不改动源码写法：
使用url不需要params了，直接使用字符串模版写在url中。
![image](https://user-images.githubusercontent.com/20324269/48050782-ed4bf400-e1dd-11e8-98b5-70e12e9be204.png)
使用字符串写法就可以不用params了。

2. 改动源码：
在node_module/eros-widget/src/axios.js中，找到hendleAxios func，
修改后截图：
![image](https://user-images.githubusercontent.com/20324269/48050884-55023f00-e1de-11e8-99f4-cc4c8e7e4d23.png)
   1.上方解构的const改为let,因为url会被修改。
   2.加上一句if
   3.在requestPath复制后面pathFormater方法加上一个空值的参数,(用于判断是url还是name)
   4.找到pathFormater func,修改后截图：
![image](https://user-images.githubusercontent.com/20324269/48051060-fb4e4480-e1de-11e8-9eaa-24e9b9353d5d.png)
   将_path都放到上面使用let声明,然后加上if-else判断type=url ? 如果=url就说明是使用url方法，不需要使用apis转换一下。
   5.fetch方法请求按照官网写法即可
![image](https://user-images.githubusercontent.com/20324269/48051202-70217e80-e1df-11e8-97c0-479d98038169.png)

**谢谢Zero大佬的提示。**

**请eros开发者尽快使用第二个方法验证并更新上源码，如果能加上我的name就更好了，谢谢。**
