### ISSUE TITLE
eros搭配最新版本weex，已经无法查看inspector和调试dom

### ISSUE THREAD

**Issue by qld-cf** [bmfe/eros#335]
测试中

**Comment by qld-cf** [comment]
关闭拦截器直接 disconnect，热刷新无法用 => 此状况属于打包到安卓手机的app，AS自带模拟器正常

**Comment by theladderofsuccess** [comment]
那么，请问大佬是如何调试js的呢？

**Comment by qld-cf** [comment]
1、目前用的方法是：
现在用的方法是：eros dev跑起，weex debug跑起，用然后用真机装的demo扫描二维码，开启js debug可以调试js，关闭js debug查看dom
2、安卓手机可以用热刷新了

**Comment by qld-cf** [comment]
@PerseveranceZ 麻烦关掉issue
