### ISSUE TITLE
如何通过weex debug中调试js？

### ISSUE THREAD

**Issue by theladderofsuccess** [bmfe/eros#339]
### Your questions.
-据文档所述，在重复真机调试步骤之后，执行$weex debug命令，扫码打开之后，选择 Debugger 后并不能看到逻辑代码，点击 Inspector 也没法查看页面结构。
-
### Environment. 
- Mobile model: MI 8
- Mobile system: Android 8.1.0
- Dev platform: darwin\/windows/linux
- Node: 10.12.0
- Npm: 6.4.1

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
- 
![image](https://user-images.githubusercontent.com/37564229/48252730-6b0f3a00-e440-11e8-8156-aeab5ddbdb8b.png)

**Comment by theladderofsuccess** [comment]
没办法看到js调试内容，很难受，有些问题不知道错误在哪儿就真的没法改。

**Comment by qld-cf** [comment]
应该不是eros的锅，官方文档down下来weex debug一样问题，文档好像说要把devtool集成到到android，试过了没用..

**Comment by qld-cf** [comment]
@theladderofsuccess 我现在用的方法是：eros dev跑起，weex debug跑起，用然后用真机装的demo扫描二维码，开启js debug可以调试js，关闭js debug查看dom

**Comment by theladderofsuccess** [comment]
js已能成功调试，然而dom依然看不了，不明白原因，但还是谢谢。

**Comment by qld-cf** [comment]
> js已能成功调试，然而dom依然看不了，不明白原因，但还是谢谢。

@theladderofsuccess   用真机的demo，打开扫一扫，扫描weex debug出来的二维码，关闭上面的 JS DEBUG，无效可以试试刷新下，再不行就新建个weex纯净demo，跑npm start,自己项目的单页扔到index.vue来调dom
