### ISSUE TITLE
vivo X3L闪退

### ISSUE THREAD

**Issue by sheatming** [bmfe/eros#34]
### 简略的描述你的问题。
> 例：启动项目闪退
### 环境信息 
> 例子：
> * 开发平台：darwin
> * node 版本：8.9.0
> * npm 版本：5.6.0
> * 调试类型：真机
> * 调试系统版本: android 4.3
> * 开发工具及其版本 android studio 3.0

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：启动项目就闪退 可以看见启动页
![wechatimg870](https://user-images.githubusercontent.com/17745365/35190914-4e905680-fea8-11e7-8b39-fa5b0bbd139d.jpeg)

**Comment by myliuyx** [comment]
fix
