### ISSUE TITLE
安卓端获取定位失效

### ISSUE THREAD

**Issue by a243065157** [bmfe/eros#340]
### Your questions.
安卓端获取定位　已经添加了amap插件 在页面内也初始化了
-
```
this.$geo.get().then(data => {
          that.$notice.alert({
            title: '3333',
            message: '132312312'
          })
          locationLat = data.locationLat
          locationLng = data.locationLng
        })
```
这段方法没执行
-
### Environment. 
- Mobile model: 华为
- Mobile system: android 7.0
- Dev platform: /windows
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by David-Chen1999** [comment]
我小米8上运行实例代码，点击“插件|三方（选择集成）->定位”，总是显示获取位置失败

**Comment by myliuyx** [comment]
权限 还有就是您的 key 是否正确。

**Comment by yp199618** [comment]
key 需要在哪配置呢?
