### ISSUE TITLE
原生tabbar在 $router.open 一个页面后消失

### ISSUE THREAD

**Issue by liuliujiangjiang** [bmfe/eros#341]
如题，跳转参数如下：
         $router.open({
                    url: '/pages/mo/login.js',  // 页面对应的 js 地址(注意路径从 /pages/ 开始)
                    type: 'PUSH',  // 客户端定义动态类型，默认值为 PUSH 1. PUSH (将页面压栈到当前容器栈) 2.PRESENT （新建容器栈在进行压栈,从下面弹出新页面）3.TRANSLATION (动画类似QQ的侧滑抽屉效果)
                    canBack: true,  // 是否需要返回按钮
                    gesBack: true,  // 是否开启手势返回（默认开启，仅支持 iOS）
                    navTitle: '登录',  // 页面标题
                    navShow: true,  // 是否显示原生导航栏
                    statusBarStyle: 'Default',  // 系统状态栏文字颜色 1.Default：黑色， 2.LightContent: 白色
                    isRunBackCallback: false  // 为true时，用户点击返回（或Android物理返回按钮）时回调下面的callback方法，native端不做页面跳转
                }, function () {
                    // callback
                });

**Comment by liuliujiangjiang** [comment]
怎么才能让跳转时候tarbar一直显示？

**Comment by xiaohuapunk** [comment]
Eros 默认 TabBar 只在首页显示，绝大多数App也是这样的，要想一直显示需要修改原生代码的

**Comment by liuliujiangjiang** [comment]
thanks,可能我们的产品需求比较奇葩

**Comment by liuliujiangjiang** [comment]
> Eros 默认 TabBar 只在首页显示，绝大多数App也是这样的，要想一直显示需要修改原生代码的

thanks,可能我们的产品需求比较奇葩
