### ISSUE TITLE
Could not find lint-gradle-api.jar

### ISSUE THREAD

**Issue by vvisme** [bmfe/eros#342]
编译出错：
Gradle sync failed: Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
Searched in the following locations:
https://plugins.gradle.org/m2/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

都已更换镜像，依旧出上面的错误
buildscript {
    repositories {
//        jcenter()
//        mavenCentral()
//        google()

        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
    }
}

Android studio 3.0.1

**Comment by myliuyx** [comment]
这个26.1.2 是你修改了某项配置导致的， 具体可能是你打开项目的时候可能会有个提示，你点击OK就修改了！

**Comment by vvisme** [comment]
谢谢
