### ISSUE TITLE
想要将公共的数据请求放在外部，而不是每个页面都去请求，请问应该怎么做？

### ISSUE THREAD

**Issue by theladderofsuccess** [bmfe/eros#346]
### Your questions.
-
-
### Environment. 
![com](https://user-images.githubusercontent.com/37564229/49144422-4f5ccc80-f338-11e8-8e70-3e28658ae3e5.jpg)
![req](https://user-images.githubusercontent.com/37564229/49144431-5683da80-f338-11e8-890c-d817908e9771.jpg)

- Mobile model: mi 8
- Mobile system: Android   @@8.1.0
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 我在如上写法中，报错是 stream.$fetch is not a function. 注册bmAxios也是如此，请问是我想法就错了还是代码的问题？如果是前者，那么请问各位大佬有无更好的方法？对了，放在appboard也不对。请各位大佬赐教！感激不尽！
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
直接在 config/index 里面 用 Vue.prototype.$fetch 发请求

**Comment by theladderofsuccess** [comment]
@PerseveranceZ 大佬能具体说明一下吗？我的写法肯定没对，不知道怎么写了
`Vue.prototype.$getApi = (mineName, pageName, key, name) => {
    let params = {
        mineName: mineName,
        pageName: pageName,
        key: key,
        name: name
    };
    return this.$fetch({
        name: "COMMON.getInfo",
        method: "GET",
        data: params,
        header: {
            caller: "WeBuild"
        }
    }).then(resData => {
        console.log(resData);
    });
};`
项目要求的数据也很多，api也不同，总不能一个api写一个吧？
而且this始终是undefined，换成stream或bmAxios也不行。头疼好久了。看到之前有篇issue有提过类似的问题，但也没解决。。。

**Comment by theladderofsuccess** [comment]
参考解决办法：将API文件夹写在pages文件夹内通过export default暴露出来，js文件中引入js文件，其内容一定要是”字符串“：”字符串“的形式，否则不识别。别问为什么，问就是不知道！

**Comment by PerseveranceZ** [comment]
其实你可以使用 js 入口方式 用全局 mixins来做这件事
js 入口 参考如下方式 ： 
[https://github.com/karynsong/weex-eros/tree/a65fe9a9f12cc19ec4d6b64270d2705f66ac2cf1/fe/src/js/pages/demo](https://github.com/karynsong/weex-eros/tree/a65fe9a9f12cc19ec4d6b64270d2705f66ac2cf1/fe/src/js/pages/demo)
