### ISSUE TITLE
No response to creating a project download template

### ISSUE THREAD

**Issue by duqianchen** [bmfe/eros#353]
### Your questions.
-No response to creating a project download template
D:\weex>eros init
? Input project/app's name. eros-demo
? Input init version? 1.0.0
? Choose your template type. with A rich example And detailed project layering. (recommend)
? Input init android application id. com.demo.wx
- downloading template

-
### Environment. 
- Mobile model: iphoneX
- Mobile system: iOS 8
- Dev platform: darwin\/windows/linux
- Node: 8.x.x
- Npm: 5.x.x

### What do you think may be caused by the analysis of the problem.
- 
- 

### Reappearance of the problem (It's best to have a screenshot).
-

**Comment by PerseveranceZ** [comment]
在 git bash 中尝试

**Comment by duqianchen** [comment]
> 在 git bash 中尝试

已解决，在windows中会出现这问题，mac中就不会，然后在git bash中可以下载
