### ISSUE TITLE
初始化项目下载模板卡住

### ISSUE THREAD

**Issue by gettf** [bmfe/eros#362]
### Your questions.
eros init  卡在
downloading template，
无法退出

### Environment. 

- Dev platform: windows
- Node: 10.x.x
- Npm: 6.x.x

-

**Comment by PerseveranceZ** [comment]
使用 git bash

**Comment by wujingquan** [comment]
您好，在powershell下同样遇到该问题，切换至git bash就行了，请问这是什么原理？
