### ISSUE TITLE
weex 集成 eros

### ISSUE THREAD

**Issue by maoyu** [bmfe/eros#364]
你好，我现在项目是使用weex创建的。在这个基础上，能集成eros吗？因为weex开放的原生功能有限，我想使用eros提供的更多原生功能。谢谢。

**Comment by karynsong** [comment]
肯定是可以的，但是整体迁移项目肯定会有一定的成本，你可以根据现在 eros 的文档新建一个项目，然后把业务迁移进去，如果之前你是用 vue 写的，迁移成本应该比较低，如果是用 weex 的语法可能迁移成本会高一些，但是肯定能做
