### ISSUE TITLE
Android studio3.0.1构建失败

### ISSUE THREAD

**Issue by gdoudeng** [bmfe/eros#368]
### Your questions.
-Android studio3.0.1构建项目失败
错误:Unable to resolve dependency for ':app@samplechannelDebug/compileClasspath': Could not resolve project :wxframework.

![avatar](http://iplus-studio.top/Snipaste_2019-02-07_21-19-15.png)

### Environment. 
- Mobile model: OPPO R11
- Mobile system: 安卓7.1.1
- Dev platform: windows
- Node: 10.14.1
- Npm: 6.4.1

### Reappearance of the problem (It's best to have a screenshot).
- ![avatar](http://iplus-studio.top/Snipaste_2019-02-07_21-26-22.png)
![avatar](http://iplus-studio.top/Snipaste_2019-02-07_21-26-04.png)

**Comment by NotMyYida** [comment]
遇上同样的问题，楼主解决了吗

**Comment by gdoudeng** [comment]
> 遇上同样的问题，楼主解决了吗

没有啊...

**Comment by PerseveranceZ** [comment]
install.sh 没有执行完成 用 git bash 试试

**Comment by 970024540** [comment]
你需要重新安装基础库 
https://bmfe.github.io/eros-docs/#/zh-cn/app_base_library
