### ISSUE TITLE
全局scss文件引入问题

### ISSUE THREAD

**Issue by timlin00** [bmfe/eros#389]
请问如何全局引入通用的scss文件？在开发中，想要全局引入scss文件，现在只能每个vue文件都去引入，能不能有个全局的引入方案？

**Comment by PerseveranceZ** [comment]
appboard那个js试试呢

**Comment by pidogc** [comment]
我試過在那個文件中引入，但是報錯@語法錯誤，我在引入的scss文件中通過@import引入其他scss文件

**Comment by PerseveranceZ** [comment]
目前只能写公共的到处引入 js可以放在appboard




| |
杨明哲
邮箱：a2192466@163.com
|

签名由 网易邮箱大师 定制

在2019年04月12日 16:14，pidogc 写道：

我試過在那個文件中引入，但是報錯@語法錯誤，我在引入的scss文件中通過@import引入其他scss文件

**Comment by timlin00** [comment]
> 目前只能写公共的到处引入 js可以放在appboard | | 杨明哲 邮箱：a2192466@163.com | 签名由 网易邮箱大师 定制 在2019年04月12日 16:14，pidogc 写道： 我試過在那個文件中引入，但是報錯@語法錯誤，我在引入的scss文件中通過@import引入其他scss文件 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我试试，thx！
