### ISSUE TITLE
android刘海屏 高度问题

### ISSUE THREAD

**Issue by nikojxie** [bmfe/eros#398]
在IphoneX可获得正确高度 正常显示
android刘海屏水滴屏 获得的高度少一段 有什么属性可以解决吗
谢谢🙏

**Comment by hanliuxin5** [comment]
Android 刘海屏的适配需要原生开发人员来配合哦。

**Comment by nikojxie** [comment]
> Android 刘海屏的适配需要原生开发人员来配合哦。

好吧 谢谢
