### ISSUE TITLE
新建项目出错

### ISSUE THREAD

**Issue by hejie20170930** [bmfe/eros#4]
### 简略的描述你的问题。
> 新建项目安装时覆盖之前的项目
### 环境信息 
> 例子：
> * 开发平台：Windows
> * node 版本：8.0
> * npm 版本：5.3.0
> * 调试类型：模拟器
> * 调试系统版本: Android 4.0
> * 开发工具及其版本 vs code

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 例：新建项目后安装时会覆盖之前安装的项目，改了applicationid以及category两个仍然报错，百度搜索一波发现是 android:authorities="downloads.${APP_ID}" 这一句的问题，${APP_ID}删除后改成就正常安装
### 什么场景下会复现这个问题，复现率是多少。
> 例：百分百

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：
![image](https://user-images.githubusercontent.com/32407307/33975310-a54ffbae-e0c8-11e7-8567-aecbb3a85443.png)

**Comment by myliuyx** [comment]
手机上已安装的app 和你现在需要运行的app 存在冲突， 您可以试着 删除您手机上的app 重新安装就行了

**Comment by hejie20170930** [comment]
尝试过，当我将之前的项目删除后，可以安装成功，但是安装上新项目后安装旧的项目，依旧会覆盖上去
