### ISSUE TITLE
图片上传功能，快点点击完成按钮，会重复上传图片

### ISSUE THREAD

**Issue by Sunrise1970** [bmfe/eros#46]
### 简略的描述你的问题。
图片上传功能，快点点击完成按钮，会重复上传图片
### 环境信息 
> 例子：
> * 开发平台：mac
> * node 版本：8.9.2
> * npm 版本：5.6.0
> * 调试类型：真机
> * 调试系统版本: 安卓7.0 Redmi Note 4X

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 例：image.upload 图片上传功能快速点击完成 ，会重复上传图片
### 什么场景下会复现这个问题，复现率是多少。
> 例：非必现

![image](https://user-images.githubusercontent.com/15205625/35369908-9485220e-01c5-11e8-8bf7-3f188eaee19b.png)
![image](https://user-images.githubusercontent.com/15205625/35369918-a0496780-01c5-11e8-850e-419eceeae3d8.png)

**Comment by Sunrise1970** [comment]
今天又发现另一个奇怪的问题，就是：先不打开上传文件权限，选择图片后，多点击几次选择图片，然后再开启权限，就会出现重复选择图片的问题。(eros 2.0.0-beta.5)
![03014fbf4849ef857d5be2e9f3890f7d](https://user-images.githubusercontent.com/15205625/35491897-735b9118-04e4-11e8-98a4-65f6fbd3fd75.png)
![e04ca88ab3fd91ae5940fd2aaff77e86](https://user-images.githubusercontent.com/15205625/35491901-784abd7a-04e4-11e8-822a-d6343c78b2f8.jpg)

**Comment by myliuyx** [comment]
请问是否是必现的吗？
先不打开上传文件权限是什么权限？
多次测试并未复现重复问题，请问您还有其他的操作吗？

**Comment by Sunrise1970** [comment]
sd卡存储授权未授予。这个试了几次都是会重复上传的。

**Comment by myliuyx** [comment]
fix:
原因：未给予权限时，在接收callback后 判断权限问题，导致给予权限后选择图片后 同时返回给了多个callback。
解决：修改权限判断位置，并增加权限申请。
