### ISSUE TITLE
初始化完新项目后用as导入项目后出现错误

### ISSUE THREAD

**Issue by sheatming** [bmfe/eros#5]
### 简略的描述你的问题。
> 初始化完新项目后用as导入项目后出现错误
Error:Execution failed for task ':bmwidget:processDebugAndroidTestResources'.
> No slave process to process jobs, aborting
### 环境信息 
> * 开发平台：windows
> * node 版本：8.9.0
> * npm 版本：5.5.1
> * 调试类型：模拟器
> * 调试系统版本: android 5.0
> * 开发工具及其版本 android studio 3.0.1
### 什么场景下会复现这个问题，复现率是多少。
>  百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：
![_20171219104534](https://user-images.githubusercontent.com/17745365/34138296-c4cabcf0-e4a9-11e7-84a6-dc8396f9a495.png)

**Comment by myliuyx** [comment]
请问您是否 eros install --android  了？

**Comment by sheatming** [comment]
安装了，我在搞搞 感觉是我本身本地环境的问题，中间重启了一次 起来就这样了。

**Comment by PerseveranceZ** [comment]
@sheatming 确认下 GIT BASH 等执行 sh 脚本的工具已安装，并在windows下作为默认打开 .sh 文件的工具，windows下 eros install 默认会去执行 .sh 脚本

**Comment by aa453509345** [comment]
@sheatming 能否提供AS项目中weexframework目录结构截图

**Comment by sheatming** [comment]
环境之前是完好的，也没问题，今天建了一个新项目(新建的流程完整)，然后报的这个错。之后以前的项目也打不开了。

**Comment by sheatming** [comment]
撇清，不是eros的报错 不知道我怎么操作的 引起了一个as的bug，重启电脑以后再开没问题了
