### ISSUE TITLE
更新发布闪退

### ISSUE THREAD

**Issue by Sunrise1970** [bmfe/eros#54]
### 简略的描述你的问题。
首先，安装一个apk到手机，没有历史版本，数据库没有任何记录。
![image](https://user-images.githubusercontent.com/15205625/35778065-c0766784-09f3-11e8-9150-ce9fdbb3e22b.png)

然后修改代码，打个全量包，并且将全量包更新到服务器，
![image](https://user-images.githubusercontent.com/15205625/35778067-c4cde398-09f3-11e8-9496-5e4fec61472f.png)

这时，数据库有一条记录
![image](https://user-images.githubusercontent.com/15205625/35778070-ca7761d4-09f3-11e8-913d-de2434ad0c43.png)
。接着打开app，APP就会请求更新接口，
![image](https://user-images.githubusercontent.com/15205625/35778071-d179bae0-09f3-11e8-8425-a0042c8367fa.png)
![image](https://user-images.githubusercontent.com/15205625/35778072-d425e624-09f3-11e8-8a69-793aff4b7844.png)
，然后退出app重新打开，就是最新的app，这一切都很正常。
但是，假如在修改代码，再打个包上去，数据库存在两条记录，然后再重新打开app的时候，就出现闪退的情况了
现在的解决方案是：每次更新完之后，把数据库清掉，永远保持只有一条记录，就不会出现闪退了
### 环境信息 
> 例子：
> * 开发平台：mac
> * node 版本：8.9.2
> * npm 版本：5..6.0
> * 调试类型：模拟器/真机

> * 开发工具及其版本as

**Comment by PerseveranceZ** [comment]
We will fix this in this week.

**Comment by PerseveranceZ** [comment]
already fixed in https://github.com/bmfe/eros-publish/pull/2.
