### ISSUE TITLE
个推通知栏点击无效

### ISSUE THREAD

**Issue by liylmn** [bmfe/eros#55]
### 简略的描述你的问题。
> 例：图片上传导致系统崩溃。
### 环境信息 
> 例子：
> * 开发平台：windows
> * node 版本：8.9.1
> * npm 版本：5.5.1
> * 调试类型：真机
> * 调试系统版本: android 24
> * 开发工具及其版本 studio3.0

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 例：个推点击通知栏没有进ResultActivity，我用BroadcastReceiver测了一下，可以进入
### 什么场景下会复现这个问题，复现率是多少。
> 例：百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：

**Comment by myliuyx** [comment]
fix
原因：ResultActivity 并未注册到AndroidManifest.xml 导致。
修复：AndroidManifest.xml 配置 ResultActivity
