### ISSUE TITLE
滑动组件扩展

### ISSUE THREAD

**Issue by YNameUndefined** [bmfe/eros#59]
希望扩展一个滑动组件。
    效果类似于微信、QQ等应用单行对用户右滑后能对单行有相关操作。
谢谢

**Comment by PerseveranceZ** [comment]
@YNameUndefined 目前 eros 已经集成了 bindingx ，可以自行实现类似功能，详情请看 [bindingx](https://bmfe.github.io/eros-docs/#/zh-cn/advanced_bindingx).
