### ISSUE TITLE
全局变量属性部分获取不到

### ISSUE THREAD

**Issue by sheatming** [bmfe/eros#6]
### 简略的描述你的问题。
> 
![qq 20171220094245](https://user-images.githubusercontent.com/17745365/34241535-459340f2-e651-11e7-8120-cc9abbdf20bc.png)

### 环境信息 
> 例子：
> * 开发平台：windows
> * node 版本：8.x.x
> * npm 版本：5.x.x
> * 调试类型：模拟器
> * 调试系统版本: android 5
> * 开发工具及其版本 android studio 3

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 如图，新增的那些属性都没有
### 什么场景下会复现这个问题，复现率是多少。
> 百分百复现，调用即复现。

**Comment by aa453509345** [comment]
@sheatming  undertaking

**Comment by sheatming** [comment]
好吧

**Comment by PerseveranceZ** [comment]
@zjzmyh 这个问题在目前的最新的 sdk 中已经 fix ，可以重新 eros init 一个项目，花个十多分钟来进行迁移，迁移过程中又什么问题可以随时反馈。
ios: https://github.com/bmfe/eros-template/wiki/update-ios#110-20171229
android: https://github.com/bmfe/eros-template/wiki/update-android#206-%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
