### ISSUE TITLE
组件目录 `js/components` 下可添加相关配置文件，方便使用

### ISSUE THREAD

**Issue by lw1024** [bmfe/eros#69]
### 在使用中我发现 `js/components` 目录下的组件没有配置文件，使用的时候有点不方便，是否可以添加一些配置文件以方便使用。
> 比如，目前要使用里面的 `TabBar`组件得这样使用：
```
import Home from 'Components/tabs/bar.vue'
```

> 如果添加上 `package.json` 和 `index.js` 配置文件的话，那么可以这样使用：
```
import { TabBar } from 'Components'
```

加上这些配置文件后，也可以作为以后添加组件的模版，方便新手学习。

**Comment by PerseveranceZ** [comment]
@lw1024 
谢谢你的建议，开发者可以自行使用 index.js 来引入管理自己的组件这没错，不过你可以试试这样的方式，会把整个index.js 管理的所有组件都打包到JS bundle中，你可以看看weex-ui的引入其实还要修改`.babelrc`，使用babel-plugin-component，来引入需要的组件，以达到减小项目体积的目的，而且也无法保证开发者修改components的名称，综合考虑一下，就给一个文件夹，自行拓展最好。
