### ISSUE TITLE
安卓端bmchart组件改变高度没变化

### ISSUE THREAD

**Issue by vskvsk** [bmfe/eros#7]
### 简略的描述你的问题。
安卓端bmchart组件改动高度没变化，宽度是可以修改的。

### 环境信息 
> 例子：
> * 开发平台：darwin\/windows/linux
> * node 版本：6.10.2
> * npm 版本：5.4.2
> * 调试类型：模拟器/真机
> * 调试系统版本: Android 7.1.2
> * 开发工具及其版本 Android Studio 3.0.1

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
应该是系统兼容问题吧，IOS没试过。

### 什么场景下会复现这个问题，复现率是多少。
百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
安卓端bmchart组件改动高度没变化，不管是从行间样式修改还是在<style>修改都没变化。
代码部分：
![image](https://user-images.githubusercontent.com/8464263/34247221-ade98290-e66c-11e7-8c8e-0c8eab12ea97.png)
展示部分：
![image](https://user-images.githubusercontent.com/8464263/34247162-79930b1a-e66c-11e7-8977-266899f6b2ff.png)

**Comment by PerseveranceZ** [comment]
@vskvsk 已fix 会跟随下个版本一起上

**Comment by PerseveranceZ** [comment]
@vskvsk https://github.com/bmfe/eros-template/wiki/update-android sdk已更新
