### ISSUE TITLE
scroller 不执行start和end事件

### ISSUE THREAD

**Issue by sheatming** [bmfe/eros#76]
### 简略的描述你的问题。
> scroller 不执行start和end事件
### 环境信息 
> * 开发平台：windows
> * node 版本：8.9.0
> * npm 版本：5.5.1
> * 调试类型：模拟器/真机
> * 调试系统版本: android 5
> * 开发工具及其版本 xcode 9

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 使用weex官方的例子 在playground中可以使用。在eros中新建頁面 内容相同 无法调起scrollstart和end事件
### 什么场景下会复现这个问题，复现率是多少。
> weex例子：http://dotwe.org/vue/8711a2004bc7f55c83f0ff741f216a39

**Comment by xiaohuapunk** [comment]
scrollstart 和 scrollend 事件 `WeexSDK` 0.17 版本后支持的，Android 目前集成的是 0.16版本，所以不支持，近期会更新到 0.18版本，请关注群公告

**Comment by sheatming** [comment]
@xiaohuapunk 好的 谢谢
