### ISSUE TITLE
提供一些bug

### ISSUE THREAD

**Issue by Ahuangshang** [bmfe/eros#79]
1.下拉刷新界面下拉刷新头不回去，而且下面的内容也滑不出来
开发平台：你们的demo
测试机信息：所有安卓手机
截图：
![image](https://user-images.githubusercontent.com/15123689/36766194-cc7b3e54-1c6f-11e8-8a84-1cafaaae5ab7.png)
说明：我已修改AndroidSDK源码解决这个问题，需要的话可以联系我。
2.发布订阅页面不能传递0开头的数据
开发平台：你们的demo
测试机信息：vivo Y51 Android 5.1.1
截图：
![image](https://user-images.githubusercontent.com/15123689/36766286-302d9744-1c70-11e8-9265-d58ed25f60c1.png)
![image](https://user-images.githubusercontent.com/15123689/36766295-39e8fa80-1c70-11e8-8ca4-2915fc6046a1.png)

**Comment by karynsong** [comment]
感谢您的支持，第一个问题能直接来个 PR 么？这两个问题我们都会再下一版本的 demo 中进行修复

**Comment by myliuyx** [comment]
新版本的 下拉刷新 已经没有这个问题了。
订阅返回的问题 是因为 fastJson 有自动识别 类型的功能导致的。
新增不自动识别方法。

**Comment by Ahuangshang** [comment]
虽然18版本修复了这个问题，显然阿里没有采用我的修复方案，但是，在上拉或者下拉的时候你在滑动的时候你滑不到头，这样做，虽然解决了这个问题，但是用户体验还是不友好，我会再建议阿里开发工程师采用我的修改方案。
