### ISSUE TITLE
$axios ios端请求目前只返回了data对于用户体验很不好，希望能把status状态码也返回出来

### ISSUE THREAD

**Issue by ElegieShaw** [bmfe/eros#8]
### 简略的描述你的问题。
> 例：$axios ios端请求目前只返回了data对于用户体验很不好，不好判断请求是否成功。
### 环境信息 
> * 调试系统版本: ios 8
> * 开发工具及其版本 xcode 9

**Comment by xiaohuapunk** [comment]
@zjzmyh 这个问题在目前的最新的 sdk 中已经 fix ，可以重新 eros init 一个项目，花个十多分钟来进行迁移，迁移过程中又什么问题可以随时反馈。https://github.com/bmfe/eros-template/wiki/update-ios#110-20171229

最新的请求`module-bmAxios`的返回如下
```
{
    status: '',
    errorMsg:'',
    data: {}
}
```
