### ISSUE TITLE
安卓refresh下拉刷新的时候，再上滑动，会卡死了不动了

### ISSUE THREAD

**Issue by janxy** [bmfe/eros#83]
refresh下拉刷新的时候，再上滑动，会卡死了不动了

**Comment by PerseveranceZ** [comment]
![239571520236528_ pic_hd](https://user-images.githubusercontent.com/13193407/36964737-919de21a-2092-11e8-95af-c0fc0dd3b040.jpg)
![239581520236533_ pic_hd](https://user-images.githubusercontent.com/13193407/36964742-93796226-2092-11e8-978c-6defa4340137.jpg)
![239591520236533_ pic_hd](https://user-images.githubusercontent.com/13193407/36964744-958366c0-2092-11e8-816a-83ad0949d13c.jpg)
先这么解决下

**Comment by myliuyx** [comment]
新版本已经不会出现这样的问题了~。
weex 也修复了这个问题！
