### ISSUE TITLE
关于weex.config.eros参数问题

### ISSUE THREAD

**Issue by ChenArno** [bmfe/eros#84]
### 简略的描述你的问题。
> 例：在获取设备的高宽度时，deviceHeight，deviceWidth，发现ios下通过weex.config.eros能获取到，但是安卓下找不到，weex.config.env可以获取到
![Uploading WX20180306-111020.png…]()

### 环境信息 
> 例子：
> * 开发平台：darwin\/windows/linux
> * node 版本：8.x.x
> * npm 版本：5.x.x
> * 调试类型：模拟器/真机
> * 调试系统版本: ios 8
> * 开发工具及其版本 xcode 9

### 尽可能写下你对问题的分析，你觉得可能是由于什么造成的。
> 例：bmImage module 中不支持传递参数的类型，导致的崩溃。
### 什么场景下会复现这个问题，复现率是多少。
> 例：百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
> 答：

**Comment by ChenArno** [comment]
![wx20180306-111020](https://user-images.githubusercontent.com/22111171/37012417-779846c4-212f-11e8-8e81-7cd7918111b7.png)

**Comment by PerseveranceZ** [comment]
@ChenArno 更新完之后已经放入参数了，看一下没问题就close吧

**Comment by myliuyx** [comment]
已添加~
