### ISSUE TITLE
$fetch返回的data为空

### ISSUE THREAD

**Issue by howie95** [bmfe/eros#89]
### 简略的描述你的问题。
无论使用get还是post请求方式向php服务器请求数据，都可以拿到状态码200，php服务器也能收到请求，但是这边返回的resData里data一直是空的，直接在浏览器访问那个接口或者使用jquery的ajax都可以正常的取到数据，查看xcode的控制台发现请求的时候有一行错误
`WeexEros[1799:136141] <Weex>[error]BMBaseRequest.m:49, BMCommonRequest Request_URL>>>>>>>>>>>>>>>>:<NSMutableURLRequest: 0x60c00001f120> { URL: http://192.168.1.78/index/driver/login }`
同时我用get方法访问自己的一个node服务器的接口，就可以正常取到数据，也没有上面那条错误，不太懂php，请问是PHP服务器那边的问题吗，一般这种情况是什么引起的，小白求教了，感谢！！

### 什么场景下会复现这个问题，复现率是多少。
百分百复现，调用即复现。

**Comment by howie95** [comment]
查了一下资料感觉是前后端数据类型不匹配的原因，具体原因还是没搞明白，但是换了weex的stream模块之后就可以取到数据了。

**Comment by PerseveranceZ** [comment]
@howie95 需要提供下截图 抓包看下你的请求头和返回头

**Comment by howie95** [comment]
![image](https://user-images.githubusercontent.com/12136338/37267211-b7596d64-25f9-11e8-934d-b8fc3d1b78fa.png)
返回头是这样的，似乎用weex的stream模块也要写明响应类型type为json，不然返回的data就会解析成下面这样。。
![image](https://user-images.githubusercontent.com/12136338/37267403-05567b32-25fb-11e8-8507-09f69e528bf7.png)
写明type:json之后就是下面这样的
![image](https://user-images.githubusercontent.com/12136338/37267424-25664b6e-25fb-11e8-99b8-e52be809ce1b.png)

**Comment by PerseveranceZ** [comment]
@howie95 嗯 建议你服务器端声明默认 application/json ，就能使用 $fetch，使用 eros 封装的请求会好些，可以切换 mock，动态参数 , cookie 等

**Comment by howie95** [comment]
感谢！是后端输出的问题，已经解决了～
另外还遇到一个问题，不知道能不能在这里问下，我仿照demo里将首页的状态栏样式改为了白色
![image](https://user-images.githubusercontent.com/12136338/37270625-70e56444-260a-11e8-9a27-5bd0b45815ec.png)
然后用router.open跳往一个新页面
![image](https://user-images.githubusercontent.com/12136338/37270668-9a0338ec-260a-11e8-8bdc-b95458c53cfe.png)
可是我点击导航栏的返回按钮返回首页的时候状态栏样式又变成黑色了，然而我看demo里并不是这样的，请问是怎样可以保持状态栏样式一直是白色呢。

**Comment by PerseveranceZ** [comment]
@howie95 statusBar 是个全局单例 应该是你打开有的页面并没有设置 statusBarsStyle，而在 widget 里面每次跳转都默认了 Default 属性，所以就变成黑色了，我们这块 widget 在优化一下 改一下这个逻辑，你先看看你的跳转逻辑。

**Comment by howie95** [comment]
![image](https://user-images.githubusercontent.com/12136338/37272145-ba9fe43c-2610-11e8-99de-16d65c5f4456.png)
我是在首页触发orderlist模块里的checkOrder方法跳转的，orderlist也在created里设置了statusbarsStyle为白色，是因为这个的原因吗

**Comment by PerseveranceZ** [comment]
@howie95 嗯 你去掉试试 看下所有 open 的方法中 是不是有没写 statusBarStyle 的

**Comment by howie95** [comment]
发现问题了，刚才比较粗心，调试登陆页面的时候把登陆页面设置为了app主页，首页其实是登陆页面跳转过去的，可是我把首页设置为app主页之后，有没有办法让它一直显示导航栏呢，我在首页created里面写了navShow: true，可是跳转到别到页面之后，点击导航的返回键，首页的导航栏就不见了

**Comment by PerseveranceZ** [comment]
@howie95 你可以在 beforeAppear beforeBackAppear 里面都写上，或者首页自己用 weex 来实现导航条，因为首页比较特殊

**Comment by howie95** [comment]
了解了，你真是太有耐心了，非常感谢！ ;D
