### ISSUE TITLE
调用 this.$image.upload  拾取图片后 ，ios 的 顶部时间状态条的时间文字以及其他系统图标就消失了

### ISSUE THREAD

**Issue by poerlang** [bmfe/eros#9]
### 调用 this.$image.upload  拾取图片后 ，ios 的 顶部时间状态条的时间文字以及其他系统图标就消失了
> 
### 环境信息 
> * app 顶部背景色是黑色，文字是白色
> * this.$navigator.setNavigationInfo。。。（略）。。。 statusBarStyle: 'LightContent' 。。。
> * 调用 this.$image.upload
> * 接下来选拍照不会引发这个bug
> * 选择从相册拾取图片并取消，不会出现bug，如果点确定选择并预览图片，会立即出现这个bug

**Comment by poerlang** [comment]
![g](https://user-images.githubusercontent.com/3243514/34321170-d4cf2864-e843-11e7-98dd-4e8093238fcb.png)
上半部分是正常情况，然后编辑一个帖子，发图完成后，就变成下半部分的状况

**Comment by xiaohuapunk** [comment]
请按照教程升级一下工程相关文件 https://github.com/bmfe/eros-template/wiki/iOS%E7%9B%B8%E5%85%B3
