### ISSUE TITLE
npm install 不会安装 bindingx-parser

### ISSUE THREAD

**Issue by phaibin** [bmfe/eros#91]
> * eros-widget: 1.0.1-beta.1
> * 开发平台：darwin
> * node 版本：9.7.1
> * npm 版本：5.6.0
> * 调试类型：模拟器
> * 调试系统版本: ios 11
> * 开发工具及其版本 xcode 9

npm install 并没有安装上依赖的 bindingx-parser，导致eros dev报错

**Comment by PerseveranceZ** [comment]
@phaibin 删掉 node_modules , 重新 cnpm install 即可

**Comment by phaibin** [comment]
试过了，还是不行

**Comment by hanliuxin5** [comment]
你贴下你 npm install 前的 package.json

**Comment by phaibin** [comment]
换了一台电脑重新安装node环境，npm install依赖都可以安装，而且eros dev也没问题，看来还是我这里npm缓存的问题
