### ISSUE TITLE
在Nenus 5x上打开app 白屏

### ISSUE THREAD

**Issue by shenmashi** [bmfe/eros#95]
03-14 17:17:17.310  5598  5635 E weex    : [WXBridgeManager] invokeInitFramework java.lang.UnsatisfiedLinkError: No implementation found for int com.taobao.weex.bridge.WXBridge.initFrameworkMultiProcess(java.lang.String, com.taobao.weex.bridge.WXParams, java.lang.String, boolean) (tried Java_com_taobao_weex_bridge_WXBridge_initFrameworkMultiProcess and Java_com_taobao_weex_bridge_WXBridge_initFrameworkMultiProcess__Ljava_lang_String_2Lcom_taobao_weex_bridge_WXParams_2Ljava_lang_String_2Z)
03-14 17:17:17.310  5598  5635 E weex    :  at com.taobao.weex.bridge.WXBridge.initFrameworkMultiProcess(Native Method)
03-14 17:17:17.310  5598  5635 E weex    :  at com.taobao.weex.bridge.WXBridge.initFrameworkEnv(WXBridge.java:103)
03-14 17:17:17.310  5598  5635 E weex    :  at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1795)
03-14 17:17:17.310  5598  5635 E weex    :  at com.taobao.weex.bridge.WXBridgeManager.access$300(WXBridgeManager.java:110)
03-14 17:17:17.310  5598  5635 E weex    :  at com.taobao.weex.bridge.WXBridgeManager$8.run(WXBridgeManager.java:1547)
03-14 17:17:17.310  5598  5635 E weex    :  at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
03-14 17:17:17.310  5598  5635 E weex    :  at android.os.Handler.handleCallback(Handler.java:790)
03-14 17:17:17.310  5598  5635 E weex    :  at android.os.Handler.dispatchMessage(Handler.java:99)
03-14 17:17:17.310  5598  5635 E weex    :  at android.os.Looper.loop(Looper.java:164)
03-14 17:17:17.310  5598  5635 E weex    :  at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by hanliuxin5** [comment]
。。。 我估计就是你的打包环境不太对？
我 linux as 打出来的包你不就安装上了吗？

**Comment by shenmashi** [comment]
3.14更新后好了
