### ISSUE TITLE
扩展module遇到的一些问题

### ISSUE THREAD

**Issue by howie95** [bmfe/eros#96]
### 简略的描述你的问题。
  想要增加一个将图片转为base64的功能，但是原生开发知识太少了。。于是想到能不能给bmImage module直接增加一个方法，参照文档在BMImageModule.m里增加了以下代码

`
WX_EXPORT_METHOD(@selector(base64:callback::))

- (void)base64:(NSString *)url callback:(WXModuleCallback)callback
{
    UIImage *img = [UIImage imageWithContentsOfFile:url];
    NSData *imgData = UIImageJPEGRepresentation(img, 1.0f);
    NSString *encodedImgStr = [imgData base64EncodedStringWithOptions:NSDataBase64Encoding64CharacterLineLength];

    if (callback) {
        callback(encodedImgStr);
    }
}
`
可是在项目中weex.requireModule('bmImage')后并调用时却提示方法不存在
![image](https://user-images.githubusercontent.com/12136338/37439314-7f9e84dc-2832-11e8-8cd0-fd5e697bd2bd.png)
请问正确的修改思路应该是怎样的，感谢！

### 其他建议
  如果可以给weex的webview组件进行一下扩展就好了，就像rn那样可以在webview里通过window.onMessage 来触发函数并传输数据～

**Comment by xiaohuapunk** [comment]
你应该是忘记暴露方法了，请看这个教程 https://bmfe.github.io/eros-docs/#/zh-cn/ios_project?id=module-%e6%89%a9%e5%b1%95；
另外：官网的`<web>`组件是支持 webview 与 weex 交互的，详情需要看一下源码；
有问题可以在群里 @ 我

**Comment by howie95** [comment]
已经解决了 多写了一个冒号哈哈哈，太粗心了，感谢
