### ISSUE TITLE
使用了component/tabs/bar后，如果在根页面push一个新页面，再从新页面返回的时候，viewWillBackAppear没有被触发

### ISSUE THREAD

**Issue by super-chen** [bmfe/eros#98]
### 简略的描述你的问题。
使用了component/tabs/bar后，如果在根页面push一个新页面，再从新页面返回的时候，viewWillBackAppear没有被触发
### 环境信息 
> 例子：
> * 开发平台：MC
> * node 版本：8.10.0
> * npm 版本：5.6.0
> * 调试类型：模拟器
> * 调试系统版本: ios 8
> * 开发工具及其版本 xcode 9

### 什么场景下会复现这个问题，复现率是多少。
> 例：百分百复现，调用即复现。

### 详细的描述下你的 issue, 最好能有截图。（复杂的问题请一定仔细填写此项）
根视图用了beforeBackAppear，但是无响应
<img width="958" alt="1" src="https://user-images.githubusercontent.com/1482026/37502102-3b0026f2-290c-11e8-82a6-f91867fbd572.png">

**Comment by PerseveranceZ** [comment]
@super-chen https://github.com/bmfe/eros-widget#records 已经在 1.0.1@beta-8 中修复

**Comment by super-chen** [comment]
@PerseveranceZ 我当前用的版本是2.0.6-beta.4，貌似还是有这个问题哦

**Comment by PerseveranceZ** [comment]
@super-chen 和脚手架无关系 更新 widget
